### ISSUE TITLE
[ICBM - Classic 1.7.10-2.16.3b224-UNSTABLE build 224 for 1.7.10] Tracker not working!

### ISSUE THREAD

**Issue by AgentOfKGB** [BuiltBrokenModding/ICBM-Classic#102]
Trackers are a big part of this mod, so far everything else works fine, but playing on a pvp/raid server trackers are an absolute must! When you left click a player, it does say Now tracking <player>, however when you right click the homing missile it does not lock onto the target and set the targets coordinates to the control panel. If you could fix this ASAP that would be great as it would allow me to switch from DefenseTech to ICBM..

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.

**Comment by ghost** [comment]
It would be nice to add a "Launch" button in the launcher control panel and also to make an API with commands etc.

**Comment by GHXX** [comment]
> It would be nice to add a "Launch" button in the launcher control panel and also to make an API with commands etc.

If you would like to request a feature, open a new issue ticket, but do not comment on a random ticket, please.
