### ISSUE TITLE
Launch Pad Tier 3 Crashes Game

### ISSUE THREAD

**Issue by A5TC** [BuiltBrokenModding/ICBM-Classic#114]
My game crashed when I tied to placed a support frame on a LPT3.

I have 70+ other mods and I don't have any conflicts at all with my mods

BTW how do I stop a Red Matter after its been going for a long time (1-2 hours)?

**Comment by DarkGuardsman** [comment]
Any chance you have the crash report?

Redmatter should auto-decay after a set amount of time. Can't remember how long but antimatter will kill it.

**Comment by A5TC** [comment]
[crash-2018-03-29_19.26.10-server.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/1862467/crash-2018-03-29_19.26.10-server.txt)
[crash-2018-03-29_19.34.40-server.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/1862468/crash-2018-03-29_19.34.40-server.txt)

**Comment by A5TC** [comment]
there are the crash reports.

**Comment by DarkGuardsman** [comment]
Strange error, its acting like the method is missing for getting the item in the slot for the inventory. The code has the method so I'm unsure the source. I will see if I can replicate it server side, if not then I might need to check if another mod is breaking it.

**Comment by A5TC** [comment]
Umm

**Comment by A5TC** [comment]
At the moment I can't even get on my world without it crashing. =(

**Comment by DarkGuardsman** [comment]
Ya I can't replicate the issue on my end. I think it might be another mod conflicting or doing something odd. If possible could you send me your modpack. As well what items did you have on you at the time? I see botania bauble in the crash.... not sure if that is related. 

While you do that I'm going to make a few changes to the code. My theory is something is ASM stripping away IInventory from the code. This would cause the missing method and the game to crash. As the method is also shared by IItemHandler which is used for inventory support.

**Comment by DarkGuardsman** [comment]
Well, my theory might be completely off. I think the actual issue was an srg mapping problem. Though I was close in that it is an issue between IInventory and IItemHandler. This commit should fix it and a new build will be up soon. https://github.com/BuiltBrokenModding/ICBM-Classic/commit/796bdaa0a56e76e08d51f7e08bcd356eb678dd00

**Comment by DarkGuardsman** [comment]
New version https://minecraft.curseforge.com/projects/icbm-classic/files/2546537
Give it a test and let me know if it fixes the problem

**Comment by A5TC** [comment]
thanks that fix it, Sorry for the late response.
