### ISSUE TITLE
[1.7.10] Failed Missle Detection

### ISSUE THREAD

**Issue by sfxworks** [BuiltBrokenModding/ICBM-Classic#116]
When attempting to use the following layout, the anti missile launch system fails to launch.

![abs-setup 1](https://user-images.githubusercontent.com/5921035/38286761-fb3b3f10-3794-11e8-8752-4dbaac8256eb.png)

**Comment by ghost** [comment]
1.12.2 too.  the radar dosen't emit signal. I used redstone to set it emit, but it never.

**Comment by johonggnJA** [comment]
I have the same issue on 1.7.10 now.

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.
