### ISSUE TITLE
[1.12.2]Incomplete JEI item registration

### ISSUE THREAD

**Issue by ghost** [BuiltBrokenModding/ICBM-Classic#117]
The title is pretty self explanatory http://prntscr.com/j1ackq

**Comment by ghost** [comment]
It turns out this only occurs when JEI is set to NEI

**Comment by DarkGuardsman** [comment]
Will look into this but we have no JEI or NEI support.

**Comment by DarkGuardsman** [comment]
As far as I can tell this is fixed now. Reopen if next update its not fixed.
