### ISSUE TITLE
[1.12.2] Add config rule to disable the dropping of sulfur by Creepers

### ISSUE THREAD

**Issue by Syndesi** [BuiltBrokenModding/ICBM-Classic#119]
Hi,

is it possible to add a rule which decides if Creepers can drop sulfur?

**Comment by DarkGuardsman** [comment]
Sure, might already even be half implemented. Though I can suggest that there are mods to edit loot table drops. The creeper uses a similar loot table system as chests and other containers.

**Comment by Syndesi** [comment]
Ok, didn't know that :D
