### ISSUE TITLE
[1.12] Red matter explosives don't make sounds / are static / too OP

### ISSUE THREAD

**Issue by imanairconditioner** [BuiltBrokenModding/ICBM-Classic#121]
I'm pretty sure this is unintentional. When I detonate a RME, it does not make any siren/wind SFX. They also don't move and interact with other black holes. The 'sucking' effect is also OP and has a sudden snap to max velocity a few dozen blocks away (~80 blocks). EDIT: THe black hole can commonly be seen through blocks, and the glare seems to have been overdone.

**Comment by DarkGuardsman** [comment]
Siren was intentionally removed back in 1.6.4 MC version. It was annoying and gave too much warning to targets. That being said if enough people request the feature I could add it back as an extra config feature.

**Audio**
I'm still working on re-adding all audio effects. The 1.12 update was not smooth and a lot of audio still has to be reimplemented. This is especially the case for the redmatter as it had a few audio effects. This includes a suction sound, crush sound, and block removal sound. 

**Movement**
At the moment there is not a lot of code to reduce the effects of movement. The plan is to work on this to help reduce pulling through walls. However, this is meant to be an endgame explosive that is overpowered. 

As for the movement of pull other blackholes. This should work and might be a bug. I will look into it first chance I get but am in finals week for university. So it will have to wait until next week at the least.

**Graphics**
Graphics will eventually be improved but there are limits.

**Comment by DarkGuardsman** [comment]
As an update on this issue, audio has been fixed. The redmatters will produce audio after being detonated.

**Comment by GHXX** [comment]
Update on this one:
Just need to fix the pull speed and some graphics (see #165 for the graphics)

**Comment by GHXX** [comment]
Just fixed the pullspeed via 2a19265f64c18aed84a1745876706ed829628721. Ill close this issue now as the graphics issue is mentioned in #165
