### ISSUE TITLE
Missiles Explode in Launchers

### ISSUE THREAD

**Issue by jefferyrlc** [BuiltBrokenModding/ICBM-Classic#122]
When trying to launch a missile from a platform, the missile with instead explode inside of the launcher instead of flying off to the designated target. This appears to be specific for each type of missile as the RME missile did function as expected, but the antimatter and nuclear missiles both caused the silo sites to explode instead of launching.

**Comment by DarkGuardsman** [comment]
RME? 

Also what version of the mod,  and what version of Minecraft 1.7 or 1.12?

**Comment by jefferyrlc** [comment]
Red Matter Explosive and 1.12.2
mod ICBM-classic-1.12.2-3.0.0b29

**Comment by jefferyrlc** [comment]
mod ICBM-classic-1.12.2-3.0.0b29

**Comment by DarkGuardsman** [comment]
I was unable to replicate the issue with a launcher in an open area. Do you have a special setup that could be resulting in the problem? Such as launcher being underground or hidden behind some blocks. As well are there any mods you have installed that create air like blocks? In which the block can't be seen but is not an air block.

**Comment by ghost** [comment]
In ICBM for like 1.5 somewhere this used to occur when a missile didn't have to go far at all and the launcher had walls right next to it, so when it tried to turn it hit the wall and blew up inside or right above the launcher

**Comment by DarkGuardsman** [comment]
Fix for that is setting the lock height :) and building a 3x3 silo opening rather than 1x1
