### ISSUE TITLE
[API] Radius for convention missile's explosion event is underestimated

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#125]
As of ICBM-classic-1.7.10-2.16.3b225, the conventional missile reports a radius of 6 while the effect on glowstone is up to 9 m away from the the center of explosion.
This applies to the radius provided in ExplosionEvent.iExplosion.getRadius() .

From a quick check, the reported radius is overestimated on other missiles, which is fine:
- Thermobaric reports a radius of 30, while the effect on glowstone is close to 20 m radius.
- Nuclear reports a radius of 50, while the effect on glowstone is close to 34 m radius.
- Endo/Exothermic reports a radius of 50, while the effect is at least 22 m radius.
- Antigrav reports a radius of 15, which seems fine
- Hypersonic repors a radius of 20, while the effect on glowstone is close to 14 m radius.
- Antimatter reports a radius of 55, while the block effect is close to 52 m radius.

RedMatter reports a radius of 70, but all blocks are checked individually, so it could be greatly reduced?

**Comment by DarkGuardsman** [comment]
Ah thought you were talking about ICBM 2 in discord. Not even sure ICBM-Classic the events are setup correctly. I will take a look at fixing this when I fix issues for Quantumworks.

**Comment by DarkGuardsman** [comment]
https://builtbroken.codecks.io/decks/21-lts-1-12/card/1fe-fix-blast-radius-api
