### ISSUE TITLE
[1.7] Crash after trying to place missile launcher

### ISSUE THREAD

**Issue by Kaihatsujin** [BuiltBrokenModding/ICBM-Classic#127]
Any time I try to place a launcher platform or support frames, Minecraft crashes. I've used a number of different 1.7.10 versions of the mod & voltzengine but they all seem to be doing the same thing. This is the most recent crash report I got: https://pastebin.com/QHNjN0jr

**Comment by DarkGuardsman** [comment]
You might be missing coding lib, it should automatically download. However, we have had issues in the past with it failing to download. 

http://api.dmodoomsirius.me/com/builtbroken/codinglib/CodingLib/0.2.8b52/CodingLib-0.2.8b52.jar

In the future, we plan to do away with this extra download just for this reason.

**Comment by Kaihatsujin** [comment]
That fixed the problem. Thanks!
