### ISSUE TITLE
Anti-ballistic missiles seems broken [1.7.10]

### ISSUE THREAD

**Issue by TheLastSpectre** [BuiltBrokenModding/ICBM-Classic#128]
Anti-ballistic missiles seem to be completely dysfunctional. When hooked up to a radar sending a signal to the monitor with an incoming missile, one of three things happens:
1. The missile appears to fire, and follows the target, but does not explode and leaves behind an invisible missile (or at least the seat entity) that can still be interacted with.
2. The missile does absolutely nothing, and the enemy missile impacts the base.
3. The anti-ballistic missile blows up in the launcher when the radar detects the enemy missile.

Any guidance from any people with knowledge of these occurences would be appreciated, as I'm uncertain of how some blocks work with reference to the original calclavia version, so some of this might be on me. Tested using latest versions of ICBM-Classic, Voltz Engine, Thermal Expansion, Foundation, COFHCore, and Mantle.
![screenshot 49](https://user-images.githubusercontent.com/28612000/40758326-ccb46002-645a-11e8-9660-5c18a1b3171d.png)
Invisible seat above:

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM-Classic/issues/94

**Comment by DarkGuardsman** [comment]
The system is broken in 1.7 and somewhat fixed in the 1.12 version. No clue when I will get chance to work on the old version.
