### ISSUE TITLE
[1.12] EMP Tower Not Disabling Missiles

### ISSUE THREAD

**Issue by spruill7716** [BuiltBrokenModding/ICBM-Classic#133]
I read the wiki and watched countless tutorials on how to set up an EMP tower but I'm fairly certain that the EMP tower is not doing its designated function. The radar station recognizes the missile but either doesn't emit a signal or the EMP tower doesn't catch it. Attached some screenshots just to see if it's the way I have it setup.   

![2018-06-22_19 32 33](https://user-images.githubusercontent.com/8177504/41803987-3bb75fca-7655-11e8-9227-26b618c82e5e.png)
![2018-06-22_19 32 47](https://user-images.githubusercontent.com/8177504/41803988-3bc59284-7655-11e8-8f50-3273863817e4.png)
![2018-06-22_19 32 56](https://user-images.githubusercontent.com/8177504/41803989-3bd4068e-7655-11e8-9ade-c7bdfee41b2d.png)
![2018-06-22_19 33 02](https://user-images.githubusercontent.com/8177504/41803990-3be33e74-7655-11e8-94c2-f4ed0df47c06.png)
![2018-06-22_19 34 15](https://user-images.githubusercontent.com/8177504/41803991-3c43b77c-7655-11e8-8c8c-ca1beecd8ae4.png)

**Comment by DarkGuardsman** [comment]
Was fix a while ago, can't remember if you're the same person that reported it in discord. 

The issue was missile not implementing EMP logic fully
