### ISSUE TITLE
[1.12.2] Missiles not going through unloaded chunks

### ISSUE THREAD

**Issue by KohlsJW3656** [BuiltBrokenModding/ICBM-Classic#134]
I've had the issue where I launch a missile through unloaded chunks and the missile never reaches its target. I assume the missiles can't load chunks themselves, which would explain why they stay suspended until the chunk is loaded.

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM-Classic/issues/70#issuecomment-401230658
