### ISSUE TITLE
[1.12.2] Client side crash with no logs

### ISSUE THREAD

**Issue by sfxworks** [BuiltBrokenModding/ICBM-Classic#136]
Minecraft version: 1.12.2
ICBM-Classic version: 1.12.2-3.0.0b29 build 29 for 1.12.2
Forge version: 14.23.4.2705
Singleplayer or multiplayer: Single Player
Steps to reproduce: On launch / clientside start

While updating Lapito's Galacticraft tonight, I was going through curse updating mods. I found that the latest build for ICBM-Classic crashed the pack. Unfortunately, it produced no logs.

**Comment by DarkGuardsman** [comment]
Can't reproduce, installed latest forge, ICBM-classic, and GC.

**Comment by sfxworks** [comment]
Might of been the typo I put in forge's version.json. Sorry I was tired.

**Comment by DarkGuardsman** [comment]
No problem, stuff happens
