### ISSUE TITLE
Cannot search for individual missiles or explosives in creative GUI

### ISSUE THREAD

**Issue by kmecpp** [BuiltBrokenModding/ICBM-Classic#137]
When searching "explosive" or "missile" in the creative GUI, none of the individual bombs actually come up.

![image](https://user-images.githubusercontent.com/6520738/42128075-7700da58-7c71-11e8-8bc5-be8c01f2015b.png)

**Comment by DarkGuardsman** [comment]
I think this might be a vanilla bug.

**Comment by DarkGuardsman** [comment]
Going to say this is a vanilla bug unless someone knows otherwise.
