### ISSUE TITLE
Suggestion: Concrete stairs and other fornitures

### ISSUE THREAD

**Issue by PzCampus** [BuiltBrokenModding/ICBM-Classic#140]
Just thinking that would be nice to have blast-resistant stairs, door and similar furniture made out of concrete

**Comment by ZinRicky** [comment]
I agree with @PzCampus: it's quite complicated if nothing makes one hide from some types of bomb

**Comment by DarkGuardsman** [comment]
We have a mod that is planned for development to handle this type of block https://github.com/BuiltBrokenModding/MilitaryBaseDecor

No clue when the mod will be updated to 1.12 or the content will be added. The original developer working on MBD decided to work on other projects. Which is understandable considering the lack of design or focus on content. The hope is to solve this in the next 3-4 months and get a new developer to focus on the mod.
