### ISSUE TITLE
EMP crashes server and game

### ISSUE THREAD

**Issue by Reliphyte** [BuiltBrokenModding/ICBM-Classic#141]
https://pastebin.com/nhPKw3A1
I blew up EMP explosives and not everytime I try to join my server it crashes.

**Comment by DarkGuardsman** [comment]
Looks like your using a very old build based on the build number.

Your file: ICBM-classic-1.7.10-2.16.2b20171229182056.jar
Latest: ICBM-classic-1.7.10-2.16.4b238.jar

Also, your build looks questionable, make sure you're only downloading builds from curse site.
https://minecraft.curseforge.com/projects/icbm-classic
