### ISSUE TITLE
[1.12.2] Crafting Recipe for Iron Plate same as Iron Trapdoor

### ISSUE THREAD

**Issue by KohlsJW3656** [BuiltBrokenModding/ICBM-Classic#142]
The iron plate has the exact same recipe as the iron trapdoor, making the plate uncraftable.

**Comment by DarkGuardsman** [comment]
Decided to remove the item and recipe. It was only used in one recipe that could easily be replaced with a normal iron ingot. 

Any plates that still exist can be melted down into iron ingots or used in ore-dictionary recipes. 
![screenshot 2018-07-11 05 30 10](https://user-images.githubusercontent.com/1477330/42563285-e1a539dc-84cb-11e8-87bd-2b6ac34027bf.png)
