### ISSUE TITLE
[1.12.2-3.1.0b42] Players cannot ride missiles

### ISSUE THREAD

**Issue by inflz** [BuiltBrokenModding/ICBM-Classic#143]
When a player gets onto a missile and attempts to launch, they are thrown off and the missile continues on its path without the player. Additionally, the player's view is largely blocked making it hard to launch the missile.

**Comment by DarkGuardsman** [comment]
Honestly, have not tested riding since I updated the mod to 1.12. As for the view being block, not much I can do about that. Minecraft gives you limited handling without a ton of extra code.

**Comment by DarkGuardsman** [comment]
Fixed though I need to make changes for the new simulation system
![screenshot 2018-08-04 21 53 45](https://user-images.githubusercontent.com/1477330/43681942-fcb3e520-9830-11e8-8145-f96588ab892a.png)
