### ISSUE TITLE
Other players can't look at multiblock in multiplayer with HWYLA 

### ISSUE THREAD

**Issue by zaccnz** [BuiltBrokenModding/ICBM-Classic#144]
When I place a launcher, when another player looks directly at it (close enough to get the tooltip) their game will crash.  This is on the latest version from the curse launcher, and will only crash people who didn't place it.

Game crashes with the error '`java.lang.NullPointerException: icbmclassic:multiblock from mod ICBM-Classic returned a null ItemStack in getPickBlock(...). Please report this to them.` at `mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:64)`.

Full crash report here: [Pastebin](https://pastebin.com/f9d2QBi2)

I tried fixing the issue by editing [/src/main/jaja/icbm/classic/content/multiblock/BlockMultiblock.java](https://github.com/BuiltBrokenModding/ICBM-Classic/blob/1.12/src/main/java/icbm/classic/content/multiblock/BlockMultiblock.java#L77-L98)
```java
@Override
public ItemStack getPickBlock(IBlockState state, RayTraceResult target, World world, BlockPos pos, EntityPlayer player)
{
    final IMultiTile multiblock = getTile(world, pos);
    if (multiblock != null && multiblock.getHost() instanceof TileEntity)
    {
        //Get tile
        TileEntity tileEntity = ((TileEntity) multiblock.getHost());

        //Get state
        IBlockState blockState = tileEntity.getWorld().getBlockState(tileEntity.getPos());
        Block block = blockState.getBlock();

        //Get actual block state
        blockState = block.getActualState(blockState, world, pos);

        //Get stack from state
        ItemStack stack = block.getPickBlock(blockState, target, world, tileEntity.getPos(), player);
    
        //Prevent null stack on servers
        if (stack == null)
        {
            stack = ItemStack.EMPTY;
        }
        return stack;
    }
    return ItemStack.EMPTY;
}
```
as to prevent the stack from ever returning null, but I couldn't test this.  Kept getting an error when I ran build-local.bat (`Could not GET 'http://box1.dmodoomsirius.me:8081/artifactory/libs-release/mezz/jei/jei_1.12.2/4.8.5.147/jei_1.12.2-4.8.5.147.pom'. Received status code 500 from server: Internal Server Error`).

**Comment by DarkGuardsman** [comment]
Already fixed, use the latest alpha https://github.com/BuiltBrokenModding/ICBM-Classic/issues/132
