### ISSUE TITLE
1.7.10 | Crafting concrete in Project: Red Project Bench causes bucket to dissapear

### ISSUE THREAD

**Issue by NullExceptionTSB** [BuiltBrokenModding/ICBM-Classic#145]
If I craft concrete in the Project Bench from the mod Project: Red, the bucket is not returned. It only happens in the Project Bench, the regular crafting table works just fine. This is especialy annoying, considering you have to refill buckets, and items don't fall out of the project bench, making the process faster.

**Comment by DarkGuardsman** [comment]
If it only happens in the project red workbench then it is likely a bug on their side. As we do nothing extra to get that recipe to work. Bucket staying in the crafting grid is a vanilla feature. 

Recipe is a standard forge shaped recipe with no extra logic: 
https://github.com/BuiltBrokenModding/ICBM-Classic/blob/development/src/main/java/icbm/classic/content/blocks/BlockConcrete.java#L87
