### ISSUE TITLE
mod started crashing game startup saying The game crashed whilst initializing game    Error: java.lang.NullPointerException: Initializing game

### ISSUE THREAD

**Issue by 1341341341** [BuiltBrokenModding/ICBM-Classic#147]
it also said it looks like you are using an unsupported modified version of the game

**Comment by 1341341341** [comment]
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game
crashed on startup

**Comment by DarkGuardsman** [comment]
Full log or nothing can be done
