### ISSUE TITLE
[1.12] No way to charge batteries

### ISSUE THREAD

**Issue by LlamaLegate** [BuiltBrokenModding/ICBM-Classic#149]
As far as I can tell from everything I've read, there is no way in 1.12 (even though it's standalone) to charge the batteries so that the launchers won't say "insufficient electricity."

**Comment by GHXX** [comment]
As of now there is no way of generating electricity with just ICBM-classic. (This is a planned feature)
But there is a config setting for turning off the power requirement for the whole mod.

**Comment by DarkGuardsman** [comment]
Any mod that supports Forge Energy (FE) or IC2 energy (EU) will work with the launchers. Make sure to download the latest alpha as well.
