### ISSUE TITLE
Radioactive waste

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#15]
As of 1.7.10-2.15.1b33, Nuclear explosion is missing the radioactive dirt, probably because that block was in Atomic Science.
=> Maybe add the missing block to VoltzEngine?

**Comment by DarkGuardsman** [comment]
Yes, the plan is to implement the blocks into VE but not in the same way as they were in AS. Though it should be able to use the AS blocks still if you updated them in your version.

**Comment by DarkGuardsman** [comment]
I re-added the code to detect for radio-active blocks. Once implement this should fix itself.
