### ISSUE TITLE
[1.12] Add simulated missiles to radar

### ISSUE THREAD

**Issue by GHXX** [BuiltBrokenModding/ICBM-Classic#154]
Yellow because they are very high up (outside the atmosphere aka simulated) and thus cannot be shot down.

Radar should not output a redstone signal, but that may be a thing to change later.

**Comment by DarkGuardsman** [comment]
tbh when we write the backend I might do an overhaul of the front end as well. Would love to use missile icons rather than dots. So we can show the heading of the missile and maybe its path. Though both could be made as optional settings if players want a simple UI.
