### ISSUE TITLE
[1.12] Nuclear explosives have no recipe

### ISSUE THREAD

**Issue by KohlsJW3656** [BuiltBrokenModding/ICBM-Classic#156]
You cannot craft nuclear explosives, or anything that requires them.

**Comment by xenon-difluoride** [comment]
The recipe exists if you have a mod that adds uranium, it's 8 uranium around a thermobaric. Probably better if there was a way to get it without IC2/techreborn though

**Comment by DarkGuardsman** [comment]
It's very easy to install a mod to change the recipe. Right now I do not want to make it super easy to craft. As well am waiting to update atomic science and have that as a requirement for nukes.

**Comment by KohlsJW3656** [comment]
Good to know, thanks.

**Comment by KohlsJW3656** [comment]
I have added IC2 to craft the nuclear explosives, but the recipe calls for refined uranium, which isn't in the mod anymore. You could switch those out with uranium 235 or add in other resources that are difficult to come by with the mod.

**Comment by DarkGuardsman** [comment]
Hmm will do, by any chance do you know the ore-dictionary value and I can change it to that

**Comment by KohlsJW3656** [comment]
Would it be <ic2:nuclear:1> // This is for uranium 235

**Comment by KohlsJW3656** [comment]
Looking at the old recipes, it looks like refined uranium turned into uranium 238, which is <ic2:nuclear:2> 
However, uranium 235 would be more realistic and harder to get for the explosive.

**Comment by ghost** [comment]
Is there an eta on when this will be fixed? Thanks =)

**Comment by ghost** [comment]
Holy heck this ticket has been open since 2018, I really hope it gets fixed as it makes the whole mod useless when there are recipes that you just cannot craft without manual item substitution by mods

**Comment by DarkGuardsman** [comment]
> Is there an eta on when this will be fixed? Thanks =)

Between now and the end of time. Hard to say as I'm beyond busy with life and work. 

> Holy heck this ticket has been open since 2018,

Its been a rather low priority as the nuke acts like an over sized TNT without radiation implementation. 

> I really hope it gets fixed as it makes the whole mod useless when there are recipes that you just cannot craft without manual item substitution by mods

It is rather easy to implement a recipe replacement using other mods. Given this is a PVP mod it is common for people to build modpacks and adjust recipes anyways. Thus no priority has been given to fixing this when time is better spent rebuilding things like the redmatter or finishing radiation.

That said the mod is open sources and anyone can submit a fix. The recipes are JSON so can be edited without much knowledge.

**Comment by ghost** [comment]
Oh awesome, so if I edited it and submitted it then that would work too? I get the busy thing sorry, thanks for working on the mod full stop, its been amazing so far, just really wanted to nuke japan and hit a roadblock haha. I'll have a look at the recipe stuff 👍 

Thanks again

**Comment by GHXX** [comment]
Ontop of that, if i recall correctly, the latest alpha already supports ore dict, so any ingotUranium i believe will work.
This includes IC2 Uranium 235 i believe it is, aswell as BigReactors/ExtremeReactors Yellorium
