### ISSUE TITLE
[1.12.2] Missiles stuck mid-air in Sponge server

### ISSUE THREAD

**Issue by Rainmaker33** [BuiltBrokenModding/ICBM-Classic#158]
Sponge tries to capture all asynchronous entities and sync them to ticks. This creates an error print on the server when launching ICBM missiles and they end up getting stuck mid-air until you go closer to them.

I don't know if this is an issue with the mod or with Sponge and the way it handles entities, but it would be nice to see the mod work with Sponge.

**Comment by DarkGuardsman** [comment]
Likely sponge but I'll see if I can fix it. We have already had to rework how several of the explosives function for the same reason. As it seems Sponge changes how ticks work and does not match vanilla tick mechanics.

**Comment by joanros97** [comment]
Ok, so I opened a therad (#307) and I've been redirected here. This bug is anoying me a lot, and I would like to know if there is any way to solve it. Changing something on the sponge config? Maybe updating sponge? Or it would require to change code to fix this unmatching of vanilla-sponge tick?

Thanks

**Comment by GHXX** [comment]
Just for clarification, i did not redirect you to here, instead i just wrote down that these two issues may be related, which helps when fixing it.

**Comment by joanros97** [comment]
Oh ok. Anyway, I dind't find any way to solve the problem, do you know if this problem has any solution?
I really love what this mod offers and I would like to have it working at 100% efficiency

**Comment by clienthax** [comment]
See https://github.com/SpongePowered/SpongeForge/issues/3136 for fix.
