### ISSUE TITLE
ICBM Homing missile issue 

### ISSUE THREAD

**Issue by William191111** [BuiltBrokenModding/ICBM-Classic#159]
You can't use the tracker on the homing it just makes you ride the homing missile. To were you use to be able to use it on the homing missile to get the cords of the person you tracked

**Comment by DarkGuardsman** [comment]
It has not been re-implemented for the 1.12 version. Not even sure it was ever implemented for the 1.7 version either.

**Comment by William191111** [comment]
This issue was on the 1.7.10 version it kinda just makes the tracker pointless not having it in

**Comment by GHXX** [comment]
Homing missiles and tracker will be removed, so this ticket is obsolete
