### ISSUE TITLE
Nuclear explosion fuse too short?

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#16]
As observed in 1.7.10-2.15.1b33, when comparing to 1.5.2 version, both in single player: some fuses are shorter than expected, notably with nuclear explosion. Is it a bug or just the original was so CPU intensive that it felt longer?

**Comment by DarkGuardsman** [comment]
Intentional, I changed those myself in 1.6.4 because it felt odd to have long timers on explosives that should be instant.
