### ISSUE TITLE
Crashing when loading into MP (1.7.10)

### ISSUE THREAD

**Issue by Breadabix** [BuiltBrokenModding/ICBM-Classic#166]
When trying to log onto a MP server using latest version of ICBM-C, VoltzEngine, CodingLib, Optifine,  liteloader and voxelmap on 1.7.10, the client crashes, but the server does not. Without ICBM-C it doesnt crash, as is the case when loaded without optifine. This also is the case when loading up without voxelmap, liteloader by itself is fine. Putting the mix of ICBM-C, optifine and voxelmap together though crashes the game. 

Full crash report: https://pastebin.com/i5NvJWkg

I will upload anything else that may be needed when requested as I dont know what might be needed other than the crash report.

**Comment by DarkGuardsman** [comment]
I think we cleared this up in discord, if not re-open
