### ISSUE TITLE
[1.12] Missile Disappears when Launched

### ISSUE THREAD

**Issue by KohlsJW3656** [BuiltBrokenModding/ICBM-Classic#168]
I've only tested the nuclear missile, but after it's launched and in the air, the missile disappears.

**Comment by DarkGuardsman** [comment]
The newer version is set to unload from the world and travel unloaded when moving large distances. This is done on a set Y level and can sometimes happen at short distances. Best way to check if this is the case is to see if it hit the target location.

**Comment by KohlsJW3656** [comment]
Good to know, it wasn't hitting at short distances and that's what I was launching them to.

**Comment by Redd56** [comment]
oh okay then

**Comment by CplPibald** [comment]
I'm seeing this same problem on MP server (Forge 2759) with the T3 launcher and any type of missile, targeting something 80-100 blocks away (still visible, so chunk loaded).  I can watch the missile fly upward for about 3 seconds, and then disappear around y=250.  No explosion, and no evidence that it hit the target.

If the target is close enough that it's a short flight (30 blocks or so), then the missile impacts.

**Comment by DarkGuardsman** [comment]
@GHXX Sounds like something is wrong with your unload alg. Check into it and see if you can write some automated tests to confirm its working.

**Comment by GHXX** [comment]
The missile is removed when it reaches a certain altitude or the Y-velocity becomes negative. There should be two log-lines in your log that look like this: "Launching missile from x y z to x y z", although the 'from'-part may be missing.
The first log line indicates the actual launch and the second indicates that the missile was re-created when simulating finished. The missile travels around 10m/s during simulation (across x and z coords)

Could you check if those lines are in the log file? @CplPibald

**Comment by CplPibald** [comment]
Yes, both log lines are there.

    [10:49:55] [Server thread/INFO] [icbmclassic]: Launching Incendiary Missile (4029743) from 586, 133, 1081 to 666, 91, 1111
    [10:50:03] [Server thread/INFO] [icbmclassic]: MissileTracker[ 0]: Simulating missile
    [10:50:07] [Server thread/INFO] [icbmclassic]: Launching Incendiary Missile (4030864) from 666, 250, 1111 to 666, 91, 1111

In-game I don't see any evidence of the re-created missile at the target site.  No missile, no smoke trail, no explosion.

EDIT: I tried several locations in a SP world using just ICBM-3.3.0b55 (and JEI).  Beyond a certain distance from launcher to target (200-ish blocks?) the missile respawns and explodes as expected.  Closer than about 40 blocks the missile impacts without simulating.  Between these distances, the missile vanishes mid-flight, but fails to reappear.

**Comment by DarkGuardsman** [comment]
hmm so its not the unloading system. Wonder if we are running into an odd SP loading issue. I recall there use to be a lot of issues with ticking entities beyond a set range from the player.

@GHXX See if you can add some debug to the missile that can be enabled to check for ticks alive and actions.

**Comment by GHXX** [comment]
I'll add some debug code on Friday. Im pretty busy right now, sorry!

**Comment by GHXX** [comment]
The missile was recreated with an acceleration of -320 blocks per tick, so after one motion update the speed was bigger than the world height, so it was going way too fast.

Fixed in 8b74bc6.
Thanks for the report.

**Comment by DarkGuardsman** [comment]
@GHXX Open a new issue ticket to add a raytrace to prevent that from happening again. The ray trace would path down and detect the ground.
