### ISSUE TITLE
EMP explosion affecting other mods

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#17]
As observed with 1.7.10-2.15.1b33, EMP explosion doesn't affect IC2 batteries in inventory, nor Modular power suit batteries, etc.
ThermalExpansion, ExtraUtilities2 and WarpDrive weren't tested.

**Comment by DarkGuardsman** [comment]
Going to move over the EMP code to VE later and solve this. As its not a problem in ICBM but the fact VE has little to no EU energy support.
