### ISSUE TITLE
Cruise Launcher GUI Crash

### ISSUE THREAD

**Issue by ConnorMiner** [BuiltBrokenModding/ICBM-Classic#172]
When opening the Cruise Launcher's GUI, the items in the player's and the block's inventories are completely invisible. When Shift-Clicking in an item, null is shift-clicked as well/instead, causing the game to crash.
Example: https://drive.google.com/file/d/1bHYrX8elMqpGPI3U40UPSJ0-djANNG8t/view?usp=sharing
Crash Report: https://drive.google.com/file/d/1MiB4jkwVu1pG4__TY6cbDVqs1H7Xy_6L/view?usp=sharing

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM-Classic/issues/182

**Comment by GHXX** [comment]
Cant confirm the invisible-issue, but the second one is fixed.
