### ISSUE TITLE
[1.12.2] b56 EMP towers don't disable rocket launcher launched missiles

### ISSUE THREAD

**Issue by PlantDaddy** [BuiltBrokenModding/ICBM-Classic#181]
I'm not sure if this is intended or not, but EMP towers don't disable rockets launched from rocket launchers.

**Comment by DarkGuardsman** [comment]
@GHXX Check if the hand held missiles register with the radar system.

**Comment by GHXX** [comment]
Fixed 😛

**Comment by DarkGuardsman** [comment]
Ah it was the impact check, nice GJ

**Comment by DarkGuardsman** [comment]
Oh random thought @GHXX test the cruise launcher. It might have the same issue.
