### ISSUE TITLE
[1.12.2]Add a missile to  Cruise Launcher causes a crash

### ISSUE THREAD

**Issue by 1a2s3d4f1** [BuiltBrokenModding/ICBM-Classic#182]
Mod version:1.12.2-3.3.0b57
forge version:1.12.2-14.23.5.2768
crash-reports:https://paste.ubuntu.com/p/Zhnx4pncqQ/
Pressing Shift to add a missile to the Cruise Launcher game will crash(Sorry I am poor in English, so I use Google translation)

**Comment by Nbgreen** [comment]
having the same issue https://paste.dimdev.org/mupalipode.mccrash

**Comment by DarkGuardsman** [comment]
@GHXX Did you by any chance look into this and fix it already?

**Comment by GHXX** [comment]
Fixed, thanks for the report.
