### ISSUE TITLE
Chinese localization is broken

### ISSUE THREAD

**Issue by Snownee** [BuiltBrokenModding/ICBM-Classic#185]
![image](https://user-images.githubusercontent.com/16059084/50737412-e8b6b280-1203-11e9-9248-f0e9f169e23a.png)

**Comment by DarkGuardsman** [comment]
Ya I think whoever did the translation file messed up the encoding. Its been broken like this for ages, I think I'm going to just rename the file until its fixed.

**Comment by DarkGuardsman** [comment]
Found out we had an updated lang file for a while but was in correctly named. I switched out the new one in place of the old one. It should in theory work but will be a while before its released. Currently in the middle of rewriting the explosive registry to allow addons to be created.

**Comment by Snownee** [comment]
I wonder why you fixed the Russian translation only? Other translations are broken too

**Comment by DarkGuardsman** [comment]
Ah I see, thought the Russian one was the only broken one. I see the Chinese one is also messed up. Nothing I can really do about it unless someone sends me a fixed file. We had one on hand for the Russian translations. The rest look fine but I have not tested them in game. 

https://github.com/BuiltBrokenModding/ICBM-Classic/tree/blast-rewrite/src/main/resources/assets/icbmclassic/lang

**Comment by Snownee** [comment]
One way I can think of is converting them to 1.13 json format and converting them back

**Comment by DarkGuardsman** [comment]
Does that work? Also I think the chineese localization is highly outdated as its missing most of the key for new stuff.

**Comment by Snownee** [comment]
> Does that work?

This is an example: https://codebeautify.org/jsonviewer/cb4ccafd

> Also I think the chineese localization is highly outdated as its missing most of the key for new stuff.

I think we should get it work then talk about making it up to date right?

**Comment by Snownee** [comment]
BTW I think es_ES.lang and de_DE.lang are broken too

**Comment by DarkGuardsman** [comment]
They may be outdated as well, I offered up a reward on a few discords for people to update them.

**Comment by 1a2s3d4f1** [comment]
![item1](https://user-images.githubusercontent.com/40121560/51451770-db580700-1d71-11e9-8287-ae8c16c10d6e.png)
![item2](https://user-images.githubusercontent.com/40121560/51451760-c7aca080-1d71-11e9-9001-2e692799eedc.png)
mod:ICBM-classic-1.12.2-3.3.0b62
forge:forge-1.12.2-14.23.5.2807 maybe forge is new
Maybe Rocket Launcher doesn't support Chinese
https://paste.ubuntu.com/p/BNd8S4G4bC/

**Comment by GHXX** [comment]
possible duplicate of #227

**Comment by Snownee** [comment]
ping

**Comment by GHXX** [comment]
@Snownee if you want you could submit a translation
