### ISSUE TITLE
Rocket launcher can launch nuclear missiles

### ISSUE THREAD

**Issue by Blayyke** [BuiltBrokenModding/ICBM-Classic#188]
Title says it all. The rocket launcher says it can launch up to tier 2 but it can launch nuclear rockets (tier 3) and probably more. Haven't tested other types.

**Comment by DarkGuardsman** [comment]
If you tested in creative mode, it overrides requirements to allow testing easier for admins.

**Comment by Blayyke** [comment]
This happened in survival mode on a faction server, faction member right clicked an ME interface and nuked half the base.

**Comment by DarkGuardsman** [comment]
That is amazing that he clicked with an RPG thinking nothing would happen.... Which version of ICBM and Minecraft are you using?

@GHXX if you can check into this, likely a simple if check issue.

**Comment by GHXX** [comment]
Fixed. Turns out it was a very simple mistake and also affected all other tier 3 missiles.

**Comment by Blayyke** [comment]
He's not the brightest aha. Sweet, thanks for the quick fix
