### ISSUE TITLE
Antigravitational explosion has no effect

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#19]
As of 1.7.10-2.15.1b33, in single player, Antigravitational explosion doesn't pick up blocks and just create 'stone' entity blocks.
Also, it doesn't move the player nor cows up in the sky

**Comment by DarkGuardsman** [comment]
Entity movement does seem to be working on my end, but the blocks seems to be a bit buggy. Mainly with it finding 65K entries to pickup but only breaking like 30 blocks.

**Comment by DarkGuardsman** [comment]
Its fixed enough that I can close this, though I will come back and improve the blast code here later. Its really inefficient compared to the rewrite's code.
