### ISSUE TITLE
ICBM explosives don't cause world updates in rejuvinated chunks

### ISSUE THREAD

**Issue by UV-Husky** [BuiltBrokenModding/ICBM-Classic#191]
ICBM explosives have some issues when exploding in chunks which have been rejuvenated.

They leave ghost blocks behind (look normal, can walk on), but when you try to place something it just replaces what is on the ground

NOTE: Vanilla TNT explodes correctly.

Steps to reproduce:

1. Detonate a explosive

2. Rejuvenate the area with a rejuvenation missile.

3. Try exploding another ICBM explosive on said area.

4. No observable change.

5. Try to place something where the latter explosive was (or right click with an empty hand).

6. Blocks on the ground get replaced with what you are placing. 

Version: 1.12.2-3.3.0b63
Forge: 14.23.5.2808
(Volts M12: 1.2.5)

**Comment by DarkGuardsman** [comment]
Known issue with rejuvenation, its a desync issue with the client and server. Vanilla TNT looks like it works due to runing on server and client at the same time. While all ICBM explosives run server-side only.

**Comment by DarkGuardsman** [comment]
@GHXX you want to take another shot at fixing this. I know you already gave it several good efforts but see if you can get some help in the MMD discord.

**Comment by GHXX** [comment]
Not sure how to fix it tbh

**Comment by DarkGuardsman** [comment]
ya that is why I suggested get help in MDD discord. I'm busy with the rewrite so can't work on it right now.

https://discord.mcmoddev.com/

**Comment by DarkGuardsman** [comment]
https://trello.com/c/q2lzQ2EQ/60-fix-icbm-classic-regen-missile-10

**Comment by Shadows-of-Fire** [comment]
This issue is very complex.  The only proper way i've figured out how to do it is to mark the chunk for regeneration from an ExtendedBlockState[] after no more players are watching the chunk.  Restoring it at any other time causes the desyncs to appear permanently until server restart.

I've tried sending vanilla chunk packets as well, they don't appear to matter.

**Comment by DarkGuardsman** [comment]
Regen blast is no longer being supported and is removed in the up coming release.
