### ISSUE TITLE
[1.12] Detonating Antimatter explosives near NVL Force Fields field causes server crash

### ISSUE THREAD

**Issue by DaComputerNerd717** [BuiltBrokenModding/ICBM-Classic#192]
When I detonate an Antimatter explosive from this mod (version 1.12.2-3.0.0b29) next to a forcefield from NVL Force Fields (version 1.12.2.2491.1.0), the server crashes. This only happens if I use the TNT-style explosive; the missiles do not cause this issue. Lower-tier explosives appear to not cause any issues, likely because lower tier explosives can't destroy obsidian.

Here's the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.7.4.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  Techguns Core (techguns-1.12.2-2.0.1.1.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 1/26/19 11:07 AM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=onlinestate, clazz=class hu.nvl.nvlforcefields.common.dataclasses.NVLEnumOnlineStates, values=[online, offline]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:215)
	at hu.nvl.nvlforcefields.entities.NVLEntityFieldColumn.setMeta(NVLEntityFieldColumn.java:372)
	at hu.nvl.nvlforcefields.entities.NVLEntityFieldColumn.turnOff(NVLEntityFieldColumn.java:267)
	at hu.nvl.nvlforcefields.entities.NVLEntityFieldColumn.destroyEndpoint(NVLEntityFieldColumn.java:64)
	at hu.nvl.nvlforcefields.blocks.NVLBlockFieldColumn.func_180663_b(NVLBlockFieldColumn.java:37)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:567)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.world.World.func_175698_g(World.java:398)
	at icbm.classic.content.explosive.blast.BlastAntimatter.doExplode(BlastAntimatter.java:61)
	at icbm.classic.content.explosive.blast.Blast.explode(Blast.java:195)
	at icbm.classic.content.explosive.handlers.ExAntimatter.doCreateExplosion(ExAntimatter.java:37)
	at icbm.classic.content.explosive.Explosive.createExplosion(Explosive.java:181)
	at icbm.classic.content.entity.EntityExplosive.explode(EntityExplosive.java:119)
	at icbm.classic.content.entity.EntityExplosive.func_70071_h_(EntityExplosive.java:104)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:215)
	at hu.nvl.nvlforcefields.entities.NVLEntityFieldColumn.setMeta(NVLEntityFieldColumn.java:372)
	at hu.nvl.nvlforcefields.entities.NVLEntityFieldColumn.turnOff(NVLEntityFieldColumn.java:267)
	at hu.nvl.nvlforcefields.entities.NVLEntityFieldColumn.destroyEndpoint(NVLEntityFieldColumn.java:64)
	at hu.nvl.nvlforcefields.blocks.NVLBlockFieldColumn.func_180663_b(NVLBlockFieldColumn.java:37)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:567)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.world.World.func_175698_g(World.java:398)
	at icbm.classic.content.explosive.blast.BlastAntimatter.doExplode(BlastAntimatter.java:61)
	at icbm.classic.content.explosive.blast.Blast.explode(Blast.java:195)
	at icbm.classic.content.explosive.handlers.ExAntimatter.doCreateExplosion(ExAntimatter.java:37)
	at icbm.classic.content.explosive.Explosive.createExplosion(Explosive.java:181)
	at icbm.classic.content.entity.EntityExplosive.explode(EntityExplosive.java:119)
	at icbm.classic.content.entity.EntityExplosive.func_70071_h_(EntityExplosive.java:104)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: icbmclassic:block.explosive (icbm.classic.content.entity.EntityExplosive)
	Entity ID: 26026
	Entity Name: Explosives
	Entity's Exact location: -258.44, 71.00, -41.88
	Entity's Block location: World: (-259,71,-42), Chunk: (at 13,4,6 in -17,-3; contains blocks -272,0,-48 to -257,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.10, -0.79, -0.60
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Test World 3
	All players: 1 total; [HookedEntityPlayerMP['DaComputerNerd'/1418, l='Test World 3', x=-260.30, y=79.87, z=-30.64]]
	Chunk stats: ServerChunkCache: 833 Drop: 0
	Level seed: -1782295177408859905
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-236,64,256), Chunk: (at 4,4,0 in -15,16; contains blocks -240,0,256 to -225,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 8722 game time, 8722 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 83080 (now: false), thunder time: 26113 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 599670816 bytes (571 MB) / 2213253120 bytes (2110 MB) up to 8375238656 bytes (7987 MB)
	JVM Flags: 16 total; -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version         | Source                                          | Signature                                |
	|:--------- |:------------------------ |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2          | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                      | 9.42            | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99       | forge-1.12.2-14.23.5.2768-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.5.2768    | forge-1.12.2-14.23.5.2768-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | obfuscate                | 0.2.6           | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | techguns_core            | 1.12.2-1.0      | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | appliedenergistics2      | rv6-stable-6    | appliedenergistics2-rv6-stable-6.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJAAAA | betterbuilderswands      | 0.12.0          | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar | None                                     |
	| UCHIJAAAA | bibliotheca              | 1.3.3-1.12.2    | bibliotheca-1.3.3-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | cll                      | 1.12.2-3.5.14   | CLL-1.12.2-3.5.14.jar                           | None                                     |
	| UCHIJAAAA | codechickenlib           | 3.2.2.353       | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | cyclopscore              | 1.0.1           | CyclopsCore-1.12.2-1.0.1.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | commoncapabilities       | 2.0.0           | CommonCapabilities-1.12.2-2.0.0.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | compactstorage           | 3.1             | CompactStorage-3.1-12.jar                       | None                                     |
	| UCHIJAAAA | crafttweaker             | 4.1.9           | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
	| UCHIJAAAA | ctgui                    | 1.0.0           | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
	| UCHIJAAAA | jei                      | 4.12.0.215      | jei_1.12.2-4.12.0.215.jar                       | None                                     |
	| UCHIJAAAA | crafttweakerjei          | 2.0.2           | CraftTweaker2-1.12-4.1.9.jar                    | None                                     |
	| UCHIJAAAA | enderutilities           | 0.7.11          | enderutilities-1.12.2-0.7.11.jar                | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCHIJAAAA | redstoneflux             | 2.0.2           | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | meem                     | 1.1.7           | ExtremeEnergy-1.1.7.jar                         | None                                     |
	| UCHIJAAAA | forgelin                 | 1.7.4           | Forgelin-1.7.4.jar                              | None                                     |
	| UCHIJAAAA | forgemultipartcbe        | 2.6.1.81        | ForgeMultipart-1.12.2-2.6.1.81-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe            | 2.6.1.81        | ForgeMultipart-1.12.2-2.6.1.81-universal.jar    | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe    | 2.6.1.81        | ForgeMultipart-1.12.2-2.6.1.81-universal.jar    | None                                     |
	| UCHIJAAAA | ftblib                   | 5.2.0.39        | FTBLib-5.2.0.39.jar                             | None                                     |
	| UCHIJAAAA | journeymap               | 1.12.2-5.5.2    | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | ftbutilities             | 5.2.0.40        | FTBUtilities-5.2.0.40.jar                       | None                                     |
	| UCHIJAAAA | funkylocomotion          | 1.0             | funky-locomotion-1.12.2-1.1.2.jar               | None                                     |
	| UCHIJAAAA | cgm                      | 0.9.2           | guns-0.9.2-1.12.2.jar                           | None                                     |
	| UCHIJAAAA | hopperducts              | 1.5             | hopperducts-mc1.12-1.5.jar                      | None                                     |
	| UCHIJAAAA | icbmclassic              | 1.12.2-3.0.0.29 | ICBM-classic-1.12.2-3.0.0b29.jar                | None                                     |
	| UCHIJAAAA | integrateddynamics       | 1.0.1           | IntegratedDynamics-1.12.2-1.0.1.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | integrateddynamicscompat | 1.0.0           | IntegratedDynamics-1.12.2-1.0.1.jar             | None                                     |
	| UCHIJAAAA | itank                    | 1.2.0-1.12.2    | ITank-1.2.0-1.12.2.jar                          | None                                     |
	| UCHIJAAAA | justenoughbuttons        | 1.12-1.2        | justenoughbuttons-1.12.2-1.2.2-5.jar            | None                                     |
	| UCHIJAAAA | modelloader              | 1.1.2           | modelloader-1.1.2.jar                           | None                                     |
	| UCHIJAAAA | magneticraft             | 2.4.4           | Magneticraft_1.12-2.4.4-dev.jar                 | None                                     |
	| UCHIJAAAA | neat                     | 1.4-17          | Neat 1.4-17.jar                                 | None                                     |
	| UCHIJAAAA | nuclearcraft             | 2.13d           | NuclearCraft-2.13d--1.12.2.jar                  | None                                     |
	| UCHIJAAAA | nvlforcefields           | 1.12.2.2491.1.0 | nvlforcefields-1.12.2.2491.1.0.jar              | None                                     |
	| UCHIJAAAA | omlib                    | 3.0.1-162       | omlib-1.12.2-3.0.1-162.jar                      | None                                     |
	| UCHIJAAAA | openmodularturrets       | 3.0.1-264       | openmodularturrets-1.12.2-3.0.1-264.jar         | None                                     |
	| UCHIJAAAA | p455w0rdslib             | 2.0.32          | p455w0rdslib-1.12-2.0.32.jar                    | None                                     |
	| UCHIJAAAA | storagenetwork           | 1.5.6           | SimpleStorageNetwork-1.12.2-1.5.6.jar           | None                                     |
	| UCHIJAAAA | spatialservermod         | 1.3             | spatialservermod-1.3.jar                        | None                                     |
	| UCHIJAAAA | techguns                 | 2.0.1.1         | techguns-1.12.2-2.0.1.1.jar                     | None                                     |
	| UCHIJAAAA | theoneprobe              | 1.4.23          | theoneprobe-1.12-1.4.23.jar                     | None                                     |
	| UCHIJAAAA | toughasnails             | 3.1.0.128       | ToughAsNails-1.12.2-3.1.0.128-universal.jar     | None                                     |
	| UCHIJAAAA | tanaddons                | 3.4.24          | ToughExpansion-1.12-3.4.24.jar                  | None                                     |
	| UCHIJAAAA | universalremote          | 1.12-0.9.10     | UniversalRemote-1.12-0.9.10.jar                 | None                                     |
	| UCHIJAAAA | wrcbe                    | 2.3.1           | WR-CBE-1.12.2-2.3.1.30-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.7.4.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [HookedEntityPlayerMP['DaComputerNerd'/1418, l='Test World 3', x=-260.30, y=79.87, z=-30.64]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DarkGuardsman** [comment]
Looks like more an issue with NVL mod than ICBM.

**Comment by DaComputerNerd717** [comment]
I posted it to both here and NVL's issue tracker; it is hard to say whether it's an issue with an active NVL forcefield being broken or if it's an issue with how ICBM breaks it

**Comment by DaComputerNerd717** [comment]
I managed to get around this issue by setting antimatter to be unable to break unbreakable blocks

**Comment by DarkGuardsman** [comment]
I think its most likely NVL, they likely assume the block is always in place and never check. I can't say without seeing the code but for the most part Antimatter just sets things to air. I could add an ignore/allow list later as that would be a good idea tbh.

**Comment by DaComputerNerd717** [comment]
it seems NVL is attempting to remove the active block but something isn't working; perhaps because the fields are already removed at just about the same time?

at hu.nvl.nvlforcefields.entities.NVLEntityFieldColumn.turnOff(NVLEntityFieldColumn.java:267)
at hu.nvl.nvlforcefields.entities.NVLEntityFieldColumn.destroyEndpoint(NVLEntityFieldColumn.java:64)

**Comment by DarkGuardsman** [comment]
Hard to say for sure as I don't know much about NVL mod

**Comment by DaComputerNerd717** [comment]
One thing that still strikes me as odd with this issue is that missiles didn't cause it. No matter whether they hit the field directly, or hit the force field controller, or hit the space in front of the field,  I never crashed from them. Only the TNT-style explosives.

**Comment by Pantheris2019** [comment]
IT could be an issue with mod interacting with the forcefield block by not being able to set it to offline directly using the antimatter explosive.
