### ISSUE TITLE
Launcher platform crashing server on bootup

### ISSUE THREAD

**Issue by bakerne** [BuiltBrokenModding/ICBM-Classic#193]
hello! 

we believe that there is something chunk loading the chunk that this particular launcher is in, however we aren't entirely sure that's it, so I figured I'd share the crash report with you all.

https://pastebin.com/hYMak9dV

we do have a lot of mods loaded, but ICBM is the only one mentioned to be related to the server tick loop exception. I reached out to the suspected player who had their launcher place, and they said it was in a chunkloaded chunk. So is there a chance that a launcher split between multiple chunks, or connected to multiple chunks, could cause this crash?

**Comment by DarkGuardsman** [comment]
Update to latest version you're 35 builds behind
