### ISSUE TITLE
[1.7] Energy buffer crash

### ISSUE THREAD

**Issue by DoctorChad** [BuiltBrokenModding/ICBM-Classic#194]
For some reason when I place down my Launchpad it crashes my game, and the world is then rendered unusable for as long as the launch pad is present. 

[crash-2019-02-02_21.07.10-server.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/2824861/crash-2019-02-02_21.07.10-server.txt)

`java.lang.NoSuchMethodError: icbm.classic.prefab.TileICBMMachine.getEnergyBuffer(Lnet/minecraftforge/common/util/ForgeDirection;)Lcom/builtbroken/mc/framework/energy/data/EnergyBuffer;
	at icbm.classic.prefab.TileICBMMachine.getEnergy(TileICBMMachine.java:97)
	at icbm.classic.content.machines.launcher.screen.TileLauncherScreen.getDescPacket(TileLauncherScreen.java:177)
	at icbm.classic.content.machines.launcher.screen.TileLauncherScreen.getDescPacket(TileLauncherScreen.java:50)
	at com.builtbroken.mc.prefab.tile.Tile.func_145844_m(Tile.java:1390)`

This is the crash file from my game.

**Comment by DarkGuardsman** [comment]
Check to make sure your using the latest alpha of both

**Comment by AtomicBrick** [comment]
the same, i can't build a launchpad and it only crashes the game making the world useless. I have the most recent version of the icbm classic

**Comment by DarkGuardsman** [comment]
Most recent beta or alpha?

**Comment by AtomicBrick** [comment]
alpha, for 1.7.10

**Comment by AtomicBrick** [comment]
and also happened in the most recent beta

**Comment by DarkGuardsman** [comment]
hmm, also have the latest alpha of VoltzEngine as well. As I think we did some work on the energy system shortly before moving to 1.12. Though this has been over a year ago so I can't recall the exacts. Honestly, you might have to go back a few versions. As there is a very high likely hood that the recent automated builds are corrupted. No one has been testing them in over a year.

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.
