### ISSUE TITLE
NoSuchMethodException in Xmas explosive

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#196]
As of ICBM-classic-1.12.2-3.3.0b63, NoSuchMethodException is reported when using the Xmas explosives: https://gist.github.com/LemADEC/455b8f6df7575c281bbc773ddb966f52

**Comment by DarkGuardsman** [comment]
Lem you know better than to paste a large crash log into github. 

As for the error make sure your using the latest alpha

**Comment by LemADEC** [comment]
b63 is the latest version available on CurseForge as of Feb 4th.
Are the UNSTABLE/alpha considered a different branch on CurseForge?

**Comment by DarkGuardsman** [comment]
Sorta, we use alpha as automated builds and beta as manually tested builds. That issue should be fixed in the latest alpha as it was reported a while back for the beta.

**Comment by LemADEC** [comment]
Issue is reproduced with latest alpha available on CurseForge as of Feb 6th: 1.12.2-3.3.0b62.
For the record, those errors are seen while in dev space, other launch environments were not tested.

**Comment by DarkGuardsman** [comment]
Rather strange, as I've had no issues on the test server with it and was spaming the xmas missiles all day monday. I'll check into it this weekend, we are almost done with the rewrite anyways.
