### ISSUE TITLE
Ender explosion does random teleportation instead of sending to the end (is it intended?)

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#20]
As observed in 1.7.10-2.15.1b33, not sure if it was already the case in 1.6.4 or intended

**Comment by DarkGuardsman** [comment]
I think it was changed in 1.6.4 to be targeted to a set location. If not targetted it will randomize to different locations. I can change it back but I'll leave this to later.

**Comment by LemADEC** [comment]
I'm fine with random teleportation as long as it keeps player on the top ground, not inside bases or in the clouds.

**Comment by DarkGuardsman** [comment]
I can fix that, though honestly its half of the fun lol

**Comment by LemADEC** [comment]
Well, then go maximum fun and make it happen also into fluids or on top of trees?

**Comment by DarkGuardsman** [comment]
I could toy around with it and make it really wacky. After all that is why I made the ender blocks explosive in the new ICBM.

**Comment by LemADEC** [comment]
yes, if it's too predictable or safe, players use it for bypassing shields.
