### ISSUE TITLE
Fragment explosives (anvil, shrapnel) do not fire a ProjectileImpactEvent

### ISSUE THREAD

**Issue by itsmeow** [BuiltBrokenModding/ICBM-Classic#200]
Essentially you can either use the base class or make your own that extends it. Just make sure it also fires the superclass event and is cancelable (no impact if canceled)

**Comment by DarkGuardsman** [comment]
https://builtbroken.codecks.io/decks/21-lts-1-12/card/1f6-missing-projectileimpactevent
