### ISSUE TITLE
Mod Compatability / More Events

### ISSUE THREAD

**Issue by itsmeow** [BuiltBrokenModding/ICBM-Classic#201]
Okay - so I've created a claims mod with about 20 different events and created an API. I do want to make an addon that will add protection for claims from ICBM via this API. But first I need a few events.

1. #200 
2. Some sort of gas effect event, gives an entity to be affected as well as the original explosion position
3. Route small-medium scale explosives through ExplosionEvent.Detonate (Thermobaric, nuke, S-Mine)
4. An event for picking up blocks (sonic, hypersonic, endothermic, exothermic, anti-gravity, redmatter) which gives a list of blocks similar to ExplosionEvent.Detonate which can be modified.
5. An event for placing blocks. This includes fire from Incendiary, lava, snow, water, ice, netherrack (endo/exothermic)
6. A general detonation event. Any time a missile/explosive is detonated, it can be canceled via this event.
7. Not sure how antimatter would work - but possibly an event for destroying blocks. I'm aware it's under rewrite and is also multi-threaded, but if it doesn't destroy performance, an event with block positions to be affected. However for this I'd probably just block detonation if a claim is within its radius.

**Comment by DarkGuardsman** [comment]
Closing without migrating to codecks given split cards. New system will pump majority of the custom stuff through the action system. Anything vanilla like will go through available events if reasonable.
