### ISSUE TITLE
[1.12] Possible entity tracker null crash from flying blocks

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM-Classic#202]
Test server we ran into an issue with the EntityTracker (MC system for syncing entities, not the ICBM tracker) that was throwing NPE crashing the server. After getting in I ran 'ICBM lag' to check for missiles as we had this crash when mass spamming missiles the other day. No missiles were in range but it did clear out a lot of entities. This could possibly be flying blocks but its not easy to tell. Though after clearing these entities the server did not crash again.

**Comment by Redd56** [comment]
Thats how minecraft works 💁

**Comment by DarkGuardsman** [comment]
ya sadly
