### ISSUE TITLE
1.13, when?

### ISSUE THREAD

**Issue by Delaser** [BuiltBrokenModding/ICBM-Classic#203]
Just wondering if theres any chance this mod would run with 1.13?

I need the datapacks feature from 1.13, what issues might I have trying to get this to run?

Thanks!

**Comment by Redd56** [comment]
A: probably not unless god himself blesses it
B: what about datapacks now?.... This is for forge 1.12.2..

**Comment by Delaser** [comment]
Forge 1.12.2 means it works with minecraft 1.12 right?

https://minecraft.gamepedia.com/Data_pack

The world data packs are minecraft 1.13

**Comment by DarkGuardsman** [comment]
mods are more or less datapacks in 1.13... likely 1-2 months before we even try to update to 1.13. Currently Forge is only in beta for 1.13 and is very very unstable. We currently have 8 SBM mods updated and most have had issues during the update. So if a small mod is having problems a medium/large sized mod like ICBM is going to be painful to update. Likely some features may not even update well until forge itself is stable.

**Comment by Redd56** [comment]
I know what they are but im confused how datapacks get involved into forge.. also they where kinda introduced in 1.12 with the function system though it was much more limited

**Comment by bl4ckscor3** [comment]
Datapacks have nothing to do with Forge in this case. Delaser just wants to utilize them, while also wanting to play around with ICBM in 1.13.

**Comment by Redd56** [comment]
Then why did you ask about datapacks...

**Comment by bl4ckscor3** [comment]
They didn't ask about datapacks, they merely used them as a reason for their question on updating ICBM to 1.13.

**Comment by DarkGuardsman** [comment]
Sounds about right, either way its going to take a while to update. Right now I'm still working on the rewrite to make ICBM API driven. That way we can produce addons and implement new content in the future. Might take a while longer now that 1.13 is ready. As I need to take a look at what content needs changed to function on 1.13. Especially since I'm already messing with the save states might as well plan for 1.13.

**Comment by bl4ckscor3** [comment]
Since this is not really an issue and your question was answered (the answer still applies to 1.14 and any following version), I'll close this. The rewrite isn't done, and until it is we won't start updating to newer Minecraft versions.
