### ISSUE TITLE
[1.12] Explosive resistance scale is off for concrete 

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM-Classic#206]
Obsidian is surviving nukes but not the concrete. This needs to be changed as a tier 3 concrete block should survive a direct hit nuke.

**Comment by ProfessorCool** [comment]
I'm running on 1.12.2-3.3.0b63. When I set off a breaching explosive, or shoot a missile, it will always penetrate through a block, regardless of whether the block is unbreakable or not. Here's screenshots of the behavior:
![image](https://user-images.githubusercontent.com/37518092/54089512-34cec200-432f-11e9-8cb3-556002846936.png)
![image](https://user-images.githubusercontent.com/37518092/54089517-44e6a180-432f-11e9-8d7c-8f3ffecab362.png)
This effectively makes it impossible to protect from breaching explosives without 6 layers of very blast resistant material.
