### ISSUE TITLE
Add decay mechanic to red matter when no more matter is available.

### ISSUE THREAD

**Issue by Onixiya** [BuiltBrokenModding/ICBM-Classic#207]
So, i launched the red matter missile and its all good with destruction and all that but is there a way to remove the black hole once its done chewing up everything it can reach? I accidentally used one on one of my good worlds and i want to remove it.

**Comment by DarkGuardsman** [comment]
It should have a timer that causes it to decay overtime. The other option is to use the admin command "/icbm lag" to clear it or destroy it with an antimatter missile. Future plans do include a better death mechanic were it will get energy as it eats items and lose energy over time. Meaning that when its not eating items it will die faster than it currently does.

**Comment by Onixiya** [comment]
That's helpful. Thank you. Need to launch a couple of rejuev missiles now but it'll be worth it
