### ISSUE TITLE
[1.12] Breaching charge creates crater through unbreakable blocks

### ISSUE THREAD

**Issue by ProfessorCool** [BuiltBrokenModding/ICBM-Classic#208]
I'm running on 1.12.2-3.3.0b63. When setting off a breaching explosive or a missile, the explosion ignores blast resistant or unbreakable blocks. Here's some screenshots of it:
![image](https://user-images.githubusercontent.com/37518092/54089562-ccccab80-432f-11e9-8c72-91e4c1d1b278.png)
![image](https://user-images.githubusercontent.com/37518092/54089563-d524e680-432f-11e9-8c45-417e97dfd74c.png)
This effectively makes it impossible to protect from breaching charges without 6 layers of very blast resistant material.

**Comment by GHXX** [comment]
fixed in the blast-rewrite branch. thanks again for reporting!
