### ISSUE TITLE
Can't place block over an ongoing explosion

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#21]
As of 1.7.10-2.15.1b33, when an explosion effect is ongoing, you can't place blocks over it. It's probably blocked by the invisible explosion entity. Since it invisible could we remove the collision effect?

**Comment by DarkGuardsman** [comment]
Honestly, going to leave this as the user shouldn't be building in the middle of a blast and allowing placement might move the blast entity.

**Comment by LemADEC** [comment]
Certain explosive only have potion effects, like Debilitation and Chemical ones. It's weird that you can't place another of those at the location of them.
Explosion entities are already non-moveable by entities and block after/during the blast.
Arrows and GunCus bullets can still go through the explosion, which is good.

**Comment by DarkGuardsman** [comment]
I'll toy around with it, honestly for those types I need to recode the entity to render the explosive. This way with particle effects turned off people know it is releasing gas.

**Comment by DarkGuardsman** [comment]
Ok, it has been fixed, how it works now is if the blast can not be moved it will spawn the entity at the bottom of the map. This way the entity is out of the way allowing for block placement and effects spawning inside of walls. 

I will be designing a better system later for ICBM-rewrite to use and will port it over for ICBM-classic to use. This way there will not be issues in the future will mod support breaking the entity being at the bottom of the map.
