### ISSUE TITLE
Config File error

### ISSUE THREAD

**Issue by NGSquirrely** [BuiltBrokenModding/ICBM-Classic#212]
Within the items configuration tab, if not all values are false or true, the game will crash on launch. 

I tried disabling ingots and circuits, and with "crafting" enabled, it crashed. I just set everything to false and it worked again.

**Comment by DarkGuardsman** [comment]
Want to share said crash?

**Comment by GHXX** [comment]
Since we have been waiting for a crashlog for a while ill close this one. If you, @NGSquirrely can provide the crashlog then ill re-open the issue and we can look into fixing it.
