### ISSUE TITLE
[1.7.10] Red Matter doesn't suck in or damage players

### ISSUE THREAD

**Issue by SnowyJune678** [BuiltBrokenModding/ICBM-Classic#214]
The red matter explosives does not suck in or damage players.

**Comment by GHXX** [comment]
~~What build of icbm are you running, and what minecraft version?~~
Edit: just saw the 1.7.10 in the title. Its implemented in 1.12, but im not sure about 1.7.10, maybe @DarkGuardsman knows?

**Comment by bl4ckscor3** [comment]
The 1.7.10 version is @kmecpp's jurisdiction as far as I know .

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.
