### ISSUE TITLE
[1.7.10] Radar station emitting redstone signal if missile is targeted in safe zone, but out of alarm zone 

### ISSUE THREAD

**Issue by SnowyJune678** [BuiltBrokenModding/ICBM-Classic#215]
Issue #138 happens in 1.7.10 as well, and has not been resolved.

**Comment by DarkGuardsman** [comment]
Honestly, its unlike 1.7.10 will receive fixes

**Comment by SnowyJune678** [comment]
Sorry for the late reply but isn't it just a matter of changing the names in /src/main/resources/assets/icbmclassic/lang/ ? Its literally the same as #138 so changing the names would probably resolve it. Are blast-rewrite or kmeccp 1.7 ?

**Comment by SnowyJune678** [comment]
UPDATE: It looks like branches "1.7" and "kmecpp" are built for 1.7. . I have no idea which one is the latest 1.7 version.

**Comment by DarkGuardsman** [comment]
In theory kmecpp is the latest, but I have not checked how much work he has done. Since I've been busy he took over 1.7 patches in my place. The plan likely will be to merge his changes over to the main 1.7 branch if he wishes to continue.

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.
