### ISSUE TITLE
[1.12.2]Ingame config changes don't save

### ISSUE THREAD

**Issue by Tommeh1** [BuiltBrokenModding/ICBM-Classic#217]
Using latest, title tells enough

**Comment by DarkGuardsman** [comment]
Note for self: Likely missing config changed event for loading new changes into fields.

**Comment by GHXX** [comment]
Seems to work in the current dev branch now, so its likely fixed, although if i remember correctly then it also worked before you opened this issue. So maybe its tied to a specific config setting?

**Comment by GHXX** [comment]
Ill flag this one with fixed in the blast-rewrite branch since i cant reproduce it.

**Comment by Tommeh1** [comment]
Fixed
