### ISSUE TITLE
[1.12.2] Crash after opening creative tab

### ISSUE THREAD

**Issue by 89Mods** [BuiltBrokenModding/ICBM-Classic#219]
I'm experiencing an issue where opening the mod's creative tab instantly crashes the game. Using the latest version of forge for 1.12.2 (14.23.5.2837).

Crash log: https://pastebin.com/hW2cE8mB

**Comment by GHXX** [comment]
The code in which the bug occoured doesnt exist anymore in the branch we currently use to develop (blast-rewrite), and i havent encountered any creative-tab crashes there yet.
So when we merge the blast-rewrite branch we will need to test if this issue still exists.

**Comment by Tommeh1** [comment]
Issue no longer exists in the blast rewrite(ICBM-classic-1.12.2-4.0.0b20200101191300.jar)
