### ISSUE TITLE
[1.12.2] Breaking Radar Station Crashes Server

### ISSUE THREAD

**Issue by anicetus1** [BuiltBrokenModding/ICBM-Classic#220]
When trying to set up an anti-ballistic missile system using the radar, the first time the missile was re-rendered the server crashed. After reloading the server the radar station was broken on the ground as an item. I could replicate a crash breaking a placed radar station, so now every time a radar station is broken it crashes the server.

Crash Report is here: https://pastebin.com/uAm0PB4C

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.
 
Time: 2019-05-21 20:57:52 UTC
Description: Ticking block entity
 
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=redstone, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
    at icbm.classic.content.machines.radarstation.TileRadarStation.update(TileRadarStation.java:111)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zzj000(World.java:4131)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Block entity being ticked --
  Name: icbmclassic:radarstation // icbm.classic.content.machines.radarstation.TileRadarStation
  Block type: ID #1930 (tile.icbmclassic:radarstation // icbm.classic.content.machines.radarstation.BlockRadarStation // icbmclassic:radarstation)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (1658,83,451), Chunk: (at 10,5,3 in 103,28; contains blocks 1648,0,448 to 1663,255,463), Region: (3,0; contains chunks 96,0 to 127,31, blocks 1536,0,0 to 2047,255,511)
  Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir // minecraft:air)
  Actual block data value: 0 / 0x0 / 0b0000
  Block Entity NBT: {safetyBanJing:50,tier:0,x:1658,y:83,z:451,id:"icbmclassic:radarstation",emitAll:1b,alarmBanJing:100,frequency:0,energy:0}
 
-- Affected level --
  Level name: world
  All players: 3 total; [GCEntityPlayerMP['SpoiledChild'/68, l='world', x=1660.89, y=83.80, z=450.70], GCEntityPlayerMP['BrickWalsh'/69, l='world', x=1198.51, y=68.18, z=840.70], GCEntityPlayerMP['Super_Gogeta_'/1591, l='world', x=1680.30, y=121.25, z=415.30]]
  Chunk stats: ServerChunkCache: 995 Drop: 0
  Level seed: -1341729741782585133
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options:
  Level spawn location: World: (-184,64,256), Chunk: (at 8,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 10164040 game time, 3078686 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 16846 (now: false), thunder time: 73146 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
 
-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.9.177-xxxx-std-ipv6-64
  Java Version: 1.8.0_191, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1136878688 bytes (1084 MB) / 2951741440 bytes (2815 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 4 total; -Xmx4096M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
  IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2768 127 mods loaded, 127 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State     | ID                                   | Version           | Source                                             | Signature                                |
       |:--------- |:------------------------------------ |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
       | UCHIJAAAA | minecraft                            | 1.12.2            | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | mcp                                  | 9.42              | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | FML                                  | 8.0.99.99         | custom.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | forge                                | 14.23.5.2768      | custom.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | creativecoredummy                    | 1.0.0             | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | ivtoolkit                            | 1.3.3-1.12        | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | littletilescore                      | 1.0.0             | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | micdoodlecore                        |                   | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | smoothfontcore                       | mc1.12.2-1.16     | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | openmodscore                         | 0.12.1            | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | foamfixcore                          | 7.7.4             | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | srm-hooks                            | 1.12.2-1.0.0      | minecraft.jar                                      | None                                     |
       | UCHIJAAAA | randompatches                        | 1.12.2-1.12.1.0   | randompatches-1.12.2-1.12.1.0.jar                  | None                                     |
       | UCHIJAAAA | baubles                              | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
       | UCHIJAAAA | jei                                  | 4.15.0.275        | jei_1.12.2-4.15.0.275.jar                          | None                                     |
       | UCHIJAAAA | thaumcraft                           | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
       | UCHIJAAAA | botania                              | r1.10-360         | Botania+r1.10-360.jar                              | None                                     |
       | UCHIJAAAA | redstoneflux                         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | cofhcore                             | 4.6.2             | CoFHCore-1.12.2-4.6.2.25-universal.jar             | None                                     |
       | UCHIJAAAA | craftstudioapi                       | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | UCHIJAAAA | mantle                               | 1.12-1.3.3.49     | Mantle-1.12-1.3.3.49.jar                           | None                                     |
       | UCHIJAAAA | natura                               | 1.12.2-4.3.2.66   | natura-1.12.2-4.3.2.66.jar                         | None                                     |
       | UCHIJAAAA | harvestcraft                         | 1.12.2z           | Pam's+HarvestCraft+1.12.2za.jar                    | None                                     |
       | UCHIJAAAA | twilightforest                       | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
       | UCHIJAAAA | animania                             | 1.6.2             | animania-1.12.2-1.6.2.jar                          | None                                     |
       | UCHIJAAAA | appleskin                            | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | UCHIJAAAA | appliedenergistics2                  | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | UCHIJAAAA | backpack                             | 3.0.2             | backpack-3.0.2-1.12.2.jar                          | None                                     |
       | UCHIJAAAA | bno                                  | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.4.0.jar                 | None                                     |
       | UCHIJAAAA | battletowers                         | 1.6.4             | BattleTowers-1.12.2_1.6.4.jar                      | None                                     |
       | UCHIJAAAA | bibliocraft                          | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | UCHIJAAAA | bookshelf                            | 2.3.577           | Bookshelf-1.12.2-2.3.577.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | buildcraftlib                        | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJAAAA | buildcraftcore                       | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJAAAA | buildcraftbuilders                   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJAAAA | buildcrafttransport                  | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJAAAA | buildcraftsilicon                    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJAAAA | crafttweaker                         | 4.1.17            | CraftTweaker2-1.12-4.1.17.jar                      | None                                     |
       | UCHIJAAAA | buildcraftcompat                     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJAAAA | buildcraftenergy                     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJAAAA | buildcraftfactory                    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJAAAA | buildcraftrobotics                   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJAAAA | cctweaked                            | 1.82.1            | cc-tweaked-1.12.2-1.82.1.jar                       | None                                     |
       | UCHIJAAAA | computercraft                        | 1.82.1            | cc-tweaked-1.12.2-1.82.1.jar                       | None                                     |
       | UCHIJAAAA | chesttransporter                     | 2.8.8             | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
       | UCHIJAAAA | chisel                               | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | UCHIJAAAA | chococraft                           | 0.9.8.0           | chococraft_1.12.2-0.9.8.0.jar                      | None                                     |
       | UCHIJAAAA | codechickenlib                       | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | cofhworld                            | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | cosmeticarmorreworked                | 1.12.2-v4         | CosmeticArmorReworked-1.12.2-v4.jar                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UCHIJAAAA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4         | CosmeticArmorReworked-1.12.2-v4.jar                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UCHIJAAAA | crafttweakerjei                      | 2.0.3             | CraftTweaker2-1.12-4.1.17.jar                      | None                                     |
       | UCHIJAAAA | creativecore                         | 1.9.9             | CreativeCore_v1.9.41_mc1.12.2.jar                  | None                                     |
       | UCHIJAAAA | dimdoors                             | 3.0.9+287         | DimensionalDoors-3.0.9-287.jar                     | None                                     |
       | UCHIJAAAA | dungeontactics                       | DT-0.15.8         | DungeonTactics-1.12.2-0.15.8.jar                   | None                                     |
       | UCHIJAAAA | eplus                                | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | endercore                            | 1.12.2-0.5.53     | EnderCore-1.12.2-0.5.53.jar                        | None                                     |
       | UCHIJAAAA | thermalfoundation                    | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | thermalexpansion                     | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | enderio                              | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderiointegrationtic                | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderiobase                          | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderioconduits                      | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderioconduitsappliedenergistics    | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderioconduitsopencomputers         | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderioconduitsrefinedstorage        | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderiointegrationforestry           | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | tconstruct                           | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar                   | None                                     |
       | UCHIJAAAA | enderiointegrationticlate            | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderiomachines                      | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderiopowertools                    | 5.0.43            | EnderIO-1.12.2-5.0.43.jar                          | None                                     |
       | UCHIJAAAA | enderstorage                         | 2.4.5.135         | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | energyconverters                     | 1.2.1.11          | energyconverters_1.12.2-1.2.1.11.jar               | None                                     |
       | UCHIJAAAA | extrautils2                          | 1.0               | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | UCHIJAAAA | zerocore                             | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                        | None                                     |
       | UCHIJAAAA | bigreactors                          | 1.12.2-0.4.5.66   | ExtremeReactors-1.12.2-0.4.5.66.jar                | None                                     |
       | UCHIJAAAA | facmod                               | 3.5.0             | faction-mod-3.5.0.jar                              | None                                     |
       | UCHIJAAAA | flansmod                             | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                        | None                                     |
       | UCHIJAAAA | flansmodapocalypse                   | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                        | None                                     |
       | UCHIJAAAA | foamfix                              | 0.10.5-1.12.2     | foamfix-0.10.5-1.12.2.jar                          | None                                     |
       | UCHIJAAAA | worldedit                            | 6.1.8             | worldedit-forge-mc1.12-6.1.8-dist.jar              | None                                     |
       | UCHIJAAAA | forgeessentials                      | 12.3              | forgeessentials-1.12.2-12.3.56-server.jar          | None                                     |
       | UCHIJAAAA | forgelin                             | 1.8.2             | Forgelin-1.8.2.jar                                 | None                                     |
       | UCHIJAAAA | forgemultipartcbe                    | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJAAAA | microblockcbe                        | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
       | UCHIJAAAA | minecraftmultipartcbe                | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
       | UCHIJAAAA | cfm                                  | 6.2.0             | furniture-6.2.0-1.12.2.jar                         | None                                     |
       | UCHIJAAAA | ic2                                  | 2.8.999           | IC2Classic+1.12-1.5.4.2.jar                        | None                                     |
       | UCHIJAAAA | galacticraftcore                     | 4.0.2.210         | GalacticraftCore-1.12.2-4.0.2.210.jar              | None                                     |
       | UCHIJAAAA | galacticraftplanets                  | 4.0.2.210         | Galacticraft-Planets-1.12.2-4.0.2.210.jar          | None                                     |
       | UCHIJAAAA | helpfixer                            | 1.12.1-1.5.18     | HelpFixer-1.12.1-1.5.18.jar                        | None                                     |
       | UCHIJAAAA | placebo                              | 1.5.1             | Placebo-1.12.2-1.5.1.jar                           | None                                     |
       | UCHIJAAAA | hexxitgear                           | 2.8.0             | Hexxit+Gear-1.12.2-2.8.0.jar                       | None                                     |
       | UCHIJAAAA | waila                                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | UCHIJAAAA | ic2-classic-spmod                    | 0.0.0.0           | IC2Classic+1.12-1.5.4.2.jar                        | None                                     |
       | UCHIJAAAA | icbmclassic                          | 1.12.2-3.3.0.63   | ICBM-classic-1.12.2-3.3.0b63.jar                   | None                                     |
       | UCHIJAAAA | teslacorelib                         | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAA | industrialforegoing                  | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.11-235.jar         | None                                     |
       | UCHIJAAAA | infernalmobs                         | 1.7.3             | InfernalMobs-1.12.jar                              | None                                     |
       | UCHIJAAAA | ironchest                            | 1.12.2-7.0.59.842 | ironchest-1.12.2-7.0.59.842.jar                    | None                                     |
       | UCHIJAAAA | jrftl                                | 1.1               | JRFTL[1.12.2]-1.1.jar                              | None                                     |
       | UCHIJAAAA | littletiles                          | 1.5.0             | LittleTiles_v1.5.0-pre130_mc1.12.2.jar             | None                                     |
       | UCHIJAAAA | mcmultipart                          | 2.5.3             | MCMultiPart-2.5.3.jar                              | None                                     |
       | UCHIJAAAA | recipehandler                        | 0.13              | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
       | UCHIJAAAA | openmods                             | 0.12.1            | OpenModsLib-1.12.2-0.12.1.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAA | openblocks                           | 1.8               | OpenBlocks-1.12.2-1.8.jar                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJAAAA | quacklib                             | 2.2.5             | quacklib-2.2.5.jar                                 | None                                     |
       | UCHIJAAAA | quickhomes                           | 1.2.2             | QuickHomes-1.2.2.jar                               | None                                     |
       | UCHIJAAAA | quickteleports                       | 1.1.0             | quickteleports-1.1.0.jar                           | None                                     |
       | UCHIJAAAA | reccomplex                           | 1.4.8.2           | RecurrentComplex-1.4.8.2.jar                       | None                                     |
       | UCHIJAAAA | redstonearsenal                      | 2.6.2             | RedstoneArsenal-1.12.2-2.6.2.17-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | redwoods                             | 1.2.1             | Redwoods-1.12-1.2.1.jar                            | None                                     |
       | UCHIJAAAA | reforged                             | 0.7.5             | Reforged-0.7.5-1.12+.jar                           | None                                     |
       | UCHIJAAAA | xreliquary                           | 1.12.2-1.3.4.786  | Reliquary-1.12.2-1.3.4.786.jar                     | None                                     |
       | UCHIJAAAA | rswires                              | 1.0               | rswires-3.0.1.jar                                  | None                                     |
       | UCHIJAAAA | ruins                                | 17.1              | Ruins-1.12.2.jar                                   | None                                     |
       | UCHIJAAAA | secretroomsmod                       | 5.6.4             | secretroomsmod-1.12.2-5.6.4.jar                    | None                                     |
       | UCHIJAAAA | thermaldynamics                      | 2.5.4             | ThermalDynamics-1.12.2-2.5.4.18-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJAAAA | simplyjetpacks                       | 2.2.10.63         | SimplyJetpacks2-1.12.2-2.2.10.63.jar               | None                                     |
       | UCHIJAAAA | soulshardsrespawn                    | 1.12.2-1.1.0-12   | SoulShardsRespawn-1.12.2-1.1.0-12.jar              | None                                     |
       | UCHIJAAAA | traverse                             | 1.6.0             | Traverse-1.12.2-1.6.0-69.jar                       | None                                     |
       | UCHIJAAAA | bspkrscore                           | at_0.9            | Treecapitator-1.12-at_0.9a.jar                     | None                                     |
       | UCHIJAAAA | treecapitator                        | at_0.9            | Treecapitator-1.12-at_0.9a.jar                     | None                                     |
       | UCHIJAAAA | vanillafix                           | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                           | None                                     |
       | UCHIJAAAA | wanionlib                            | 1.12.2-2.2        | WanionLib-1.12.2-2.2.jar                           | None                                     |
       | UCHIJAAAA | teslacorelib_registries              | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
       | UCHIJAAAA | unidict                              | 1.12.2-2.9.2      | UniDict-1.12.2-2.9.2.jar                           | None                                     |
  Loaded coremods (and transformers): LittlePatchingLoader (LittleTiles_v1.5.0-pre130_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.53-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.41_mc1.12.2.jar)
                                       
                                      RandomPatches (randompatches-1.12.2-1.12.1.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                       
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-1.16.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                       
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                       
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
                                        openmods.core.OpenModsClassTransformer
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  ForgeEssentials: Running ForgeEssentials 12.3.56 (fccdc2d). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
  Ender IO: No known problems detected.
           
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: ICBM-Classic (icbmclassic)
  Profiler Position: N/A (disabled)
  Player Count: 3 / 40; [GCEntityPlayerMP['SpoiledChild'/68, l='world', x=1660.89, y=83.80, z=450.70], GCEntityPlayerMP['BrickWalsh'/69, l='world', x=1198.51, y=68.18, z=840.70], GCEntityPlayerMP['Super_Gogeta_'/1591, l='world', x=1680.30, y=121.25, z=415.30]]
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

The issue only seems to happen with radar stations in areas near incoming missiles, or where past missiles have hit.

**Comment by DarkGuardsman** [comment]
```
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=redstone, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
at icbm.classic.content.machines.radarstation.TileRadarStation.update(TileRadarStation.java:111)
```

Looks like something happened to the block to cause it to be removed but not for the tile entity to clear. I can fix it but still strange.
