### ISSUE TITLE
Turrets FOR 1.12.2 !

### ISSUE THREAD

**Issue by epicreis** [BuiltBrokenModding/ICBM-Classic#222]
I asked you when will you add turrets. **I mean in 1.12.2**. You posted the link but this mod only working on 1.7.10. I'm going to ask the same question second but with a little difference, when will you add turrets to **_1.12.2_** icbm-classic ?

**Comment by epicreis** [comment]
I know, Mod developing is a hard thing but I want to use this turrets because I want to make a great base.

**Comment by DarkGuardsman** [comment]
Never, that was the whole point of sending you the link and locking the ticket. Both the ICBM-Classic page and sentry page explain why its not included. The mod will be updated as an addon for Armory when I get time to update armory. 

Only reason it was ever included in ICBM was to reduce conflict with Calcalvia. However, I never liked my sentries being included as part of a missile mod. As this limited gameplay heavily for modpack developers. 

https://minecraft.curseforge.com/projects/armory-icbm-sentries
