### ISSUE TITLE
[1.12] Crashing with fluxducts

### ISSUE THREAD

**Issue by dpPandora** [BuiltBrokenModding/ICBM-Classic#223]
My game crashes when I place a fluxduct next to the T1 launch platform

**Comment by DarkGuardsman** [comment]
can't do much without a crash report/log

**Comment by GHXX** [comment]
Since we have been waiting for a crashlog for a while ill close this one. If you, @HadrianDiaz can provide the crashlog then ill re-open the issue and we can look into fixing it.
