### ISSUE TITLE
Anti Missile targets other Anti Missile

### ISSUE THREAD

**Issue by yossi2000** [BuiltBrokenModding/ICBM-Classic#225]
When you launch two anti missile close to each other it intercepts the anti missile.
i wanna make an iron dome like intercepts defences, but how can i if you even shoot Anti missile one after another and it will intercept the first Anti Missile and now the Incoming Enemy Missile.

**Comment by yossi2000** [comment]
?

**Comment by DarkGuardsman** [comment]
hmm strange there was a reply on this a while ago... either way the current system is not great and it will not be fixed until we get a chance to rewrite the system.
