### ISSUE TITLE
Chinese language errors

### ISSUE THREAD

**Issue by Dr-WeiAL** [BuiltBrokenModding/ICBM-Classic#227]
作者你好,我发现mod本身的中文为Unicode编码,这导致游戏内不能显示中文,而且转换成中文后是繁体中文,不是简体中文,我这里附上了两个转换后的语言文件,希望作者在下次更新的时候换上这个

Hello author, I found that the Chinese language of mod itself is Unicode encoding, which leads to the inability to display Chinese in the game, and it is traditional Chinese after conversion to Chinese, not simplified Chinese. I have attached two converted language files here, I hope the author Change this at the next update
Google Translate, forgive me 

[zh.zip](https://github.com/BuiltBrokenModding/ICBM-Classic/files/3358701/zh.zip)

**Comment by GHXX** [comment]
Thank you for your contribution.
But we renamed some things and moved stuff around.
Could you please take a look at the en_US.lang file in the [blast-rewrite branch](https://github.com/BuiltBrokenModding/ICBM-Classic/blob/blast-rewrite/src/main/resources/assets/icbmclassic/lang/en_US.lang)?
Please update your translation and i will be happy to merge it.

**Comment by GHXX** [comment]
Gonna close this one due to inactivity.
