### ISSUE TITLE
[1.12] Red Matter Bomb Crashed Entire Server

### ISSUE THREAD

**Issue by MadDog443** [BuiltBrokenModding/ICBM-Classic#228]
I am not sure how but an up to date version of this mod for 1.12.2 crashed a entire server when some asshat decided to Red Matter spawn, it might have been caused over disputes with other mods like RF Shields, Unbreakable Blocks, Airplanes, Block Protectors, etc... but nobody knows.
I am currently waiting on the server logs to be public as this is a big time server for Sjin's Discord, I will post them ASAP; for more info please contact Naird. 
`The modpack is called Sjincord Ampz, you can contact Naird on Discord at @Nairdwood#0001`

**Comment by DarkGuardsman** [comment]
ok, once you get me the crash log I should be able to look into it.

**Comment by GHXX** [comment]
Since we have been waiting for a crashlog for a while ill close this one. If you, @MadDog443 can provide the crashlog then ill re-open the issue and we can look into fixing it.
