### ISSUE TITLE
[1.12.2] Anti-Ballistic Missile Doesn't Target Incoming Missiles

### ISSUE THREAD

**Issue by JustLukes** [BuiltBrokenModding/ICBM-Classic#229]
Fairly Self Explanatory.
Running version "ICBM-classic-1.12.2-3.3.0b65" And When I Launch A Missile, The Radar Detects And Fires An Anti-Ballistic Missile. But Doesnt Aim It At The Incoming Missile.

Please Help

**Comment by DarkGuardsman** [comment]
Current version of the mod (and all versions before it) missiles are not aimed towards the target missile. They have a 30m detection range to locate the target missile and start tracking. This means if the missile is not within range it will not start tracking. To get around this you can fire the AB missile in the expected direction of an attack. Then have it fire either on its own or in a group based on a detection zone (target in the picture under). Common usage I've seen is to setup a few radars ahead of the missile path. Then trigger the AB to fire into the detection zone. 
![ABS-Setup](https://user-images.githubusercontent.com/1477330/61124736-b49fa100-a475-11e9-9b89-629d244ca771.png)

In the future I do plan to rewrite the AB missile system to solve this problem

**Comment by JustLukes** [comment]
I sorta understand what you mean, but the diagram is a bit confusing.
