### ISSUE TITLE
Lag from constant file access in world tick events

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#232]
As of "1.12.2-3.3.0b65-UNSTABLE build 65", lag is observed from pre/post events, with 1.5% CPU taken according to LagGoogles on a dedicated server:
![image](https://user-images.githubusercontent.com/4776032/61668917-a572eb80-acde-11e9-8ddd-13768e2c4f4f.png)

This lag source doesn't scale with number of online players.

From a quick profiling, this is due to recurrent file access in both Pre and Post World tick events:
![image](https://user-images.githubusercontent.com/4776032/61669233-95a7d700-acdf-11e9-8680-c3e5ce44d9fa.png)

**Comment by LemADEC** [comment]
The double call per tick doesn't seem to be intended, moving missiles twice faster than expected.
A similar issues is seen in BlockEditHandler, placing blocks twice faster than expected.

**Comment by DarkGuardsman** [comment]
I'm having trouble understanding how 1.5% is considered lag. What you are seeing is the game loading chunks. Though I'm confused why its show getHandler() -> getOrLoadData().

**Comment by LemADEC** [comment]
The measure is relative to a tick: 1.5% of each tick is used by the mod just for (re)loading its world's specific data for missile handling.
It's not about the game loading chunks here.
It's about the MissileTrackerHandler tick event constantly asking to load its data from the world because the cache is empty because no missiles are flying.
You're seeing this call here: https://github.com/BuiltBrokenModding/ICBM-Classic/blob/5f3bc0cd347c3df4b8f88da75ab6e66358b9b606/src/main/java/icbm/classic/content/missile/MissileTrackerHandler.java#L95 which fails the cache and proceed with loading the world data https://github.com/BuiltBrokenModding/ICBM-Classic/blob/5f3bc0cd347c3df4b8f88da75ab6e66358b9b606/src/main/java/icbm/classic/content/missile/MissileTrackerHandler.java#L59

**Comment by GHXX** [comment]
1.5% doesn't seem like a big improvement, but it's certainly an improvement. So thank you for pointing that out. It should be applied when this branch is merged into the main one which will happen when the blast rewrite is complete.
Feel free to bring up any other performance issues / improvements you find (create a new issue for that though, please)

**Comment by LemADEC** [comment]
100% is the CPU time available for a single tick.
1.5% is a lot for a IDLE task in a single mod. It's common for modpack to have 100+ mods, imagine what happens when all of them are consuming 1.5% of a tick time just in IDLE state.
On a different perspective, imagine a modpack that start lagging when 66 mods are loaded, without any entity, block nor player doing anything.
