### ISSUE TITLE
Missiles not launching after the use of laser designator or radar/remote detonator [12.2.2]

### ISSUE THREAD

**Issue by LordGooon** [BuiltBrokenModding/ICBM-Classic#235]
I've been using the twitch loader and everything in the mod including the launches have worked excellently. however, after attempting to run the mod on both my forge server and just from my basic minecraft forge installation on the minecraft launcher, the same issue arises. everything in the pack works and is placeable along with other mods I have installed, but the missiles in the silos just refuse to launch. The closest that they get occurs after I use the designator. After use, it will say "firing missile at "x" "y" "z"" and then it will just sit there as if nothing happened. On my server i have ensured that my client and server are both running the same version and I have triple checked that my mods are in the correct files. it seems almost as if there is a chunk of a file somewhere that needs to be added somewhere but I can't tell where that might be aside from a cluster of files present in my "instances" folder for the twitch mod launcher where a few additional files reside outside of my mod folder.

**Comment by LordGooon** [comment]
![image](https://user-images.githubusercontent.com/53377318/61997517-368fec80-b068-11e9-932c-97e383aa5f6d.png)

these are the files present in my .minecraft folder

![image](https://user-images.githubusercontent.com/53377318/61997526-4e677080-b068-11e9-8a11-4d40159f31ef.png)

these are the files present in my twitch instances folder

![image](https://user-images.githubusercontent.com/53377318/61997560-c2a21400-b068-11e9-9e3a-05039f174e9e.png)

these are the files present in the both of the mods folders from the previous images

**Comment by GHXX** [comment]
Have you linked the laser designator with the launcher? (right click the launchpad with the designator)

**Comment by GHXX** [comment]
Im assuming this was due to not linking the laser designator, which is a mistake made by the user, Although there could be a message that is sent when no missile could be fired, or when the laser designator wasnt linked yet. (see #242)
