### ISSUE TITLE
[Suggestion] Let EMP Tower Remove RF, FE, MJ energy from machines and storages in range

### ISSUE THREAD

**Issue by Dente222** [BuiltBrokenModding/ICBM-Classic#237]
As in topic, please add a function that will instantly deploy energy from energy storage blocks and machines that are in the range of EMP tower :)

**Comment by DarkGuardsman** [comment]
Not possible with the current way Forge energy (FE), RedstoneFlux(RF), and MincraftJoules(MJ) work. I've been trying to get around the problem for a year plus now. As well am in progress of pull requesting changes to forge to make it more likely. Until something changes I can't do much about it.

**Comment by tomdodd4598** [comment]
Is there a reason you can't look for instances of `IEnergyStorage` rather than `EnergyStorage` in the EnergySystemFE class, and use the `extractEnergy(...)` method?

**Comment by DarkGuardsman** [comment]
IEnergyStorage is the issue, its default implementation limits max output. So you end up only pulling 10k FE to 50k FE per iteration. To drain a battery fully I have to loop 1000 times for a 10M buffer resulting in a large lag spike per machine.

**Comment by tomdodd4598** [comment]
Ah yes, I see. Yep, that sounds pretty annoying :P

**Comment by DarkGuardsman** [comment]
Very, though I think I might be able to make IC2 work assuming its API is not buggy like it was in 1.7

**Comment by Dente222** [comment]
Hmm sorry for digging this topic out but what if instead of removing energy from its storage you could just change its input/output values to 0 for a fixed amount of time?

**Comment by DarkGuardsman** [comment]
that can't be accessed via the API calls

Only thing we can do with most energy systems is 

- check energy value
- check if we can receive
- check if we can extract
- give energy (limited to internal value)
- take energy (limited to internal value)

Beyond this we have no access to what the machine, item, or entity does with the internal logic. So a device could limit to 100 RF a call or 1B RF a call.
