### ISSUE TITLE
[1.12] Missile Detonation Underground/map

### ISSUE THREAD

**Issue by Zjalost** [BuiltBrokenModding/ICBM-Classic#240]
Will do further testing, I am using the most recent file for 1.12.2 and have increased the firing range. So far every missile that has been fired and simulated re spawns underground or under the map when it detonates. First time posting here so if i messed up or left any info out let me know.

**Comment by GHXX** [comment]
Hmmm, it should spawn at height 250 when it comes out of the simulation. Could you go to your mod settings -> icbm classic -> debug (icbm_classic/debug) -> set debug_missile_tracker to true
That will show you some lines to see if the missile is actually being simulated.
In your log you should see a line like this: [Netty Server IO #1/INFO] [icbmclassic]: Launching icbm.missile.icbmclassic:exothermic (368855) from -249, 7, -276 to 743, 0, -5
and then a few lines from the missiletracker that are counting down, and then you should see a line like this:
Launching icbm.missile.icbmclassic:exothermic (612363) from **743, 250, -5 to 743, 0, -5**
Missile spawned from simulator: EntityMissile['entity.icbmclassic:missile.name'/612363, l='New World - radartest', x=743.34, y=245.00, z=-4.27]

if you see them please post the second coordinate pair here (i made the important one bold up there)

**Comment by DarkGuardsman** [comment]
it could be a NaN bug similar to the other report we have like this

**Comment by GHXX** [comment]
Its only been a few days, but im going through tickets right now and closing inactive ones that require us to have additional info in order to fix them, so, if you got more info, please just comment and i can reopen the issue so we can fix this.
