### ISSUE TITLE
Rejuvenation generating seemingly random chunks when detonated

### ISSUE THREAD

**Issue by tobi-polar** [BuiltBrokenModding/ICBM-Classic#245]
Not sure what's causing the odd behaviour (unless it's intended and I don't realise) But setting the rejuvenation explosive off seems to generate a random chunk and change the biome. It will do this a few times... and then after say 2 or 3 times it will rejuvenate the same chunk, and from that point on it rejuvenates that chunk evertime. I think I read on #191 that you're going to remove it soon anyway so I'm not asking for a fix, but was curious what causes this kind of strange behaviour?

**Comment by DarkGuardsman** [comment]
Its based on world seed and the vanilla generator. So if either changes it
can result in the wrong data.

**Comment by tobi-polar** [comment]
So if for example I had a different mod handling world gen like cofh, the icbm bomb would try generating the chunk the vanilla way, causing it to look different than if cofh did it?

**Comment by DarkGuardsman** [comment]
Maybe, it will pick up on the basic modded things such as ores and trees. Its the higher end mods that will break it such as biomes++
