### ISSUE TITLE
EMP has no effect on energy blocks

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#246]
As of 1.12.2-3.3.0b65-UNSTABLE build 65, EMP won't drain any energy from Thermal Energy cells and Mekanism Energy cubes.

Thermal has a limitation that would require 2000x calls per block, so a workaround is required.
Mekanism can't work due to several issues in ICBM, fixing the below code would help:
1- https://github.com/BuiltBrokenModding/ICBM-Classic/blob/1.12/src/main/java/icbm/classic/lib/energy/system/EnergySystemFE.java#L138
=> doAction should be !doAction to actually do the action

2- https://github.com/BuiltBrokenModding/ICBM-Classic/blob/1.12/src/main/java/icbm/classic/lib/energy/system/EnergySystemFE.java#L88
=> some blocks don't accept null side, so we should try all 6 sides in addition to null here

3- https://github.com/BuiltBrokenModding/ICBM-Classic/blob/1.12/src/main/java/icbm/classic/lib/energy/system/EnergySystemFE.java#L96
=> this test is too restrictive, preventing the previous to get a chance to execute. Consider removing that part completely?

**Comment by DarkGuardsman** [comment]
I have a merge request with forge to solve this... until then nothing is happening.

**Comment by LemADEC** [comment]
the Forge PR won't fix the implementation bugs in ICBM's EnergySystemFE class. Would you like a PR for that?

**Comment by DarkGuardsman** [comment]
Not really as its all getting gutted and rewrote.
