### ISSUE TITLE
CreeperHeal

### ISSUE THREAD

**Issue by adventurer500** [BuiltBrokenModding/ICBM-Classic#248]
Hey so I am trying to use creeperheal mod with this and it works with explosives like conventional and fragmentation but not nuclear or antimatter is there a way to fix this???

**Comment by bl4ckscor3** [comment]
Unlikely to be fixed by us.

**Comment by adventurer500** [comment]
Is it possible that it is because the explosives arent coded to be explosives and rather a remove block command?

**Comment by DarkGuardsman** [comment]
Explosives are just remove block calls. No the issue is we thread a lot of
our explosives and then queue the edits to reduce lag making event calls
hard to implement without breaking other mods. It can likely be fixed but
it would have to wait until after the current API rewrite.

**Comment by adventurer500** [comment]
Ah thank you for helping me understand this issue better😀
