### ISSUE TITLE
Battery Box/ Cruise Launcher inventory issues

### ISSUE THREAD

**Issue by clienthax** [BuiltBrokenModding/ICBM-Classic#254]
blast-rewrite

Battery box makes everything in your inventory invisible, it also has another inventory screen on the bottom right that lets you delete items.

![image](https://user-images.githubusercontent.com/1056270/68435533-6bf1bd80-01b3-11ea-8788-96f8a6c8b971.png)
![image](https://user-images.githubusercontent.com/1056270/68435537-6e541780-01b3-11ea-9528-73f62a66187c.png)
![image](https://user-images.githubusercontent.com/1056270/68435581-85930500-01b3-11ea-9524-290946af3429.png)

**Comment by DarkGuardsman** [comment]
Did I even make that thing craftable?

**Comment by clienthax** [comment]
> Did I even make that thing craftable?

Battery box is not craftable, cruise launcher is.

**Comment by clienthax** [comment]
seems it could be same as https://github.com/BuiltBrokenModding/ICBM-Classic/issues/231
Will have a look once im home.

**Comment by DarkGuardsman** [comment]
Ya battery box should be removed when @bl4ckscor3 gets a chance. As for cruise launcher this is a known defect that is caused by a few other mods. We can fix it on our side but its been hard to track down.

**Comment by clienthax** [comment]
Seems to be of been resolved by the GLStateManager commit

**Comment by bl4ckscor3** [comment]
Good, that was my hunch.

**Comment by GHXX** [comment]
Merged blast-rewrite into 1.12
