### ISSUE TITLE
[1.12.2] Explosive doesn't damage world or player

### ISSUE THREAD

**Issue by JustGoku** [BuiltBrokenModding/ICBM-Classic#260]
The missile just blow up as expected, but as if explosions were disabled.
Vanilla and other tnt such as Industrial TNT works fine

**Comment by bl4ckscor3** [comment]
Which explosive?

**Comment by JustGoku** [comment]
[16:34:38] [Netty Local Client IO #1/ERROR] [icbmclassic]: icbm.classic.lib.network.ex.PacketTileReadException: Null tile

All of them, got this error in console

**Comment by bl4ckscor3** [comment]
It may be that this is already fixed in the rewrite, but please send the complete log anyways.

**Comment by border999** [comment]
where is that rewrite?

**Comment by bl4ckscor3** [comment]
https://github.com/BuiltBrokenModding/ICBM-Classic/tree/blast-rewrite

**Comment by GHXX** [comment]
Closing this one because there is way too little info to be able to look into it unfortunately. 
Missiles right now seem to work just fine. Feel free to comment if more info is available.
