### ISSUE TITLE
All missiles target correctly but explode at 0 0 0 (1.12.2)

### ISSUE THREAD

**Issue by CyberShroom** [BuiltBrokenModding/ICBM-Classic#262]
Everytime I fire ANY missile at any location, the missile will fire like normal and travel in the direction of the target. When it reaches the target, it will hit the target. However, instead of an explosion/sound/animation/projectile, it disappears and does nothing. I turned on all the debug options via config and found that when it hits the target, the explosion appears at 0 0 0 instead of target cords. When I tp there, the entire underground area is a crater from all the explosions. This was on a server using custom chosen mods and I tried a variety of different ways to see if I could find a way to get the missiles to work properly. I even went to singleplayer and it still didn't work. Meaning that the mod is not working properly on both client and server side. This is bad since the server im running is all about war and diplomacy and not being able to use missiles ruins the fun. I would love to know if there is a work around of some sort or if Im able to change some setting that would fix the issue at least on the server side until the bug is officially fixed in a future update.

Also it might be important to mention that the mod worked fine in the previous version of the custom pack I was running. Missiles worked fine in that version but then I gave the pack a major update (increasing the mod count from 68 to 100 basically) and then they stopped working. But a lot of other things happened during the update to me finding the bug so Im not 100% sure if the pack update caused the bug or if switching server hosts and ips caused it.

Another bug I found was that the launchers like to rename themselves to tier 1 as well as the control panels and launch supports. Don't know if this is an already known bug or if it might have something to do with the bug im facing. They rename themselves tier 1 but keep the properties and textures of what they actually are. When mined, they turn back to tier 2/3.

**Comment by CyberShroom** [comment]
Update:
I think I figured it out.
When I targeted a missile at a different cord, it went off.
any other coordinates will cause an explosion but for some reason the original cords of my test site would force the explosion at 0 0 0.
the cords I used when the bug occurred were -1333 74 -2696
it seems like perhaps theres an error in the code that if a certain area of cords is chosen as a target, the missile will hit but explode at 0 0 0.
I thought I saw another post about the 0 0 0 thing, and that guys cords were similar to mine.
I'm not able to test what the size of the 'bug zone' is since the more time I take testing the bug, the farther along my opponents will get on the server but ill just let them know not to build a base on that mountain.

**Comment by GHXX** [comment]
Might be related to #210 
You said that you enabled all debug options, could you post the corresponding output log if you still got that?

**Comment by GHXX** [comment]
Just tested it using the blast-rewrite branch, and the missile flew correctly to the target position. So this may be fixed.

**Comment by Tommeh1** [comment]
Tested with the blast rewrite(ICBM-classic-1.12.2-4.0.0b20200101191300.jar), seems to be fixed, re-open the issue if it still occurs
