### ISSUE TITLE
[1.12.2] "Insufficient Power"

### ISSUE THREAD

**Issue by TacticalTux** [BuiltBrokenModding/ICBM-Classic#271]
With a T3 setup, using Mekanism wires (tried fluxducts as well), I am unable to get power to the machine. I am using a Creative Power Cube, and it still reports not having enough power.
https://imgur.com/a/634tO2B

The version number is 1.12.2-4.0.0.20191109044626

**Comment by HydrogenC** [comment]
+1

**Comment by bradyrussell** [comment]
I appear to be having this issue with IC2 wires in ICBM-classic-1.12.2-4.0.0b70.

At first it would  draw power properly but after a few launches it stops drawing power.

**Comment by AzazelMango** [comment]
Use the energy converters mod and use the FE producer module.
