### ISSUE TITLE
Redmatter exception trying to write state

### ISSUE THREAD

**Issue by Tommeh1** [BuiltBrokenModding/ICBM-Classic#273]
Although the red matter appears to save correctly(It still exists after reloading a save etc) it does throw this error in the logs: https://pastebin.com/64ZuCYzF

Used ICBM version: Self-build until this commit: https://github.com/BuiltBrokenModding/ICBM-Classic/commit/2a19265f64c18aed84a1745876706ed829628721

**Comment by GHXX** [comment]
This may have been fixed in commit 9c6db8eaff4869223198c7a476beeae2a2f2dc17
Could you re-test it, including this commit?
(stacktrace is very similar to #346)
