### ISSUE TITLE
/icbm lag doesn't kill active antimatter blast

### ISSUE THREAD

**Issue by Tommeh1** [BuiltBrokenModding/ICBM-Classic#274]
Whenever an antimatter explosion is being processed /icbm lag is unable to stop it.

Used ICBM version: Self-build until this commit: https://github.com/BuiltBrokenModding/ICBM-Classic/commit/2a19265f64c18aed84a1745876706ed829628721

**Comment by DarkGuardsman** [comment]
That is due to the antimatter completed instantly, any lag from it is the world loading the changes.
