### ISSUE TITLE
EMP tower wont switch to Disrupt missiles.

### ISSUE THREAD

**Issue by BlueYoshi68** [BuiltBrokenModding/ICBM-Classic#277]
As the title says, for whatever reason, every time i click missiles in the EMP tower it just goes back to electronics.

**Comment by GHXX** [comment]
What mod and minecraft version are you using?

**Comment by BlueYoshi68** [comment]
Forge 14.23.5.2846
ICBM 1.12.2-4.0.0.70

**Comment by Tommeh1** [comment]
Can confirm while using a custom build until this commit: https://github.com/BuiltBrokenModding/ICBM-Classic/commit/2a19265f64c18aed84a1745876706ed829628721

**Comment by GHXX** [comment]
Fixed it in dev environment.
