### ISSUE TITLE
Explosives turn into condensed explosives when unable to leave flying block state correctly

### ISSUE THREAD

**Issue by Tommeh1** [BuiltBrokenModding/ICBM-Classic#278]
Whenever an explosive becomes a flying block but tries to turn back into a static block while it's either inside of another block or there is an entity in the way it will become a condensed explosive.

Used ICBM version: Self-build until this commit: https://github.com/BuiltBrokenModding/ICBM-Classic/commit/2a19265f64c18aed84a1745876706ed829628721

**Comment by GHXX** [comment]
does it turn back into the correct one if you apply a block update, or does it stay?

**Comment by Tommeh1** [comment]
> does it turn back into the correct one if you apply a block update, or does it stay?

It stays this way

**Comment by DarkGuardsman** [comment]
considering condensed was like ID 0... its a save bug and is likely fixed in the new version
