### ISSUE TITLE
Missiles turn nearby entities darker

### ISSUE THREAD

**Issue by Tommeh1** [BuiltBrokenModding/ICBM-Classic#279]
When a missile is either near the player or near an entity(can't tell which one of these 2) nearby entities will appear darker than usual.

Used ICBM Version: Self-build until this commit: https://github.com/BuiltBrokenModding/ICBM-Classic/commit/2a19265f64c18aed84a1745876706ed829628721

**Comment by DarkGuardsman** [comment]
Need more details... aka screenshots

**Comment by Tommeh1** [comment]
Seems like this one has been fixed in the meanwhile as i can no longer reproduce it with the latest alpha
