### ISSUE TITLE
Can't find the camouflage block

### ISSUE THREAD

**Issue by SWJN5** [BuiltBrokenModding/ICBM-Classic#281]
I have been playing with this mod and I see that the old camo blocks are meant to be in it but they don't seem to be in the creative menu or in JEI. Is it actually in the 1.12.2 version?

**Comment by DarkGuardsman** [comment]
They were not ported when we did the 1.12 update due to complexities with MC rendering. The plan is to eventually update them as a SBM mod. However, due to how low priority the feature was it has fallen behind due to working on the core features.

**Comment by SWJN5** [comment]
ok thanks just could u maybe remove it from the feature list on the curse forge page?

**Comment by DarkGuardsman** [comment]
I will when its officially removed, as we still have it in older versions.
