### ISSUE TITLE
OpenComputers integration

### ISSUE THREAD

**Issue by Alainx277** [BuiltBrokenModding/ICBM-Classic#285]
Seeing as Computercraft is not officially developed anymore, it seems wise to integrate the most up-to-date computer mod.
[Here's a simple driver example](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.12/src/main/scala/li/cil/oc/integration/minecraft/DriverNoteBlock.scala), which allows access to the vanilla noteblock.
It would be really amazing to have a fully automated missile system.

**Comment by GHXX** [comment]
It would indeed be nice to have, feel free to submit a pull request for it, if you got working code.

**Comment by DarkGuardsman** [comment]
Support will need to be added as an addon rather than built into the mod directly.  As I do not want to delete code each time we move MC versions and OC doesn't update fast enough to keep the support.

**Comment by GHXX** [comment]
Even though we do not officially support it, there is a 3rd party icbm-oc-addon now for 1.12 which should work for you: 
https://www.curseforge.com/minecraft/mc-mods/opencomputers-icbm-classic-addon/files/2913483
