### ISSUE TITLE
CubicChunks Compatibility

### ISSUE THREAD

**Issue by sa-shiro** [BuiltBrokenModding/ICBM-Classic#288]
ICBM used to work with CubicChunks with some bugs, but now with latest update, no explosions are possible outside of vanilla range.

My request is to add CC support so we can have fun below and above vanilla range xD

**Comment by DarkGuardsman** [comment]
We don't support CubicChunks due to how much it changes the base game and amount of time it takes to support. Anyone is welcome to pull request changes for support but we need to focus on fixing the base mod for the base game at this time.
