### ISSUE TITLE
missiles gets stuck [1.7.10]

### ISSUE THREAD

**Issue by jumpjetPL** [BuiltBrokenModding/ICBM-Classic#289]
i sent missile with laser designator for about 2000 block, chunks where t3 launch platform is located 
is force loaded by dimensal anchor, (im using ICBM-classic-1.7.10-2.16.2b205 ) i had message on chat that missile has been sent but never come :(

**Comment by johonggnJA** [comment]
I also have this issue, when I rode the rocket by right-clicking it and traveled with it the whole way it worked. I think it is definitely a chunk loading issue where it gets stuck as it enters the first unloaded chunk. I read the 1.1.12 version it removes it if you put the lock-on height at 255 or above but it didn't fix it for me. Was also roughly 2400 blocks.

**Comment by GHXX** [comment]
the lock height doesnt matter much in this perspective given that the launch area is chunkloaded.
in 1.7.10 the whole misisle flight path needs to be chunkloaded. 
in 1.12.2 only the launch area needs to be loaded.
thats because the flight path is simulated and the impact area is loaded automatically.

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.

That being said, if you got further questions, feel free to comment.

**Comment by johonggnJA** [comment]
I do, how do I launch a missile from my base to another base 2000 blocks away. Do I have to ride it? If I ride the first but launch 4 at the same time should the chunks I load while riding keep the other misssiles from getting stuck.

**Comment by GHXX** [comment]
In 1.7 you have to either ride it, or follow it some other way to load the chunks, yes.
In 1.12 only the launch area needs to be loaded

**Comment by jumpjetPL** [comment]
its been long time since i looked here, but im here to say that if you using 1.7.10 you beter install defense tech i used voltz engine things on my modpack so i had to leave ibcm classic in modpack but i deactivated it, i even created custom emc file for defense tech now i dont see any problems with chunkloading itp, one rocket flew 3000m to my friend base and he was very suprised that i somehow fixed it

**Comment by johonggnJA** [comment]
Could you share the emc doc with me please? I really appreciate the advice.

**Comment by jumpjetPL** [comment]
yeah sure :) https://drive.google.com/open?id=1TyVaKITAQ88aYqGk6DNL5tjfetAw3HhH
i gave unlimited emc to antimatter and nomatter becouse they are uncraftable, also if u enable cheats on minecraft world u can set emc to anything you hold in hand
