### ISSUE TITLE
1.12: EntityGrenade#hasCapability infinite loop

### ISSUE THREAD

**Issue by Joey-Destroyah** [BuiltBrokenModding/ICBM-Classic#293]
@DarkGuardsman

When I try to throw a grenade, it doesn't work. When i use a dispenser, it crashes. 

Modlist: LucraftCore heroesexpansion, anvil infinity craft. ichunutil, opencomputers, Icbm beta, Gravity gun, and techguns on 1.12.2 forge.

Please fix the bug. 

-Joey

Here is the crash report:

---- Minecraft Crash Report -------- Minecraft Crash Report ----
WARNING: coremods are present:  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.9 (6).jar)  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)Contact their authors BEFORE contacting forge
// Don't do that.
Time: 3/28/20 7:02 PMDescription: Exception while ticking a block
java.lang.StackOverflowError: Exception while ticking a block at icbm.classic.content.entity.EntityGrenade.hasCapability(EntityGrenade.java:321) at icbm.classic.content.entity.EntityGrenade.hasCapability(EntityGrenade.java:321) at icbm.classic.content.entity.EntityGrenade.hasCapability(EntityGrenade.java:321) at icbm.classic.content.entity.EntityGrenade.hasCapability(EntityGrenade.java:321) at icbm.classic.content.entity.EntityGrenade.hasCapability(EntityGrenade.java:321) at icbm.classic.content.entity.EntityGrenade.hasCapability(EntityGrenade.java:321) at icbm.classic.content.entity.EntityGrenade.hasCapability(EntityGrenade.java:321) at icbm.classic.content.entity.EntityGrenade.hasCapability(EntityGrenade.java:321) at icbm.classic.content.entity.EntityGrenade.hasCapability(EntityGrenade.java:321) at 

etc.

 

 

-- Block being ticked --Details: Block: minecraft:dispenser[facing=west,triggered=true] Block location: World: (1643,52,-586), Chunk: (at 11,3,6 in 102,-37; contains blocks 1632,0,-592 to 1647,255,-577), Region: (3,-2; contains chunks 96,-64 to 127,-33, blocks 1536,0,-1024 to 2047,255,-513)Stacktrace: at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:742) at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) at java.lang.Thread.run(Thread.java:745)
-- Affected level --Details: Level name: New World All players: 1 total; [EntityPlayerMP['Joseph_da_IT_Guy'/3, l='New World', x=1641.11, y=52.00, z=-585.66]] Chunk stats: ServerChunkCache: 369 Drop: 0 Level seed: 3789110629297299985 Level generator: ID 01 - flat, ver 0. Features enabled: true Level generator options: 3;minecraft:bedrock,50*minecraft:dirt,minecraft:grass;1;village Level spawn location: World: (1652,4,-494), Chunk: (at 4,0,2 in 103,-31; contains blocks 1648,0,-496 to 1663,255,-481), Region: (3,-1; contains chunks 96,-32 to 127,-1, blocks 1536,0,-512 to 2047,255,-1) Level time: 46063 game time, 2369 day time Level dimension: 0 Level storage version: 0x04ABD - Anvil Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false) Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
-- System Details --Details: Minecraft Version: 1.12.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_51, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 474745616 bytes (452 MB) / 1610612736 bytes (1536 MB) up to 2147483648 bytes (2048 MB) JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP 9.42 Powered by Forge 14.23.5.2838 16 mods loaded, 16 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
| State  | ID                             | Version         | Source                                  | Signature                                | |:------ |:------------------------------ |:--------------- |:--------------------------------------- |:---------------------------------------- | | LCHIJA | minecraft                      | 1.12.2          | minecraft.jar                           | None                                     | | LCHIJA | mcp                            | 9.42            | minecraft.jar                           | None                                     | | LCHIJA | FML                            | 8.0.99.99       | forge-1.12.2-14.23.5.2838.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 | | LCHIJA | forge                          | 14.23.5.2838    | forge-1.12.2-14.23.5.2838.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 | | LCHIJA | opencomputers|core             | 1.7.5.192       | minecraft.jar                           | None                                     | | LCHIJA | techguns_core                  | 1.12.2-1.0      | minecraft.jar                           | None                                     | | LCHIJA | ichunutil                      | 7.2.2           | iChunUtil-1.12.2-7.2.2 (2).jar          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 | | LCHIJA | gravitygun                     | 7.1.0           | GravityGun-1.12.2-7.1.0 (1).jar         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 | | LCHIJA | lucraftcore                    | 1.12.2-2.4.9    | LucraftCore-1.12.2-2.4.9 (6).jar        | None                                     | | LCHIJA | heroesexpansion                | 1.12.2-1.3.5    | HeroesExpansion-1.12.2-1.3.5 (5).jar    | None                                     | | LCHIJA | icbmclassic                    | 1.12.2-4.0.0.74 | ICBM-classic-1.12.2-4.0.0b74.jar        | None                                     | | LCHIJA | infinity                       | 1.10            | infinity-1.10 (7).jar                   | None                                     | | LCHIJA | lightningcraft                 | 2.9.7_1         | lightningcraft-2.9.7_1.jar              | None                                     | | LCHIJA | opencomputers                  | 1.7.5.192       | OpenComputers-MC1.12.2-1.7.5.192.jar    | None                                     | | LCHIJA | eternalsoap.icbm.opencomputers | 1.0             | OpenComputersICBMAddon-MC1.12.2-1.1.jar | None                                     | | LCHIJA | techguns                       | 2.0.2.0         | techguns-1.12.2-2.0.2.0_pre3.1.jar      | None                                     |
Loaded coremods (and transformers): TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)  li.cil.oc.common.asm.ClassTransformerLucraftCoreCoreMod (LucraftCore-1.12.2-2.4.9 (6).jar)  lucraft.mods.lucraftcore.core.LCTransformerTechguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)  techguns.core.TechgunsASMTransformer GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread. Profiler Position: N/A (disabled) Player Count: 1 / 8; [EntityPlayerMP['Joseph_da_IT_Guy'/3, l='New World', x=1641.11, y=52.00, z=-585.66]] Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DarkGuardsman** [comment]
Commit 52b55a518b469b13b49b0c9aca4ce2b1b804a0f0 should fix it
