### ISSUE TITLE
Tracker not a functional item... Yet?

### ISSUE THREAD

**Issue by Erosion139** [BuiltBrokenModding/ICBM-Classic#298]
The tracker doesn't do what it says it can do. Read somewhere that it was not implemented yet in 1.12.2, or the 1.7.10 version this is based off. Quite frustrated about it because I thought my genius idea to find my friends secret base was to use this very item but would ya look at that its a completely nonfunctional paperweight!

**Comment by Joey-Destroyah** [comment]
Same with me.

**Comment by GHXX** [comment]
The tracker item, along with the homing missile will be removed in future versions since it is considered OP by us.

You might be able to get away with giving him a tablet computer from cctweaked or opencomputers or something. Not sure. Be creative!

**Comment by Erosion139** [comment]
Alright thank you. Keep up the good work! Found an alternative by sticking a tracker from wireless redstone CBE. Although a bit glitchy. I think it will do the job.
