### ISSUE TITLE
Redmatter rendering issues

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#30]
As of ICBM-classic-1.7.10-2.15.1b37-universal, the 3rd red matter explosion had no 'black' sphere.
After adding a 4th, it was glitching my client window with a intermittent translation offset (bottom left corner rendering almost at center of screen).
It was only a translation of the view, including GUI elements.
There was also lots of white flashes.
3rd and 4rd red matter were flying in a large circle, I was on the border of it, maybe they were passing through me too fast to render?

1st and 2nd red matter went flying high away earlier, so they were probably still active at that time.

**Comment by DarkGuardsman** [comment]
Not sure what your on about so a screenshot could help.

From what I do understand it sounds like velocity rendering glitches?

As well I think I need to re-add redmatter merging to fix the collision render issue.

**Comment by LemADEC** [comment]
According to MC Edit, there was still 4 ProceduralExplosion and 913+ GravityBlocks in the area.

It was going pretty fast and I've crashed shortly after. I'll try to reproduce later on.

**Comment by DarkGuardsman** [comment]
Ok, when you do try to take screenshots or even better record it as it happens. This way I better understand what happened. If you can't do either of those tell me how you managed to get it to happen. That way I can follow the same steps to see the same rendering issues.

**Comment by LemADEC** [comment]
This was the same session that lead to the crash in #29 with low video settings:
![image](https://cloud.githubusercontent.com/assets/4776032/22993631/eeff6c3c-f3c3-11e6-85c7-e78650aa6fea.png)

With DefenseTech:
1- The missing black sphere is intermittent, it seems related to EvilCraft vengeance spirits orbiting around the RedMatter. Those are transparent versions of recently dead entities.

2- Some entities from Advent Of Ascension (nevermine2) appears to resist the Red Matter wrath and keep oscillating around the explosion. It's kinda fun and inconsistent at the same time:
![image](https://cloud.githubusercontent.com/assets/4776032/22994126/02a8e554-f3c6-11e6-9d5b-f0de5336728a.png)

3- I can't reproduce the offset glitch so far.

**Comment by LemADEC** [comment]
With ICBM-Classic:
1- The black sphere is always present when Vengeange spirits are orbiting it. The black sphere is still missing depending on time and where I'm looking at, still not sure which block or entity is triggering it.

2- The mob entities appears to hover below the explosion instead of orbiting it like DefenceTech does. The Glistering pixon are surviving, no difference here.

3- Offset glitch is reproduced. It's probably related with the flying blocks creation:
3.1: glitch stops when RedMatter no longer break new blocks
3.2: glitch is reproduced when antigrav explosion is starting

Capture just before the glitch:
![image](https://cloud.githubusercontent.com/assets/4776032/22996053/a65d0bb0-f3cd-11e6-9896-95701d622edb.png)
Capture with the glitch:
![image](https://cloud.githubusercontent.com/assets/4776032/22996060/b024785e-f3cd-11e6-935c-5fbc887363e8.png)
The offset is also horizontal every now and then, just couldn't capture it.

Those are confirmed also on ICBM-classic-1.7.10-2.15.1b45-universal

**Comment by LemADEC** [comment]
To summarize:
A- Entities are falling instead of orbiting the RedMatter explosion => #31

B- Black sphere isn't always rendering, not sure what's trigerring it yet. => this issue

C- Some parts of the GUI is offset when FlyingBlocks are created. =>  this issue

**Comment by DarkGuardsman** [comment]
GUI might be an overflow error of some kind, the render code has a lot of crash preventers that do not clean up well.

I can most likely fix the entity issue here soon but the render issue is going to take a while. It is most likely an openGL issue that might not be fixable. The best thing I can think of is to kill entities before they get in the center. This way the issue does not happen.

**Comment by LemADEC** [comment]
Which entities you want to kill?

**Comment by DarkGuardsman** [comment]
Any entity being sucked into the redmatter, since I think the clipping or z fighting is the issue. 

That being said I think I might have fixed it in the latest as I did fix two issues with the flying block renderers causing display bugs.

**Comment by DarkGuardsman** [comment]
Should be fixed now
