### ISSUE TITLE
Missile lagged

### ISSUE THREAD

**Issue by joanros97** [BuiltBrokenModding/ICBM-Classic#307]
Hi, I'm using ICBM-classic-1.12.2-3.3.0b63 on my 1.12.2 sponge server (7.1.6 forge version) and I have the following problem:

Every time I launch a missile with the launch platform, the missile start flying back and forwards (like lagged) and it flies really slow. If a player in creative mode go near this launched missile, then it travels fast. I know that this is not server lag as everything goes normally and we have 30ms, so it's mod problem.

I don't know if this problem can be solved changing something on the config files (mod, server properities, sponge config...) but I think I'm not the only one that have this problem (I didn't find anything on the forums). 

How to recreate:

1: place the platform with the missile (and everything needed to make a missile launch)
2: use the lever to launch the missile
3: look how the missile goes back and forward

**Comment by GHXX** [comment]
It might be a Sponge issue, not sure, but it may be related to #158

**Comment by Harchvertelol** [comment]
I confirm that the sponge gives such an effect. What sponge settings do you need to change in order for the mod to work?

**Comment by Harchvertelol** [comment]
Maybe, you can attached to missile fictive-ghost-player? Like world anchor from railcraft (maybe ic2).

**Comment by GHXX** [comment]
amrailcraft anchor only serves as a chunkloader as far as i know, and after the launch is finished, the missile is removed from the world and then spawned back in afer some time depending on the travel distance to avoid having to chunkload it.
so i dont think a world anchor would do much

**Comment by Harchvertelol** [comment]
But why then does having a player make the rocket fly on? In this case, a dummy player can help (it seems to me).

**Comment by joanros97** [comment]
Thanks for the info. I don't know how to do that dummy player (maybe a script or something, I don't know) but it's a solution that I don't want to implement on my server. I tested your mod on a "Magma" server (a "new" software for servers) and the missiles work perfectly, with 0 lag or errors. 

I will try to move my server to Magma, as Sponge give a lot of problems, and don't have so much plugins. If my proces of changing the server to Magma fails, and I have to continue on Sponge, I will notify it here to try to solve this problem. 

Again, thank you to both of you for your help.

**Comment by GHXX** [comment]
@Harchvertelol my guess is that sponge does some optimizations, like ticking the entity less or some shenanigans when no player is nearby, but thats just a wild guess.

**Comment by clienthax** [comment]
See https://github.com/SpongePowered/SpongeForge/issues/3136 for fix.
