### ISSUE TITLE
insufficient power t3 controller

### ISSUE THREAD

**Issue by W4RxTHExLEGEND** [BuiltBrokenModding/ICBM-Classic#313]
I have galacticraft aluminium wire hooking a mekanism nuclear reactor to my t3 icbm setup. The t1 and t2 seem to have the power they need to launch, but t3 says insufficient power. I have tried a FE producer and it doesn't help at all.

**Comment by W4RxTHExLEGEND** [comment]
This is on The 1.12.2 Pack with ICBM-CLASSIC

**Comment by DarkGuardsman** [comment]
Get more power or change the required power in the config.

**Comment by W4RxTHExLEGEND** [comment]
How much power and what type is required?

**Comment by DarkGuardsman** [comment]
No idea off the top of my head, but it should be listed in the configs.

Like all mods it supports Forge Energy which means it should work with mekanism, thermal expansion, buildcraft, etc. IC2 power is also supported by tends to break a lot.
