### ISSUE TITLE
Russian Language bug

### ISSUE THREAD

**Issue by DarkShyMW** [BuiltBrokenModding/ICBM-Classic#315]
![image](https://user-images.githubusercontent.com/30442729/81454469-12d00a00-9195-11ea-8fd1-7fd740b4493d.png)
I have some troubles.. please help

**Comment by DarkShyMW** [comment]
and all ICBM-GUI have this problem

**Comment by bl4ckscor3** [comment]
I believe we fixed an issue like this already. Try updating the mod.

**Comment by DarkShyMW** [comment]
I was download latest version 3 hours ago.
