### ISSUE TITLE
Ic2 experimental crafting issue

### ISSUE THREAD

**Issue by thekydon** [BuiltBrokenModding/ICBM-Classic#317]
Ive come across an issue where its impossible to craft a nuclear bomb with Ic2 experimental since its asking for refined uranium that does not exist, while I found this post (https://github.com/BuiltBrokenModding/ICBM-Classic/issues/156) which discusses the same issue and suggests using either uranium 235 or 238 in refined uraniums place, however this still doesn't work. Is there anything obvious that I am missing or is there anywhere in the mod where I can change the recipe myself?

Thanks.

**Comment by DarkGuardsman** [comment]
You should be able to use any standard crafting adjustment mod to fix it. Once we get things sorted with the rework i'll take a look at IC2 support again.

**Comment by thekydon** [comment]
Nice, got it working. Thanks for the help mate

**Comment by GHXX** [comment]
awesome!
