### ISSUE TITLE
Unexpected packet during modded negotiation | console spam

### ISSUE THREAD

**Issue by HonzaVinCZ** [BuiltBrokenModding/ICBM-Classic#318]
Hey, I was trying latest 1.12.2 alpha version and I'm getting spam in console of Unexpected packet during modded negotiation - assuming vanilla or keepalives.
It happens just after creating new world. After a while world shuts down. 
Here's log:
[latest.log](https://github.com/BuiltBrokenModding/ICBM-Classic/files/4640790/latest.log)

**Comment by GHXX** [comment]
Is there any reason why you suspect that its icbm's fault?

**Comment by HonzaVinCZ** [comment]
> Is there any reason why you suspect that its icbm's fault?

Yes, the beta version works fine without any spams like that. If I can help bring more info somehow just tell me what you need to know.

**Comment by GHXX** [comment]
hm we changed quite a lot since the last beta version, but im assuming @DarkGuardsman would need to take a look.

**Comment by HonzaVinCZ** [comment]
> hm we changed quite a lot since the last beta version, but im assuming @DarkGuardsman would need to take a look.

Okay, btw thanks for improving and keeping this mod alive, it's really great mod and I can see many improvements in latest alpha compared to beta. 
Good luck!

**Comment by Tommeh1** [comment]
I saw a SPacketEntityTeleport in there, i don't think ICBM uses that, my best guess is Vic's Modern Warfare Mod
