### ISSUE TITLE
1.12.2 Tracking Issue

### ISSUE THREAD

**Issue by Staqur** [BuiltBrokenModding/ICBM-Classic#319]
Not sure if trackers are still supposed to lock on to homing missiles, they don't for 1.12.2

When tracking a player on 1.12.2 (I believe the tracker is supposed to point in the direction of the player when you track them) That doesn't work also

**Comment by GHXX** [comment]
Trackers and homing missiles were removed because they didnt work properly / were too op. Not sure if we will add them back in a future version, but for now they are gone, sorry!
(They might still be in the latest Release version, but they are definitely gone in the 4.x.x alpha)
