### ISSUE TITLE
Polish translation for ICBM classic

### ISSUE THREAD

**Issue by michasrutek** [BuiltBrokenModding/ICBM-Classic#321]
I have translated this mod into Polish.
[pl_PL.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/4674065/pl_PL.txt)

**Comment by DarkGuardsman** [comment]
If you make this in to a pull request I can merge it.

**Comment by GHXX** [comment]
Ill close this for now, @michasrutek feel free to submit this as a pullrequest.
