### ISSUE TITLE
Remote Detonator not functioning as intended?

### ISSUE THREAD

**Issue by RaiRaiTheRaichu** [BuiltBrokenModding/ICBM-Classic#323]
The remote detonator does not seem to want to sync up to any placed explosives such as a breaching charge. Shift+Right click does not sync the detonator to the explosive, and right clicking the explosive also does nothing.

You can right click a Tier 3 terminal, however, and it syncs the frequency (like a laser designator) and then right clicking provides the chat output that a missile is being fired at those coordinates. It seems as if the remote detonator is functioning identically to the laser designator.

Using ICBM-classic-1.12.2-4.0.1b75.jar

**Comment by GHXX** [comment]
Would need to double check what the original plan was for the remote detonator, but it might just be a simpler version of the laser designator.
Laser designator lets you call a missile in on the position you click on.
Remote detonator only launches the missile to the coordinates that are filled in already.

Remotely detonating explosives is probably something we should support though.

**Comment by RaiRaiTheRaichu** [comment]
I see, thank you for the clarification! I understand this may be a super outdated page and/or unrelated, but this was where the confusion of its use stemmed from:

https://voltz.fandom.com/wiki/Remote_Detonator

Apologies if that wiki page doesn't apply at all to this mod (ICBM vs ICBM Classic, old 1.7.10 version, etc), just made the assumption that it worked similarly. 

Glad to hear that you'd look into remote detonation though, would be massively useful!

**Comment by GHXX** [comment]
Well, icbm and icbm classic are the same thing. Long story.
But for 1.12 we removed some stuff like homing missiles. And we reworked some stuff (and still are).
Currently the remote detonator does not set off explosives, i think we'll add that in the future though.

**Comment by DarkGuardsman** [comment]
Honestly the remote explosive feature has not been a thing for a few years now. It is possible I will add it back but its a low priority compared to fixing things like the redmatter.
