### ISSUE TITLE
Nuclear explosives won’t work on a forge server and we installed atomic craft

### ISSUE THREAD

**Issue by asianchinaboi** [BuiltBrokenModding/ICBM-Classic#324]
The recipe of the nuclear explosives is glitched and shows this.
![image](https://user-images.githubusercontent.com/67562117/85959162-0d957b80-b9de-11ea-8113-427d86fe2e6d.jpg)
We tried this recipe and it didn’t work so we used atomic craft hoping it will work which still didn’t. Please help

**Comment by GHXX** [comment]
Very odd, what icbm version are you using?
And since icbm should be using the ore dictionary item 'ingotUranium', make sure Atomiccraft adds that. 
Installing Extreme Reactors or Industrialcraft2 should definitely fix that.

**Comment by GHXX** [comment]
Ill mark this as closed for now, due to inactivity. If there is any updates on this, feel free to comment. If the issue persists, i can reopen this ticket.

**Comment by asianchinaboi** [comment]
Its been fixed we just added a villager that accepts uranium and the four bombs for a nuclear bomb

**Comment by GHXX** [comment]
Alright, just out of curiosity, what version of ICBM were you using exactly?
