### ISSUE TITLE
Mobs missing from pack

### ISSUE THREAD

**Issue by KPhoenixX** [BuiltBrokenModding/ICBM-Classic#325]
I'm using the latest version of this modpack, and the mobs are entirely absent. I checked all the changelogs and there appears to be no mention whatsoever of their removal. Is this a bug? My server gave me a notice that there were missing entities from the world after updating this mod.

**Comment by GHXX** [comment]
What mobs? And please send us the error log, and what was your old version?

**Comment by GHXX** [comment]
If you are talking about mobs like monsters holding a rocket launcher, yeah we removed them ages ago.

**Comment by dmodoomsirius** [comment]
maybe the rockets. they are entities not mobs.

**Comment by GHXX** [comment]
Very old icbm versions had actual mobs. The @br1c definitely needs to clarify that.

**Comment by KPhoenixX** [comment]
My bad. The creeper, skeleton, and zombie that use ICBM weapons

**Comment by GHXX** [comment]
Those mobs were removed a while ago. I dont think there are plans to bring them back currently.

**Comment by DarkGuardsman** [comment]
Oh they are coming back, just not as part of ICBM. I only added them as an XMAS event thing with no plan of keeping them in the mod forever. Before I hit my current break on modding the plan was to make it a mod by itself. This way people could selectively install the content.
