### ISSUE TITLE
language file

### ISSUE THREAD

**Issue by ghui9087** [BuiltBrokenModding/ICBM-Classic#326]
chinese language file could not read it was all wrong

**Comment by GHXX** [comment]
I believe nobody of the devteam speaks chinese, if you do, feel free to submit a fixed version via a pullrequest

**Comment by ghui9087** [comment]
ok thank you
this the zh_CN.lang file
the code!


itemGroup.ICBM=ICBM

children=zh_TW,

## Items
item.sulfur.name=硫磺
item.poisonPowder.name=poisonPowder
item.antidote.name=antidote
item.radarGun.name=雷达枪
item.remoteDetonator.name=remoteDetonator
item.defuser.name=拆弹器
item.laserDesignator.name=激光指示器
item.tracker.name=生物绑定器
item.signalDisrupter.name=信号破坏者

item.bullet.0.name=???\u666E\u7528\u6027\u5B50\u5F48???_bullet0
item.bullet.1.name=???\u53CD\u7269\u8CEA\u5B50\u5F48???_bullet1
item.launcher.name=???\u706B\u7BAD\u7B52???_launcher

## ICBM Machines
icbm.machine.0.name=\u767C\u5C04\u53F0T1_machine0
icbm.machine.1.name=\u767C\u5C04\u53F0T2_machine1
icbm.machine.2.name=\u767C\u5C04\u53F0T3_machine2
icbm.machine.3.name=\u63A7\u5236\u7CFB\u7D71T1_machine3
icbm.machine.4.name=\u63A7\u5236\u7CFB\u7D71T2_machine4
icbm.machine.5.name=\u63A7\u5236\u7CFB\u7D71T3_machine5
icbm.machine.6.name=\u652F\u63F4\u6846T1_machine6
icbm.machine.7.name=\u652F\u63F4\u6846T2_machine7
icbm.machine.8.name=\u652F\u63F4\u6846T3_machine8
icbm.machine.9.name=\u96F7\u9054\u53F0_machine9
icbm.machine.10.name=\u78C1\u66B4\u5854_machine10
icbm.machine.12.name=\u5DE1\u822A\u767C\u5C04\u5668_machine12

## ICBM Explosives

## Block Form
icbm.explosive.condensed.name=壓縮性炸藥
icbm.explosive.shrapnel.name=散彈性炸藥
icbm.explosive.incendiary.name=燃燒性炸藥
icbm.explosive.chemical.name=化學性炸藥
icbm.explosive.anvil.name=砧炸藥
icbm.explosive.repulsive.name=抗拒性炸藥
icbm.explosive.attractive.name=吸引性炸藥

icbm.explosive.fragmentation.name=碎片性炸藥
icbm.explosive.contagious.name=傳染性炸藥
icbm.explosive.sonic.name=音波炸彈
icbm.explosive.breaching.name=違反性炸藥
icbm.explosive.rejuvenation.name=治療性炸藥
icbm.explosive.thermobaric.name=溫壓性炸藥

icbm.explosive.nuclear.name=核彈
icbm.explosive.emp.name=EMP磁暴彈
icbm.explosive.conflagration.name=燃烧彈
icbm.explosive.endothermic.name=吸熱性炸藥
icbm.explosive.antiGravitational.name=反地心吸力炸彈
icbm.explosive.ender.name=瞬移彈
icbm.explosive.hypersonic.name=超音波彈

icbm.explosive.antimatter.name=反物質炸彈
icbm.explosive.redMatter.name=紅物質炸彈

icbm.explosive.sMine.name=S型地雷

## Missile Form
icbm.missile.condensed.name=普用式導彈
icbm.missile.shrapnel.name=散彈導彈
icbm.missile.incendiary.name=燃燒導彈
icbm.missile.chemical.name=化學導彈
icbm.missile.anvil.name=砧導彈
icbm.missile.repulsive.name=拒抗性導彈
icbm.missile.attractive.name=吸引性導彈

icbm.missile.fragmentation.name=分裂導彈
icbm.missile.contagious.name=傳染性導彈
icbm.missile.sonic.name=音波導彈
icbm.missile.breaching.name=違反性導彈
icbm.missile.rejuvenation.name=治療性導彈
icbm.missile.thermobaric.name=溫壓性導彈

icbm.missile.nuclear.name=核導彈
icbm.missile.emp.name=EMP磁暴導彈
icbm.missile.conflagration.name=燃烧導彈
icbm.missile.endothermic.name=吸熱導彈
icbm.missile.antiGravitational.name=反地心吸力導彈
icbm.missile.ender.name=瞬移導彈
icbm.missile.hypersonic.name=超音波導彈

icbm.missile.antimatter.name=反物質導彈
icbm.missile.redMatter.name=紅物質導彈

## Special Missiles
icbm.missile.missileModule.name=空壳導彈
icbm.missile.antiBallistic.name=反彈道導彈
icbm.missile.cluster.name=風暴導彈
icbm.missile.nuclearCluster.name=核風暴導彈
icbm.missile.homing.name=追蹤性導彈

## Grenades
icbm.grenade.condensed.name=普用性手榴彈
icbm.grenade.shrapnel.name=散彈手榴彈
icbm.grenade.incendiary.name=燃燒性手榴彈
icbm.grenade.chemical.name=化學性手榴彈
icbm.grenade.anvil.name=砧手榴彈
icbm.grenade.repulsive.name=拒抗性手榴彈
icbm.grenade.attractive.name=吸引性手榴彈

## Explosive Minecarts
icbm.minecart.condensed.name=爆炸矿车
icbm.minecart.shrapnel.name=散彈矿车
icbm.minecart.incendiary.name=燃燒矿车
icbm.minecart.chemical.name=化學矿车
icbm.minecart.anvil.name=砧矿车
icbm.minecart.repulsive.name=拒抗性矿车
icbm.minecart.attractive.name=吸引性矿车

icbm.minecart.fragmentation.name=碎片矿车
icbm.minecart.contagious.name=傳染性矿车
icbm.minecart.sonic.name=音波矿车
icbm.minecart.breaching.name=違反性矿车
icbm.minecart.rejuvenation.name=治療性矿车
icbm.minecart.thermobaric.name=溫壓性矿车

## ICBM Misc Blocks
tile.sulfurOre.name=硫矿石
tile.glassPressurePlate.name=玻璃压板
tile.glassButton.name=玻璃按钮
tile.camouflage.name=伪装
tile.proximityDetector.name=接近探测器
tile.spike.0.name=spike1
tile.spike.1.name=spike2
tile.spike.2.name=spike3

**Comment by ghui9087** [comment]
ok that was not good!
[zh_CN.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/5054627/zh_CN.txt)

**Comment by GHXX** [comment]
The language file you edited was outdated.
Edit the following instead: https://github.com/BuiltBrokenModding/ICBM-Classic/blob/dev/1.12-4.0.2/src/main/resources/assets/icbmclassic/lang/zh_cn.lang

**And please propose the file change using a Pullrequest.**
Just go to that link and click on the pencil icon to edit that file.
Make your changes.
Scroll down to the bottom and enter a message describing what you changed, like "Updated chinese translation"
After that, create a Pullrequest, to propose the changes to us.
