### ISSUE TITLE
Anti-Ballistic Missile is missing

### ISSUE THREAD

**Issue by mechaminu** [BuiltBrokenModding/ICBM-Classic#327]
MC 1.12.2 / Forge 14.23.5.2854 / ICBM 1.12.2-4.0.1b75

Anti-ballistic missile seems to be missing in the game.
Its absence confirmed in both creative menu and missile metadata list(tried all metadata with /give command).

**Comment by GHXX** [comment]
It was removed in 4.x.x since it wasnt working properly at all. We'll add it back in the future.

**Comment by DarkGuardsman** [comment]
Will be added back specifically as a new entity as well. This way it works better then the previous version that faked out the old missile guidance.
