### ISSUE TITLE
Version 4.0.1 for 1.12.2 on Aternos, but curseforge?

### ISSUE THREAD

**Issue by Spaceelliott** [BuiltBrokenModding/ICBM-Classic#329]
im not sure if this is the correct place but the only 4.0.1 i could find on curse was the unstable one, unlike on aternos where there is a stable one.

**Comment by bl4ckscor3** [comment]
I don't know how Aternos displays files, but [this file](https://www.curseforge.com/minecraft/mc-mods/icbm-classic/files/2918052) is the latest version that has been officially released by us on CurseForge. I _assume_ Aternos just fetches the files that are available on CurseForge, so there is probably a discrepancy regarding Aternos displaying files, so you should talk to them about this.
