### ISSUE TITLE
inventory dosent show in cruise launcher

### ISSUE THREAD

**Issue by Spaceelliott** [BuiltBrokenModding/ICBM-Classic#330]

**Comment by Spaceelliott** [comment]
the bug is that your inventory dosent show

**Comment by GHXX** [comment]
What icbm version and what mc version are you using?

**Comment by Spaceelliott** [comment]
version 1.12.2-3.3.0b63

**Comment by GHXX** [comment]
use version 4.x.x (alpha), that should fix it for you

**Comment by GHXX** [comment]
Im assuming this one is solved since you havent replied. If its not, comment and ill reopen it.
