### ISSUE TITLE
Can't craft nuclear explosives

### ISSUE THREAD

**Issue by ghost** [BuiltBrokenModding/ICBM-Classic#331]
I realise this has been raised but the issue seemingly has no been resolved so I wanted to make this to address that. 

IC2 no longer has a recipe in 1.12.2 for crafting uranium ingots however uranium 235 is the equivalent.

I'm currently running a war server and having to manually exchange stuff because this no longer exists.

Please fix this ASAP as it really does ruin what otherwise is an amazing mod. 

Thanks!!

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM-Classic/issues/156
