### ISSUE TITLE
Shutting down internal server

### ISSUE THREAD

**Issue by njsilvadyne** [BuiltBrokenModding/ICBM-Classic#332]
Playing this mod with the 1.12.2 Pack and this error randomly pops up after a few minutes of blowing up nukes, without fail, in every world I've created so far. It pretty much makes them unplayable because almost as soon as I try to load back into them the error occurs again. [Link to the logs](https://drive.google.com/file/d/12NVtT8LWD4fTXm8DJrQrV8I9wcL_b7oZ/view?usp=sharing)

**Comment by DarkGuardsman** [comment]
I'm not seeing ICBM in that log.... tbh it looks like you uploaded a partial log rather than a full log.

**Comment by njsilvadyne** [comment]
> 
> 
> I'm not seeing ICBM in that log.... tbh it looks like you uploaded a partial log rather than a full log.

Sorry, uploaded the wrong log. This should be correct, I searched around at the bottom and it looks like ICBM is mentioned: https://drive.google.com/file/d/1gh3c2ieESAAZnnba_-nxKCu2mT0IOaaF/view?usp=sharing

**Comment by DarkGuardsman** [comment]
Notes for self:
```
Caused by: java.lang.NullPointerException
	at icbm.classic.content.entity.EntityExplosion.writeSpawnData(EntityExplosion.java:63) ~[EntityExplosion.class:1.12.2-4.0.0b20191109044627]
	at net.minecraftforge.fml.common.network.internal.FMLMessage$EntitySpawnMessage.toBytes(FMLMessage.java:213) 
```

icbmclassic@1.12.2-4.0.0.20191109044626
