### ISSUE TITLE
Antimatter issues don't like OpenCubicChunks

### ISSUE THREAD

**Issue by JAcamp1** [BuiltBrokenModding/ICBM-Classic#333]
OpenCubicChunks allows building above and below build limits with the removal of the bedrock floor. The antimatter missile refuses to break anything above or below the limits while other missiles still are effective. Is there a config fix possibly?

**Comment by clienthax** [comment]
https://github.com/BuiltBrokenModding/ICBM-Classic/blob/6ec6ab695a0fadc4a6b14017c71dee042d43bb92/src/main/java/icbm/classic/content/blast/threaded/BlastAntimatter.java#L99 needs to be changed to grab from the current world settings i would guess

**Comment by JAcamp1** [comment]
Makes sense. I'll make a recompile with the edit for my server settings for just server side.

**Comment by JAcamp1** [comment]
#334 may work may not compile properly. I'm not great at java.

**Comment by clienthax** [comment]
That's not the correct way to go about that, I will take a look later

**Comment by DarkGuardsman** [comment]
Have to also keep in mind some of this code is threaded and can't easily pull from the world data. So when making changes to pull from the world take care to make it thread safe.

**Comment by clienthax** [comment]
Made a PR for now, tested it, seems to work nicely
![image](https://user-images.githubusercontent.com/1056270/96288392-42542f80-0fdb-11eb-988e-22b4d2a353e9.png)
