### ISSUE TITLE
Laser designator not working for long ranges?

### ISSUE THREAD

**Issue by heyheyhey123243** [BuiltBrokenModding/ICBM-Classic#336]
Not sure if this is intended or it has already been addressed, but the laser designator doesn't seem to fire the missile if you are firing from a faraway range of the silo. It works fine if I am in view of the silo.

For example, if I load the missile up and everything and walk about 10 chunks away from the silo (or until I can't see the silo anymore). I proceed to use the laser designator, the 2 messages will show up saying that the missile aim and fired but won't ever fire from the silo itself until I walk back into the silo's view or chunk, which then the animation of the firing will play. I've tried using chunk loaders from multiple mods but that doesn't seem to work either. 

Any idea? As of now, I can't use fire missiles using the laser designator unless it's in view of the silo.

**Comment by GHXX** [comment]
Sorry for the super late reply, but do you happen to remember still, if this was in singleplayer, or when playing on a multiplayer-server? If its the latter it might be related to #363

**Comment by heyheyhey123243** [comment]
This was on a singleplayer

**Comment by GHXX** [comment]
What mc version were you using, and what icbm version? if you still remember that

Maybe it was a build which still required chunks to be loaded along the flightpath.

**Comment by heyheyhey123243** [comment]
Was 1.12.2 if I remember correctly. ICBM version was also the latest.
