### ISSUE TITLE
[Radar Crash] Crash: Using laser designator at long ranges

### ISSUE THREAD

**Issue by BathToast** [BuiltBrokenModding/ICBM-Classic#337]
Was attempting to test out the range of the Laser Designator, teleported 9000 blocks away from the launch pad. Used Laser Designator to fire off the missile. After a few seconds crash occurred, log is as follows:

Missile being used was an Antimatter missile, range was about 9300 blocks, give or take, it took about 5 seconds after the laser designation to crash. All T3 equipment was used (Launch pad, Terminal, Stabilizer)

_**Crash Report**_
[crash-2020-10-25_21.47.20-server.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/5436446/crash-2020-10-25_21.47.20-server.txt)

**Comment by GHXX** [comment]
Seems to be radar related rather than laser designator

**Comment by DarkGuardsman** [comment]
Ya the crash points to the radar registry used for tracking missiles when they enter and leave the game world.
