### ISSUE TITLE
Rejuvenation bomb does not exist (version ICBM - Classic 1.12.2-4.0.1b75-UNSTABLE build 75 ) 

### ISSUE THREAD

**Issue by embelcourt** [BuiltBrokenModding/ICBM-Classic#340]
it is supposed to have the rejuvenation bomb but it is not showing up as an item for me.  even though it worked before on my friend's curse forge pack but isn't there on technic did I do something wrong?

**Comment by bl4ckscor3** [comment]
The rejuvenation missile and explosive got intentionally removed in version 4.0.0.
