### ISSUE TITLE
Launcher Support Frame T3 breaks my server

### ISSUE THREAD

**Issue by BaranonEldereth** [BuiltBrokenModding/ICBM-Classic#341]
I have a private server running Yao Pack, and I added  ICBM-classic-1.12.2-4.0.1b20200328215453.
The thing is whenever I put a Launcher Support Frame T3 in the world, it starts looping error messages and effectively DoSes the server.
The fix is to backup to a point prior to plomping down the frame.
I have not tried the T1 and T2 frames nor other blocks of the mod.

Pastebin of the crash log (cut so it would fit pastebin, but contains error loop):
[https://pastebin.com/ShQasm36](https://pastebin.com/ShQasm36)

Thank you very much for your time and hope it is an easy fix!

EDIT: Every block from this mod that you can put down breaks the server, tested it today.

**Comment by GHXX** [comment]
Does it break if you place down any other blocks from other mods that accept ic2 energy? (especially non-ic2 blocks)
