### ISSUE TITLE
Something called the vanilla explosion method

### ISSUE THREAD

**Issue by BarryHarton** [BuiltBrokenModding/ICBM-Classic#342]
ICBM classic has been added to all the mods 3 remix on 1.12
Recipes all work, but when an explosive is set off, we get an error, and no explosion happens. I assume it is to do with conflicting mods but can't work out which one. This happens on both single player and the server.
We originally used the recent file, and changed to version 3.3.0b63 due to the recent one being marked as unstable. However the error still persists.
No crash occurs, only an error and no explosion, the error is below. Thank you

https://pastebin.com/RCX2f5iY

**Comment by bl4ckscor3** [comment]
Add `icbm.classic.content.blast.Blast` to Environmental Creepers' `explosionTypeBlacklist` config and set its `explosionClassListType` config to `blacklist`.
