### ISSUE TITLE
Please help me with the file error!

### ISSUE THREAD

**Issue by blor123** [BuiltBrokenModding/ICBM-Classic#343]
ICBM - Classic 1.12.2-4.0.1b75-UNSTABLE build 75

ICBM - Classic 1.12.2-4.0.1b75-UNSTABLE-deobf build 75

When I put both of the above files in mods file, an error appears below. What's wrong with you?

Forge Mod Loader has found a problem with your minecraft installation 
     You have mod sources that are duplicate E thin your system 
                                  Mod Id : File name 

      icbmclassic : ICBM-Classic-1.12.2-4.0.1b75-deobf.jar 

      icbmclassic : ICBN-classic-1.12.2-4.0.1b75.jar

**Comment by clienthax** [comment]
Remove the deobf one
