### ISSUE TITLE
[1.12.2]Radar Not showing anything

### ISSUE THREAD

**Issue by Xudros** [BuiltBrokenModding/ICBM-Classic#344]
I have a modded server and I wanted to setup a radar for base defense and when I try to use it nothing shows up on the grid so its a bit difficult to do anything when nothing even shows up or sends a redstone signal. I've tried it in singleplayer its the same issue and when I remove all other mods other than mekanism for power it still does not work. and potential fixes because I've tried all that I could think of. 
![radarnotworking](https://user-images.githubusercontent.com/66235508/102301521-89e43280-3f1c-11eb-8f23-1654dbfe680f.png)
I have tried multiple versions of the mod the list is
ICBM-classic-1.12.2-3.3.0b65, ICBM-classic-1.12.2-3.3.0b63, ICBM-classic-1.12.2-4.0.0b74
and each one of them the same problem so is it something with my game? 
Forge version is forge-1.12.2-14.23.5.2854

**Comment by Stennar** [comment]
I have the same issue on a server with ICBM-classic-1.12.2-4.0.1b20200328215453

No players/Radars/Missles showing up.

**Comment by iEx5** [comment]
Same, but shows in 3.3.0b63 for a second before detonation.

**Comment by MrLightside** [comment]
I am also experiencing the same issue. ICBM-classic-1.12.2-4.0.1b75. Singleplayer and Multiplayer.

**Comment by DenisOSVR** [comment]
I'm also having the same problem, I'm using the same version as MrLightside I think and it's in sigleplayer and multiplayer. Is there a way to fix this?

**Comment by BigSpaceships** [comment]
Same thing happening to me. Flans planes also don't show up (it says that they will on the wiki).

**Comment by DevishaPadmaperuma** [comment]
I tried on both ICBM-classic-1.12.2-4.0.1b20200328215453.jar and ICBM-classic-1.12.2-4.0.1b75.jar, the radar still doesn't show anything. (Singleplayer, forge-14.23.5.2846, Minecraft 1.12.2)

**Comment by DevServices-PartAge** [comment]
Same problem on a server and in singleplayer.  Forge 1.12.2-14.23.5.2847.

**Comment by hofq** [comment]
Hey There, Will there be any Update soon to the Radar? it does nothing at the moment, which makes the mod really much useless in survival.

**Comment by bl4ckscor3** [comment]
Yes, we know that the radar seems to be broken. There is no need to keep asking about it if multiple people have already inquired about it. We will look into it, but I cannot say a timeframe.
