### ISSUE TITLE
Crashes on launching minecraft

### ISSUE THREAD

**Issue by ghost** [BuiltBrokenModding/ICBM-Classic#345]
[crash-2021-01-21_01.28.51-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/5843294/crash-2021-01-21_01.28.51-client.txt) - crash report

**Comment by bl4ckscor3** [comment]
Don't use the deobf mod file of ICBM Classic. That one is only for development purposes and does not work in a normal Minecraft client. 
Use this file instead: https://www.curseforge.com/minecraft/mc-mods/icbm-classic/download/2918052/file
