### ISSUE TITLE
No visuals for chemical weapons

### ISSUE THREAD

**Issue by SwilaPlasmark** [BuiltBrokenModding/ICBM-Classic#347]
Is this a known issue or simply something thats on the to do list?

**Comment by DarkGuardsman** [comment]
Most likely particle settings. Can you check if it will work in a new world?

**Comment by GHXX** [comment]
Im assuming you are referring to chemical explosives not showing any particles after exploding? 
(When playing on a multiplayer server) In this case this would be a duplicate of #362
