### ISSUE TITLE
[1.7.10] Control Panel

### ISSUE THREAD

**Issue by ew38** [BuiltBrokenModding/ICBM-Classic#348]
Hi,
I'm using 1.7.10 build 2.16.4b3. When I place a T3 control panel, sometimes it works correctly but other times it turns into a T1 when I right click it and will repeatedly turn back into a T3 and back into a T1 repeatedly. This also causes the GUI to reset everytime and the extra options in the GUI for the T3 such as Lock Height will dissapear and reappear repeatedly also. Its super weird. I've also tried using build 2.16.2b205 from curseforge but that version gives me NoSuchMethodError upon placing the T3 control panel. Pastebin link is for the stack trace for the2b205 crash

https://pastebin.com/mYZbR4Mc

Thanks guys

**Comment by bl4ckscor3** [comment]
Unless kmecpp says otherwise, 1.7.10 is no longer updated by us.

**Comment by kmecpp** [comment]
You probably have the wrong VoltzEngine installed. Use 1.7.10-1.11.0b491

**Comment by ew38** [comment]
Thanks for the replies! I can confirm I'm already using VE 1.7.10-1.11.0b491.
