### ISSUE TITLE
Cannot find certain recipes/craft ones i find the recipe for online

### ISSUE THREAD

**Issue by Tysee1999** [BuiltBrokenModding/ICBM-Classic#350]
Below i have an image attached of the jei/nei of the icbm. The items that are missing (t3 launchher control and a decent bit of the missiles/explosives are showing in the creative menu) but they are not showing up. I have been unable to utilize parts of the mod for example because no matter what ive tried, I cannot craft he t3 launcher panel. I could get the t3 made but I had to look online for that. The T3 launcher panel recipe online I found doesnt work so I am stuck in a pickle at this point and frustrated.
![2021-04-24_18 06 02](https://user-images.githubusercontent.com/83142798/115974084-37e59600-a528-11eb-8c99-549b5432e3e6.png)

**Comment by DarkGuardsman** [comment]
@GHXX can you look into this?

**Comment by Tysee1999** [comment]
I should note I am playing the 1.12.2 pack. I am guessing it’s some sort of ID conflict potentially but I would love to be actually able to craft the t3 launcher

**Comment by GHXX** [comment]
How exactly are you unable to craft the item?
Does the crafting result not show up in the table, or can you not pull out the item?
in that case, ensure that all crafttweaker scrips are thr same on client and server, and also ensure that the icbm version is the same

**Comment by Tysee1999** [comment]
> How exactly are you unable to craft the item?
> Does the crafting result not show up in the table, or can you not pull out the item?
> in that case, ensure that all crafttweaker scrips are thr same on client and server, and also ensure that the icbm version is the same

Crafting result does not appear. I am not the server admin however..is the crafting recipe for the t3 online correct?

**Comment by GHXX** [comment]
iirc, its 6 steel plates on the sides, in the very center an elite circuit (from mekanism or icbm), and in the lower center slot a t2 launcher.
Can you craft the item in singleplayer?

**Comment by GHXX** [comment]
Any news on this @Tysee1999 ?

**Comment by GHXX** [comment]
Ill close this for now, as i suspect its a ct issue, and has nothing to do with icbm. Feel free to comment though, and ill reopen it, if needed :)
