### ISSUE TITLE
Black hole collison crashes server

### ISSUE THREAD

**Issue by Veritius** [BuiltBrokenModding/ICBM-Classic#351]
As the name suggests. To reproduce, just shoot two Red Matter missiles next to eachother.
Also the world becomes unusable.

**Comment by bl4ckscor3** [comment]
Please post the crash-report.

**Comment by Veritius** [comment]
[crash-2021-05-03_16.20.06-server.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/6414901/crash-2021-05-03_16.20.06-server.txt)

**Comment by Veritius** [comment]
Notably this only caused issues in multiplayer. This worked fine in singleplayer.

**Comment by Veritius** [comment]
Really should be confirmation for that. Anyway

**Comment by bl4ckscor3** [comment]
Thanks! It was fixed in a832718eaa19fc7ade553fd5d3e5e747277a4de7, so the next release will no longer have this problem.
