### ISSUE TITLE
CoreProtect compatibility

### ISSUE THREAD

**Issue by Yghore** [BuiltBrokenModding/ICBM-Classic#352]
**Minecraft's version** : 1.12.2 
**Server's version** : Mohist-200-server

The coreprotect plugin (https://www.spigotmc.org/resources/coreprotect.8631), do not save the explosion of ICBM ;(

**Comment by DarkGuardsman** [comment]
Unlikely to happen as we don't support systems outside of forge. I will leave this open in case someone wants to write an addon to ICBM.
