### ISSUE TITLE
i not see the anti ballistic missile

### ISSUE THREAD

**Issue by greenspawner153** [BuiltBrokenModding/ICBM-Classic#353]
i see youtuber play this mod and i download the mods i need from the description and i cant see and find the anti ballistic missile

**Comment by bl4ckscor3** [comment]
It has been removed in version 4.0.0.

**Comment by greenspawner153** [comment]
you can send me the version download please??

**Comment by bl4ckscor3** [comment]
All downloads are here https://www.curseforge.com/minecraft/mc-mods/icbm-classic/files/all
If you want to play with the anti ballistic missile you probably want to install this version https://www.curseforge.com/minecraft/mc-mods/icbm-classic/files/2734676
