### ISSUE TITLE
Will Sentries be updated in Armory for 1.12.2?

### ISSUE THREAD

**Issue by SashaIndustries** [BuiltBrokenModding/ICBM-Classic#354]
Really not a fan of Open sentries and Armory Sentries I couldn't find its Github page will they ever be updated. Got a hardcore PvE world that needs them to stop Xenos and other mobs breaking into my factories of to protect trains and bores

**Comment by bl4ckscor3** [comment]
There is zero reason to post this question on the ICBM-Classic issue tracker.
[This ](https://github.com/BuiltBrokenModding/Armory)is the GitHub repository for Armory, but please do not post these kinds of question there. These are bug trackers, only use them to post bugs and problems with a supported version of the mod. Join the BBM Discord server for these questions and ask in the appropriate channel.

To answer your question, read this big fat red message at the start of Armory's CurseForge page:

https://i.imgur.com/k95CXCc.png

**Comment by DarkGuardsman** [comment]
@bl4ckscor3 is right this is the wrong place to ask. That said, we don't exactly point people to discord on curse either. So it is understandable this was asked in the wrong place.
