### ISSUE TITLE
There is zero reason to post this question on the ICBM-Classic issue tracker.

### ISSUE THREAD

**Issue by SashaIndustries** [BuiltBrokenModding/ICBM-Classic#355]
Someone's a grump and a bit hostile. Would have just let this rest if you had sent the image as I never saw the armory I only went to the Sentries page.

"Zero reason"
This is ICBM Classic, ICBM used to contain the sentries it was taken out as a modification to my knowledge.

"Zero reason"
I could not find the other github so I asked here the only place I knew that was part of the ICBM set.

I don't think theres any harm when I've spent the last 6 hours looking across the internet for this and you show hostility for a post that probably took you 3 minutes to write.

Also just as a reference that text is not bold, and it's not in a fat format so saying fat is just being plain hostile.
I'm not sure what happened in your day but taking it out on random people is not the way to go about it.
Hostility is met with more hostility.
Mr I have a fat attitude.

**Comment by SashaIndustries** [comment]
Also just want to say there are several different armory Curse pages and armory name is already used for other mods too so chances of finding that "fat" message is very low when looking via Google

**Comment by DarkGuardsman** [comment]
Got confused what you were on about then found https://github.com/BuiltBrokenModding/ICBM-Classic/issues/354

@bl4ckscor3 This is what happens when you lock an issue ticket and write posts that sound like you are upset at users. Next time just give them the link to the discord and point them to the information nicely.

**Comment by DarkGuardsman** [comment]
As for an actual answer on ICBM-Sentries. When I originally built the content I never wanted to include it in ICBM. This was done as a peace branch with calclavia to avoid us fighting over content. After calclavia left modding I split it off into it's own content so ICBM could focus on missiles. Sadly due to time limits I have not found the time to update it. Even if it was still part of ICBM it likely would have been dropped to save time.

**Comment by SashaIndustries** [comment]
Thank you for your responses I was not expecting these to be responded to :)
Regardless to if Sentries gets updated or not thank you for the effort in making them.
I got into ICBM due to Voltz and felt the look of the sentries really fit the theme and set themselves apart from other sentries. So thank you for adding that content had probably hours of fun building and testing designs in Voltz and Sentries played a big part in that. 

Now a days I have a modpack with AvP been trying to make multiple PvE threats that are actually worth using an ICBM on, but base defense itself can be hard to automate haha. Making it so me and my sister have something to play.

**Comment by DarkGuardsman** [comment]
Funny enough lack of a good PvE threat has made motivation to work on ICBM hard. Though I have noticed newer versions of MC now contain raids... so this might prove a good reason.

**Comment by SashaIndustries** [comment]
Lots of dungeon mods I have noticed personally.
Chemical warfare could prove fairly useful and bunker busters for dungeons
found using scanners.

Anti-Matter I would say more is to eliminate a threat that gets way too out
of hand which is basically what happens if you use AvP and set spawn limit
to 1000+
The hive can get too hard to do much about. Turrets are good for setting up
a very short base to get health back but noise at least in my pack I am
creating attracts things so more cover while healing before trying to push
again. I feel 1.16 has tons of dungeon and a fair few things to do with
enemy bases that expand over time and the mod that allows for better core
usage also dramatically boosts my frame rate but seems a lot of the more
combat mods are on older minecraft still so a fair bit of mix and match it
feels like.
