### ISSUE TITLE
[Radar] "Potential problem found" popup

### ISSUE THREAD

**Issue by homosapien97** [BuiltBrokenModding/ICBM-Classic#356]
Hi, I was playing the Ad Astra Per Nucleon pack ( https://www.curseforge.com/minecraft/modpacks/ad-astra-per-nucleon ) and ran into https://paste.dimdev.org/amesiconad.mccrash .

There was no crash, but I got a popup saying "Potential problem found!" indicating that the issue was caused by either ICBM-Classic or LagGoggles.

I didn't do anything with ICBM-Classic or LagGoggles in the world yet (very early game, haven't done much of anything).

Hope this is helpful.

Edit: The LagGoggles bug post is here https://github.com/TerminatorNL/LagGoggles/issues/130

**Comment by DarkGuardsman** [comment]
Looks like you have something that caught a crash with our chunk unload
event

**Comment by DarkGuardsman** [comment]
Closing as links seem to be broken
