### ISSUE TITLE
Chemical weapon particles not working on pebble host servers

### ISSUE THREAD

**Issue by AlphaWolf3040** [BuiltBrokenModding/ICBM-Classic#358]
no matter what ive tried the particles wont show i made sure explosions were turned on, i tried doing this in a single player world and it worked fine, im on 1.12.2 if that helps.

does anyone know how to fix this error/glitch/bug 

i am on a pebble host server btw as title says

**Comment by DarkGuardsman** [comment]
Do particles work for other mods?

**Comment by AlphaWolf3040** [comment]
> Do particles work for other mods?

I believe so, yes

**Comment by GHXX** [comment]
likely a duplicate of #362 and appears to be an issue when running just forge + icbm in a client server environment
