### ISSUE TITLE
Shrapnel and anvil explosion entities use arrow hit sound on impact

### ISSUE THREAD

**Issue by strikerrocker** [BuiltBrokenModding/ICBM-Classic#360]
Can be fixed by playing different sound in https://github.com/BuiltBrokenModding/ICBM-Classic/blob/prod/1.12/src/main/java/icbm/classic/content/entity/EntityFragments.java#L423

**Comment by DarkGuardsman** [comment]
Should be easy enough to use different vanilla sounds or hunt down some on freesound.org

Whoever fixes this make sure you get the source of the sound file and add it to the credits. Also make sure we have license rights to use the sounds.

**Comment by DarkGuardsman** [comment]
https://builtbroken.codecks.io/decks/21-lts-1-12/card/1f7-fragment-hit-sound
