### ISSUE TITLE
[1.12] Task: Update launcher models

### ISSUE THREAD

**Issue by strikerrocker** [BuiltBrokenModding/ICBM-Classic#361]
![image](https://user-images.githubusercontent.com/28724985/128631434-9c6dbb7e-1876-4284-9415-5c8cf5d18c80.png)

Expected : To be able to see the frame of the launcher from the other side

**Comment by DarkGuardsman** [comment]
This isn't a bug but a limitation of the models we have. Short of new models I don't expect it to be fixed any time soon.

**Comment by DarkGuardsman** [comment]
Modeled update in v5.x.x
