### ISSUE TITLE
[1.12] Task: Sync Configs

### ISSUE THREAD

**Issue by GHXX** [BuiltBrokenModding/ICBM-Classic#363]
When running in a client server environment, and setting the server "needs electricity" config to true, and setting the client "needs electricity" config to false, the UI in the launcher shows that its ready to launch, even though it is unable to due to having no power.
(This assumes no power is fed to the launcher, and that a missile is loaded)
Clicking the launch button then just doesnt do anything - it also does not throw an error.

**Comment by DarkGuardsman** [comment]
Not fixing for 1.12, will leave modpack makers to ensure files are synced
