### ISSUE TITLE
Creative Menu Crash

### ISSUE THREAD

**Issue by Breadabix** [BuiltBrokenModding/ICBM-Classic#366]
I am using ICBM-classic-1.12.2-4.0.1b75 and going into the creative menu crashes the game. Other than the obvious statement saying its an issue updating screen events I dont know what the issue is.

[crash-2021-08-23_17.27.22-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/7033511/crash-2021-08-23_17.27.22-client.txt)

**Comment by GHXX** [comment]
Cant reproduce this on the current devbranch 9d05c47, so it might have been fixed already.

**Comment by Tommeh1** [comment]
I believe i may have gotten this fixed at some point

**Comment by fmohican** [comment]
https://github.com/Gliese-832-c/ad-astra-per-nucleon/issues/40 ^^

**Comment by Gliese-832-c** [comment]
The important question is: Will it get pushed on CurseForge?

**Comment by DarkGuardsman** [comment]
If its for 1.12 then likely as we have not updated beyond that. If older versions than I leave it up to the community to validate a build for release.

**Comment by Gliese-832-c** [comment]
Sorry for the misunderstanding, I of course indeed was talking about 1.12.2. Looking forward to the release.

**Comment by Gliese-832-c** [comment]
So, has this been pushed to CurseForge? The latest version on CF is from Nov 6, 2021. This time theoretically allows for the changes to be included, but I would prefer official confirmation.

**Comment by bl4ckscor3** [comment]
Git blame doesn't show any change in that timeframe that would support the assumption that it has been fixed, but as previously said we can't reproduce it. It might be a mod interaction problem or something else. Try out the version from November and see if it works for you. In any case, I'll push a safeguard, and that will be included whenever we release 4.2.0.

**Comment by DarkGuardsman** [comment]
Was closed originally due to age of card.
