### ISSUE TITLE
Minecart IDS

### ISSUE THREAD

**Issue by Kaminester** [BuiltBrokenModding/ICBM-Classic#368]
Hello, I'm working on a project where you can select what tnt you want and then push a minecart into the machine and it will turn in to the minecart version of that tnt. But since there are many different minecarts with tnts, i cant really summon enything else but the Explosive Cart. I try to use /summon icbmclassic:cart.bomb and then /summon icbmclassic:cart.bomb:1 but it just says it cant summon that entity. How do i summon minecarts like the anvil tnt, anti-matter tnt and so on

**Comment by Kaminester** [comment]
![2021-09-25_12 29 36](https://user-images.githubusercontent.com/91369681/134766699-fcd14a8e-587a-4a91-a9ac-8858d3217a79.png)

**Comment by DarkGuardsman** [comment]
Explosive data is set via NBT on the carts. Place one normally in the world and then use a tool to check the NBT. From that you can then setup entity spawning.
