### ISSUE TITLE
Radar not working

### ISSUE THREAD

**Issue by jlw1995** [BuiltBrokenModding/ICBM-Classic#369]
Ive read several other issues regarding the same thing but when are the issues like the radar not working, AB missile missing etc going to be fixed?

**Comment by DarkGuardsman** [comment]
Sorry to ignore your issue, I have not been focusing on this mod much. I've closed this card and others to create new cards with specific info https://github.com/BuiltBrokenModding/ICBM-Classic/issues/385 https://github.com/BuiltBrokenModding/ICBM-Classic/issues/384 https://github.com/BuiltBrokenModding/ICBM-Classic/issues/387
