### ISSUE TITLE
Missile Silo Fires Wrong Missile

### ISSUE THREAD

**Issue by hunterdubbs** [BuiltBrokenModding/ICBM-Classic#37]
When firing missiles from a silo (tested with tier 3 silo), all missiles will revert back to the conventional missile upon launch (with its texture and explosion effect).  

found in v. 1.7.10-2.15.1b51

**Comment by DarkGuardsman** [comment]
Might be a rendering issue? I'll check into it in a few mins and have it fixed shortly.

**Comment by DarkGuardsman** [comment]
Ok, just checked its not a rendering issue. Looks like the line that set the explosive type was removed. I have it fixed locally but need to recode a few parts of the launcher frame. Once I have that done I'll push the changes live.
