### ISSUE TITLE
Startup crash java.lang.NoClassDefFoundError: icbm/classic/api/ExplosiveRefs

### ISSUE THREAD

**Issue by xnossisx** [BuiltBrokenModding/ICBM-Classic#373]
While starting the modpack SuperSymmetry on the latest version:
[crash-2021-11-06_20.21.35-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/7491536/crash-2021-11-06_20.21.35-client.txt)
It appears to be an incompatibility with a class from the mod Trinity.

**Comment by bl4ckscor3** [comment]
This is an issue with Trinity, not ICBM-Classic. A file got removed in ICBM which Trinity apparently uses, and it's the Trinity author's job to update their mod to support the new ICBM version that does not contain this file.

**Comment by DarkGuardsman** [comment]
I don't recall what that file was but I suspect it is now named `icbm.classic.api.refs.ICBMExplosives`
