### ISSUE TITLE
Cant remove mod from server or people get fatally missing registry entries error when connecting

### ISSUE THREAD

**Issue by xamareik** [BuiltBrokenModding/ICBM-Classic#377]
I added icbm to my server, and i cant delete it or everyone that tries to join will get the fatally missing registry entries error.

[latest.log](https://github.com/BuiltBrokenModding/ICBM-Classic/files/7730709/latest.log)

**Comment by bl4ckscor3** [comment]
If you remove a previously installed mod, then its content will no longer be there, and forge notifies about that. Clients and servers should have the same mods installed (unless they're clientside/serverside only). That's normal and intended behavior.
