### ISSUE TITLE
Energy/Electricity i can't find energy/elecrticity is that an other mod ?

### ISSUE THREAD

**Issue by Bastiow** [BuiltBrokenModding/ICBM-Classic#379]
I can't find energy in this mod so i cant launch missile is that an other mod ???
![2022-02-18_11 54 33](https://user-images.githubusercontent.com/99962035/154669590-ca5d8863-48c2-40ee-8733-6c4c72615e73.png)

**Comment by bl4ckscor3** [comment]
You need to install a mod that adds energy generators. Immersive Engineering, Actually Additions, Mekanism, ...

**Comment by Bastiow** [comment]
ok thanks

**Comment by GHXX** [comment]
You can also disable the energy requirement in the config file @Bastiow

**Comment by Bastiow** [comment]
How ??
