### ISSUE TITLE
[1.12] Task: Fix radar

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM-Classic#384]
Closed a lot of issues and making this issue as a placeholder;

- Fix threading issues
- Fix redstone isues
- Fix detection being inverted
- Add automated testing

**Comment by DarkGuardsman** [comment]
Tested radar in yesterday's stream... seems to be working in 4.2.X+ version. Not sure if @GHXX or @bl4ckscor3 fixed issues with it in the previous version. Will do more testing but at minimal basic functionality works.

Still need to check threading issues and add automated testing to validate it works.

**Comment by bl4ckscor3** [comment]
Might have been fixed by this? https://github.com/BuiltBrokenModding/ICBM-Classic/pull/370

**Comment by DarkGuardsman** [comment]
Maybe, honestly have no idea without diving the commit history. Since gitkraken is broken on linux I'm loathing to do any advanced git stuff.

**Comment by DarkGuardsman** [comment]
Fixed in 4.3.0 release
