### ISSUE TITLE
Unbreakable block structures not protecting insides against explosives 

### ISSUE THREAD

**Issue by keyboardcat1** [BuiltBrokenModding/ICBM-Classic#390]
Unbreakable blocks such as bedrock, barriers and other unbreakable blocks from external mods don’t protect against the thermobaric and nuclear explosives. Although the block structures themselves do survive, anything contained within them gets destroyed, as opposed to reinforced concrete structures.

**Comment by DarkGuardsman** [comment]
Can you supply the version of minecraft, version of the mod, and picture of the setup.

**Comment by keyboardcat1** [comment]
Minecraft version: 1.12.2, mod version: 4.0.1
Here are pictures of the setup (both structures contained crafting tables before the explosion):
![2022-04-18_19 49 09](https://user-images.githubusercontent.com/56785825/163835233-15242c6e-a5a9-4026-aee1-7a1e3cc7d49e.png)
![2022-04-18_19 49 16](https://user-images.githubusercontent.com/56785825/163835236-423e9591-53da-4e55-a294-9e92c765ec7e.png)
![2022-04-18_19 49 41](https://user-images.githubusercontent.com/56785825/163835240-21b6623d-6fbd-47eb-bf7d-68c25d2417bc.png)
![2022-04-18_19 49 54](https://user-images.githubusercontent.com/56785825/163835246-d8b53c9e-9bb5-4bad-bb9c-79d3f3d04699.png)

**Comment by DarkGuardsman** [comment]
Bedrock should work. I'll confirm later this week. As for external mods I can't say for sure. Since I know a few do some tricks to make things unbreakable without setting the `unbreakable` attribute on the block. Such as a few magic mods that respawn blocks when broken. MFFS also has this issue in newer versions.

**Comment by keyboardcat1** [comment]
Thanks! My main concern is SecurityCraft's unbreakable blocks (yes they have the unbreakable attribute), since that's our main defense mod on my server. Meanwhile we'll just have fun with the flaw :)

**Comment by DarkGuardsman** [comment]
Oh neat, luckily the author of security craft is part of our team.

@bl4ckscor3 any chance you can test your mod with ICBM.

**Comment by bl4ckscor3** [comment]
I already did test it and SecurityCraft's reinforced blocks have the same behavior as bedrock in this case. There must be a special case for reinforced concrete in the blast code, since bedrock and SC's reinforced blocks have the same explosion resistance, while reinforced concrete is merely a little higher than obsidian's.

**Comment by DarkGuardsman** [comment]
We have no special logic as that would be annoying to maintain. The nuke works off energy vs blast resistance. Each block it breaks cost energy and will eventually cause the nuke to stop on the ray trace.

**Comment by bl4ckscor3** [comment]
At a quick glance, this is likely the culprit. The hardness of bedrock and SC's reinforced blocks is -1, while reinforced concrete's is 10. Blocks that have a negative hardness do not count towards the power calculation, resulting in the observed behavior. 
https://github.com/BuiltBrokenModding/ICBM-Classic/blob/7311c17d308bfa09f7b86bf75e36eb65184069ce/src/main/java/icbm/classic/content/blast/threaded/BlastNuclear.java#L116-L119

**Comment by keyboardcat1** [comment]
When will the polish be released?

**Comment by keyboardcat1** [comment]
Is BlastNuclear.java also responsible for thermobaric explosions, since those also have the same issue?

**Comment by bl4ckscor3** [comment]
> When will the polish be released?

The "1.12 Polish" project does not constitute a single version release, but merely a way to keep track of things that need to be done to polish the mod.
> Is BlastNuclear.java also responsible for thermobaric explosions, since those also have the same issue?

Yes, the thermobaric explosive is a less powerful and non-nuclear version of the nuclear explosive :)

**Comment by DarkGuardsman** [comment]
Ya 1.12 polish is an on-going goal with no ETA. We will make releases as we go.

@bl4ckscor3  if you want to release an update or work with @GHXX to do so feel free. I'm in meetings til 6pm today and likely will be too burnout to do mucn.

**Comment by keyboardcat1** [comment]
@DarkGuardsman can I compile a version myself while I wait for the next release?

**Comment by DarkGuardsman** [comment]
Sure, but you can't host it anywhere due to copyright policy on the assets. If you set the version the same you can add it to a server.

**Comment by keyboardcat1** [comment]
Thanks a lot! Yeah I'll just keep it to myself and my friends.
