### ISSUE TITLE
server crashes on start but loads in single player

### ISSUE THREAD

**Issue by archmichaeliii** [BuiltBrokenModding/ICBM-Classic#391]
[crash-2022-04-30_16.29.32-server.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/8597776/crash-2022-04-30_16.29.32-server.txt)

not sure whats going on loads fine in single player but will not load on server.

**Comment by bl4ckscor3** [comment]
This is caused by the sided annotation in the following code of FVTM, and is not our fault. https://github.com/Fexcraft/FVTM/blob/5828f18e5675cf55887342df89a4240a69babab3/src/main/java/net/fexcraft/mod/fvtm/item/BlockItem.java#L41-L42
