### ISSUE TITLE
launching multiple nuclear missiles with the laser designator crashes the game after a few minutes (1.12.2)

### ISSUE THREAD

**Issue by kifirer** [BuiltBrokenModding/ICBM-Classic#397]
(crash logs attached
[crash-2022-06-12_18.45.40-server.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/8886188/crash-2022-06-12_18.45.40-server.txt)
[crash-2022-06-12_18.32.03-server.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/8886189/crash-2022-06-12_18.32.03-server.txt))

**Comment by DarkGuardsman** [comment]
In the future use pastebin or other sites so we don't have to download the logs. Anyways, this is a known bug in the radar system closing into existing issue https://github.com/BuiltBrokenModding/ICBM-Classic/issues/384
