### ISSUE TITLE
Spikes not damaging players

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/ICBM-Classic#40]
All three spike types are not damaging players, they do however damage other living entities like pigs and zombies.

**Comment by Hennamann** [comment]
Now it crashes when the player comes into contact with poison and fire spikes, seems to be client code running on server side: https://gist.github.com/Hennamann/045aaf37b50fc7ee5d567228c0f99398 
The normal spikes work as intended now.

**Comment by DarkGuardsman** [comment]
Nope casting error, will fix
