### ISSUE TITLE
Port to 1.8?

### ISSUE THREAD

**Issue by NefariousIntent2** [BuiltBrokenModding/ICBM-Classic#402]
I need a port to 1.8 for a test I'm doing with other mods. I don't know if it's possible but I will forever be grateful if their was a port.

**Comment by bl4ckscor3** [comment]
No. That's a whole bunch of work that doesn't make sense to do.

**Comment by DarkGuardsman** [comment]
Its actually not even a question of work, 1.8 Forge lacks some of the functionality we need to render our custom .obj models. I would need to custom create new render functionality and likely wire into MC's rendering. Which will almost 100% sure break with mods like optifine and other rendering mods.
