### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by macteed** [BuiltBrokenModding/ICBM-Classic#405]
[crash-2023-02-20_16.52.43-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/10787998/crash-2023-02-20_16.52.43-client.txt)

**Comment by bl4ckscor3** [comment]
You need to download the correct jar file, not the deobf one that is meant for developers. ![An image showing that the first download button is to be used, not any other](https://i.imgur.com/vihXb0z.png)
