### ISSUE TITLE
Crashes during startup

### ISSUE THREAD

**Issue by macteed** [BuiltBrokenModding/ICBM-Classic#406]
[crash-2023-02-20_21.21.53-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/10788990/crash-2023-02-20_21.21.53-client.txt)

**Comment by bl4ckscor3** [comment]
Delete this file and try again. C:\Users\Silas\AppData\Roaming\.minecraft\config\icbmclassic\explosive_reg.json

**Comment by DarkGuardsman** [comment]
If you have not deleted it yet we could use that file to verify why it tried to register missile_module twice.

**Comment by Joey-Destroyah** [comment]
[explosive_reg.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/10856116/explosive_reg.txt)
I got the same issue and I'm glad to donate my copy of the file

**Comment by Joey-Destroyah** [comment]
Thanks for the fix, BTW

**Comment by DarkGuardsman** [comment]
oh I see what happened, I added a locked ID entry for `missile` to 24 and your file has that set for `mutation`. It can be fixed by either letting it regen by deleting the file or changing `mutation` line to something other than 24.
