### ISSUE TITLE
Server crash during startup after a first crash on lauching a colorful grenade

### ISSUE THREAD

**Issue by Lou-fr** [BuiltBrokenModding/ICBM-Classic#407]
Server crash after send a coloruful grenade, and now c'ant start it anymore
`java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1498)
	at net.minecraft.world.World.func_147448_a(World.java:2285)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:942)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:93)
	at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:133)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:104)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:98)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:152)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:421)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:391)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:623)
	at java.lang.Thread.run(Thread.java:748)`

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 1.12.2-a0c0ffb0
	Operating System: Linux (amd64) version 5.10.0-21-amd64
	Java Version: 1.8.0_312, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 2826050184 bytes (2695 MB) / 3623878656 bytes (3456 MB) up to 28631367680 bytes (27305 MB)
	JVM Flags: 2 total; -Xms128M -XX:MaxRAMPercentage=95.0
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version          | Source                                          | Signature |
	|:------ |:-------------------- |:---------------- |:----------------------------------------------- |:--------- |
	| LCHIJA | minecraft            | 1.12.2           | minecraft.jar                                   | None      |
	| LCHIJA | mcp                  | 9.42             | minecraft.jar                                   | None      |
	| LCHIJA | FML                  | 8.0.99.99        | Magma-1.12.2-a0c0ffb0.jar                       | None      |
	| LCHIJA | forge                | 14.23.5.2860     | Magma-1.12.2-a0c0ffb0.jar                       | None      |
	| LCHIJA | micdoodlecore        |                  | minecraft.jar                                   | None      |
	| LCHIJA | biomesoplenty        | 7.0.1.2445       | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar   | None      |
	| LCHIJA | galacticraftcore     | 4.0.2.280        | GalacticraftCore-1.12.2-4.0.2.280.jar           | None      |
	| LCHIJA | galacticraftplanets  | 4.0.2.280        | Galacticraft-Planets-1.12.2-4.0.2.280.jar       | None      |
	| LCHIJA | icbmclassic          | @VERSION@        | ICBM-classic-1.12.2-4.2.0.jar                   | None      |
	| LCHIJA | mts                  | 22.5.0-BETA      | Immersive+Vehicles-1.12.2-22.5.0.jar            | None      |
	| LCHIJA | jei                  | 4.16.1.302       | jei_1.12.2-4.16.1.302.jar                       | None      |
	| LCHIJA | immersiveengineering | 0.12-98          | ImmersiveEngineering-0.12-98.jar                | None      |
	| LCHIJA | immersivepetroleum   | 1.1.10           | immersivepetroleum-1.12.2-1.1.10.jar            | None      |
	| LCHIJA | trackapi             | 1.2              | TrackAPI-1.2.jar                                | None      |
	| LCHIJA | universalmodcore     | 1.1.4            | UniversalModCore-1.12.2-forge-1.1.4-2b81e7.jar  | None      |
	| LCHIJA | immersiverailroading | 1.9.1            | ImmersiveRailroading-1.12.2-forge-1.9.1.jar     | None      |
	| LCHIJA | mekanism             | 1.12.2-9.8.3.390 | Mekanism-1.12.2-9.8.3.390.jar                   | None      |
	| LCHIJA | mekanismgenerators   | 1.12.2-9.8.3.390 | MekanismGenerators-1.12.2-9.8.3.390.jar         | None      |
	| LCHIJA | nuclearcraft         | 2.18y            | NuclearCraft-2.18y-1.12.2.jar                   | None      |
	| LCHIJA | unuparts             | 5.1.4            | UNU+Parts+Pack+[MTS]+1.12.2-21.3.0-5.1.4.jar    | None      |
	| LCHIJA | unucivil             | 5.3.2            | UNU+Civilian+Pack+[MTS]+1.12.2-21.3.0-5.3.2.jar | None      |
	| LCHIJA | unumilitary          | 5.0.0            | UNU+Military+Pack+[MTS]+1.12.2-21.3.0-5.0.0.jar | None      |
	| LCHIJA | voicechat            | 1.12.2-2.3.28    | voicechat-forge-1.12.2-2.3.28.jar               | None      |
	| LCHIJA | worldedit            | 6.1.10           | worldedit-forge-mc1.12.2-6.1.10-dist.jar        | None      |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'Magma'
	Type: Dedicated Server (map_server.txt)

**Comment by bl4ckscor3** [comment]
Which ICBM version are you using?

**Comment by dmodoomsirius** [comment]
@bl4ckscor3 ICBM-classic-1.12.2-4.2.0.jar found in crash log they posted.

**Comment by bl4ckscor3** [comment]
Right, sorry. I didn't check the file name, just the version column.

**Comment by DarkGuardsman** [comment]
Unable to replicate on latest version. Can you provide additional details as we didn't change the code for gas explosives in 4.2.0. It is also the same code that runs Chemical and Debilitation explosives.

**Comment by Lou-fr** [comment]
Okay, so my friend was building and i say "look the new grenade they added" i launch the colorful grenade and the next frame i see"server closed" and this is the first error 
```
java.lang.NoClassDefFoundError: org/lwjgl/util/Color
	at icbm.classic.client.ColorHelper.HSBtoRGB(ColorHelper.java:73)
	at icbm.classic.content.blast.gas.BlastColor.generateRandomColors(BlastColor.java:57)
	at icbm.classic.content.blast.gas.BlastColor.setupBlast(BlastColor.java:38)
	at icbm.classic.content.blast.Blast.doFirstSetup(Blast.java:191)
	at icbm.classic.content.blast.Blast.onBlastTick(Blast.java:162)
	at icbm.classic.content.entity.EntityExplosion.func_70071_h_(EntityExplosion.java:137)
	at net.minecraft.world.World.func_72866_a(World.java:2340)
	at net.minecraft.world.World.func_72870_g(World.java:2294)
	at net.minecraft.world.World.func_72939_s(World.java:2076)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:923)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:800)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.util.Color
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:115)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 15 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at icbm.classic.client.ColorHelper.HSBtoRGB(ColorHelper.java:73)
	at icbm.classic.content.blast.gas.BlastColor.generateRandomColors(BlastColor.java:57)
	at icbm.classic.content.blast.gas.BlastColor.setupBlast(BlastColor.java:38)
	at icbm.classic.content.blast.Blast.doFirstSetup(Blast.java:191)
	at icbm.classic.content.blast.Blast.onBlastTick(Blast.java:162)
	at icbm.classic.content.entity.EntityExplosion.func_70071_h_(EntityExplosion.java:137)
	at net.minecraft.world.World.func_72866_a(World.java:2340)
	at net.minecraft.world.World.func_72870_g(World.java:2294)

-- Entity being ticked --
Details:
	Entity Type: icbmclassic:holder.explosion (icbm.classic.content.entity.EntityExplosion)
	Entity ID: 37
	Entity Name: Explosion[icbm.classic.content.blast.gas.BlastColor@606175ad]
	Entity's Exact location: -5899.05, -1.00, -26401.54
	Entity's Block location: World: (-5900,-1,-26402), Chunk: (at 4,-1,14 in -369,-1651; contains blocks -5904,0,-26416 to -5889,255,-26401), Region: (-12,-52; contains chunks -384,-1664 to -353,-1633, blocks -6144,0,-26624 to -5633,255,-26113)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2076)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['Polo_lulu_YT'/24, uuid='966318ab-1912-34d9-8556-e71fe1bd1196', l='world', x=-5908.93, y=44.20, z=-26404.43, cx=-370, cd=-1651, tl=1933547, v=true, d=false](Polo_lulu_YT at -5908.933005350158,44.200000047683716,-26404.429367251425), EntityPlayerMP['louarn125'/32, uuid='04126ebf-b4ba-3713-93d7-cc028f1fd244', l='world', x=-5903.96, y=43.00, z=-26402.17, cx=-369, cd=-1651, tl=54510, v=true, d=false](louarn125 at -5903.9610404238965,43.0,-26402.171540282525)]
	Chunk stats: ServerChunkCache: 547 Drop: 0
	Level seed: 1977903950976188068
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: {"landScheme":"archipelago","tempScheme":"latitude","rainScheme":"small_zones","biomeSize":"medium","amplitude":1.5211269,"generateBopOre":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":775.493,"mainNoiseScaleY":1092.331,"mainNoiseScaleZ":775.493,"coordinateScale":1268.3944,"heightScale":888.176,"upperLimitScale":1057.1267,"lowerLimitScale":810.6972}
	Level spawn location: World: (-5947,88,-26367), Chunk: (at 5,5,1 in -372,-1648; contains blocks -5952,0,-26368 to -5937,255,-26353), Region: (-12,-52; contains chunks -384,-1664 to -353,-1633, blocks -6144,0,-26624 to -5633,255,-26113)
	Level time: 57088220 game time, 289600 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 84345 (now: false), thunder time: 11725 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:923)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:800)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 1.12.2-a0c0ffb0
	Operating System: Linux (amd64) version 5.10.0-21-amd64
	Java Version: 1.8.0_312, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 3207831112 bytes (3059 MB) / 4184866816 bytes (3991 MB) up to 28631367680 bytes (27305 MB)
	JVM Flags: 2 total; -Xms128M -XX:MaxRAMPercentage=95.0
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version          | Source                                          | Signature |
	|:------ |:-------------------- |:---------------- |:----------------------------------------------- |:--------- |
	| LCHIJA | minecraft            | 1.12.2           | minecraft.jar                                   | None      |
	| LCHIJA | mcp                  | 9.42             | minecraft.jar                                   | None      |
	| LCHIJA | FML                  | 8.0.99.99        | Magma-1.12.2-a0c0ffb0.jar                       | None      |
	| LCHIJA | forge                | 14.23.5.2860     | Magma-1.12.2-a0c0ffb0.jar                       | None      |
	| LCHIJA | micdoodlecore        |                  | minecraft.jar                                   | None      |
	| LCHIJA | biomesoplenty        | 7.0.1.2445       | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar   | None      |
	| LCHIJA | galacticraftcore     | 4.0.2.280        | GalacticraftCore-1.12.2-4.0.2.280.jar           | None      |
	| LCHIJA | galacticraftplanets  | 4.0.2.280        | Galacticraft-Planets-1.12.2-4.0.2.280.jar       | None      |
	| LCHIJA | icbmclassic          | @VERSION@        | ICBM-classic-1.12.2-4.2.0.jar                   | None      |
	| LCHIJA | mts                  | 22.5.0-BETA      | Immersive+Vehicles-1.12.2-22.5.0.jar            | None      |
	| LCHIJA | jei                  | 4.16.1.302       | jei_1.12.2-4.16.1.302.jar                       | None      |
	| LCHIJA | immersiveengineering | 0.12-98          | ImmersiveEngineering-0.12-98.jar                | None      |
	| LCHIJA | immersivepetroleum   | 1.1.10           | immersivepetroleum-1.12.2-1.1.10.jar            | None      |
	| LCHIJA | trackapi             | 1.2              | TrackAPI-1.2.jar                                | None      |
	| LCHIJA | universalmodcore     | 1.1.4            | UniversalModCore-1.12.2-forge-1.1.4-2b81e7.jar  | None      |
	| LCHIJA | immersiverailroading | 1.9.1            | ImmersiveRailroading-1.12.2-forge-1.9.1.jar     | None      |
	| LCHIJA | mekanism             | 1.12.2-9.8.3.390 | Mekanism-1.12.2-9.8.3.390.jar                   | None      |
	| LCHIJA | mekanismgenerators   | 1.12.2-9.8.3.390 | MekanismGenerators-1.12.2-9.8.3.390.jar         | None      |
	| LCHIJA | nuclearcraft         | 2.18y            | NuclearCraft-2.18y-1.12.2.jar                   | None      |
	| LCHIJA | unuparts             | 5.1.4            | UNU+Parts+Pack+[MTS]+1.12.2-21.3.0-5.1.4.jar    | None      |
	| LCHIJA | unucivil             | 5.3.2            | UNU+Civilian+Pack+[MTS]+1.12.2-21.3.0-5.3.2.jar | None      |
	| LCHIJA | unumilitary          | 5.0.0            | UNU+Military+Pack+[MTS]+1.12.2-21.3.0-5.0.0.jar | None      |
	| LCHIJA | voicechat            | 1.12.2-2.3.28    | voicechat-forge-1.12.2-2.3.28.jar               | None      |
	| LCHIJA | worldedit            | 6.1.10           | worldedit-forge-mc1.12.2-6.1.10-dist.jar        | None      |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Profiler Position: N/A (disabled)
	Player Count: 2 / 20; [EntityPlayerMP['Polo_lulu_YT'/24, uuid='966318ab-1912-34d9-8556-e71fe1bd1196', l='world', x=-5908.93, y=44.20, z=-26404.43, cx=-370, cd=-1651, tl=1933547, v=true, d=false](Polo_lulu_YT at -5908.933005350158,44.200000047683716,-26404.429367251425), EntityPlayerMP['louarn125'/32, uuid='04126ebf-b4ba-3713-93d7-cc028f1fd244', l='world', x=-5903.96, y=43.00, z=-26402.17, cx=-369, cd=-1651, tl=54510, v=true, d=false](louarn125 at -5903.9610404238965,43.0,-26402.171540282525)]
	Is Modded: Definitely; Server brand changed to 'Magma'
	Type: Dedicated Server (map_server.txt)
```

**Comment by DarkGuardsman** [comment]
That is a different crash then the original you posted... luckily looks simple to fix.

**Comment by DarkGuardsman** [comment]
Commit f8bcd6633fec06f0ebe9097bffbbf42e58426026 should fix things

**Comment by Lou-fr** [comment]
what can i do with you commit ?

**Comment by DarkGuardsman** [comment]
Nothing, that is just for our own tracking while I upload the file to curse.  https://www.curseforge.com/minecraft/mc-mods/icbm-classic/files/4406083

**Comment by Lou-fr** [comment]
Okay work fine now, thanks to fix it !
