### ISSUE TITLE
Tooltip Error

### ISSUE THREAD

**Issue by FireFox1324** [BuiltBrokenModding/ICBM-Classic#408]
When I look at the missiles and and the explosives in JEI it just shows tooltip error, see log. It also has no name in the creative menu.

**Comment by DarkGuardsman** [comment]
Can you provide versions and screenshots of the issue. As last version tested with JEI doesn't show the issue.

**Comment by FireFox1324** [comment]
I'm on 1.12.2 with ICBM 4.2.1, I'm new to using github so I don't really know how to upload stuff. I was messing around with it and found that if I disable Trinity the problem goes away. I think the problem is between ICBM and Trinity and not JEI.

**Comment by bl4ckscor3** [comment]
I suppose Trinity needs to be updated to support the new ICBM versions then, as it adds support for ICBM. This may have been broken by all the recent changes.

**Comment by FireFox1324** [comment]
Ok that makes sense, probably doesn't help that I'm using an older version of trinity so I can use the non-overhauled version of nuclearcraft. Thank you for your time, I think I'm gonna try using the newer version and see if that helps any.

**Comment by FireFox1324** [comment]
Using the most resent version of NCO and Trinity still causes the issue, I've found using NC and Trinity 0.3.b doesn't cause it though. I put in a comment on the issues page on curse for trinity so I'm gonna close this one cause I think it's just an issue with trinity. Thank you both for your time.
