### ISSUE TITLE
Error Using ICBM V5 on a 1.12.2 Server

### ISSUE THREAD

**Issue by SeamusMullan** [BuiltBrokenModding/ICBM-Classic#410]
I've recently been getting a crash on a minecraft server using ICBM v5.0. The crash report is on the attached pastebin link but I'm currently unsure about whats actually happening and what i can do to fix it. The main error is as follows

Description: Exception in server tick loop
net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: icbm.classic.config.ConfigClient

The full crash report
https://pastebin.com/sZTJcY4b

The server is running OpenJDK 1.8.0 on Ubuntu 22.10

Hope to hear back soon about this!

**Comment by DarkGuardsman** [comment]
Interesting, seems forge is trying to load the client side config. Will fix it here later as it should be easy enough.

**Comment by DarkGuardsman** [comment]
Should be fixed in 5.1.0, curse might take a bit to process but once done link should work https://www.curseforge.com/minecraft/mc-mods/icbm-classic/files/4485952
