### ISSUE TITLE
Can I translate the mod and which file is responsible for texts and stuff?

### ISSUE THREAD

**Issue by MorgoWizard** [BuiltBrokenModding/ICBM-Classic#428]
Hi, I'm having trouble with item names and stuff when playing in my native language, so can you suggest how I could translate everything myself and such, hehehe

**Comment by DarkGuardsman** [comment]
feel free to make a pull request as we happily take help in translating the mod. Should be able to find a few guides online how to edit the files and submit them to github. With the github part usually being the hardest for those not use to technical tools.

Here is an example: https://github.com/BuiltBrokenModding/ICBM-Classic/pull/226

Then the 1.12 branch or dev branch https://github.com/BuiltBrokenModding/ICBM-Classic/tree/dev/1.12-5.x.x is a good place to branch to start a translation. As it should have updated files.
