### ISSUE TITLE
Missile not visible while approaching. No chance to intercept them.

### ISSUE THREAD

**Issue by shit-png** [BuiltBrokenModding/ICBM-Classic#429]
Hi, 
i tried to intercept the missiles but when they move over build limit (256 blocks) they are no longer shown on the radar and can during this stage not be intercepted until they hit their target.

Is there any way i didn´t see something or is this behaviour intendet?

**Comment by DarkGuardsman** [comment]
I'll take a look but the radar should be able to detect anything inside it's max range. As it doesn't care about the minecraft world or build height. It uses ICBM's radar registry to track any entity. Which is a separate data structure that anything can connect to to report position and size.

Some useful things to keep in mind, radar only runs every 3 ticks ( 3/20 second). As well only triggers for protection area. So if detection range is 500 (which is max) but trigger range is 50. Then radar will not go off until it detects a potential impact within 50m of itself.

**Comment by shit-png** [comment]
Well, i can´t find the comment anymore but i have read that the missile renders out at a certain target distance or launch height. 
I have watched the missiles on radar for nearly 3 seconds after they started, then dissapear and another 3 seconds later appear on radar at target location. Redstone trigger was the same.
To reproduce: Launcher is ~200 blocks away from radar and SAM. Target is ~50 blocks after SAM Station. 3 Radars are set with  (Trigger:Detection) 50:100, 200:400, 500:600. Every missile launched 100 block or nearer will be detected the whole way till impact.

**Comment by DarkGuardsman** [comment]
Yep, not only do vanilla entities stop rendering above world height... something I think forge slightly fixes. We also have a simulation system in ICBM. Where the missile will upload from the world to continue flying through unloaded chunks. Saving on performance issues and complications of chunk loading during flight. Which can cause SAM systems to have a shorter window of attack.

Also it is important to note the detection range of a radar is in 3D. So if you set it to 400 it means it can only detect 400 up as well. Meaning any missile coming down from orbit is hard to see. 

Yes, your test noticies the one downside with the simulation system. The radar can't see the missiles. As simulation system is meant to act as orbital flight. So was never intergrated with radar. This shouldn't be a large issue as the missile will always spawn back in high above the target. Giving time to hit the missile... just maybe not a lot of time.

We do have plans to solve for this during the radar rework. Which hopefully will introduce longer range detection and intergrate with the simulation system. This might be a while before being implemented as i'm the only dev and am limited on time.

**Comment by DarkGuardsman** [comment]
This has been improved in v6
