### ISSUE TITLE
EMP Tower crash in server and suggestion

### ISSUE THREAD

**Issue by Boulldog0** [BuiltBrokenModding/ICBM-Classic#435]
Hello !

Today i will report you a new bug in 1.12.2 version of ICBM. On a server, the EMP tower, when a missile approaches the if and it is in working order, instead of deleting/deactivating the missile, the if crashes the server and despawn.

And I have an addition suggestion for future versions, why not add an option in the mod configuration to change the resistance of certain hard blocks like obsidian, because I haven't seen anything that does that in the current versions of icbm and this could be interesting for certain servers which wish to implement certain obsidian breaking features via missiles for example.

**Comment by DarkGuardsman** [comment]
Can you include the crash.

As for block resistance we had that feature once but removed it in favor of
other mods.
