### ISSUE TITLE
Can’t interrupt missiles

### ISSUE THREAD

**Issue by Shweps7** [BuiltBrokenModding/ICBM-Classic#436]
Hey, is there an option to cancel the missile from disappearing in the air? Because when it’s disappearing I can’t interrupt them… when they launched the radar launches the anti ballistic but the missile disappearing couple seconds before the anti ballistic missile reaching him… when the missile go down the radar activates the anti ballistic missile again but it’s to late…

**Comment by DarkGuardsman** [comment]
can change the simulation height in the config

**Comment by Shweps7** [comment]
Ohh, where I can find the config? And if I put the simulation height to the maximum it’s not going to disappear in the air and do a full arch until the impact?

**Comment by Shweps7** [comment]
> can change the simulation height in the config

Ohh, where I can find the config? And if I put the simulation height to the maximum it’s not going to disappear in the air and do a full arch until the impact?

**Comment by DarkGuardsman** [comment]
Can access it in game via the mod options, but it might still vanish if the logic thinks it can't safely travel through chunks. As the reason it does this is to avoid chunk loading.

**Comment by Shweps7** [comment]
> Can access it in game via the mod options, but it might still vanish if the logic thinks it can't safely travel through chunks. As the reason it does this is to avoid chunk loading.

Ohh ok thanks🙏
