### ISSUE TITLE
Compatibility issue between trinity and the icbm classic mod.

### ISSUE THREAD

**Issue by Thunderrock424242** [BuiltBrokenModding/ICBM-Classic#437]

**Comment by bl4ckscor3** [comment]
Can you please provide more info such as a log, reproduction steps, and used versions of Minecraft, Forge, Trinity, and ICBM Classic?

**Comment by Thunderrock424242** [comment]
> Can you please provide more info such as a log, reproduction steps, and used versions of Minecraft, Forge, Trinity, and ICBM Classic?
[latest.log](https://github.com/BuiltBrokenModding/ICBM-Classic/files/13851814/latest.log)
crashed on start mc 1.12.2 forge icbm classic latest version trinity also

**Comment by bl4ckscor3** [comment]
Report this to Trinity. The mod is made for an older version of ICBM Classic, and it needs to get updated to fix this.
