### ISSUE TITLE
FX error crash 

### ISSUE THREAD

**Issue by nextjr** [BuiltBrokenModding/ICBM-Classic#44]
I'm running this on a server and during missile impact, if there is a player nearby to view it the server crashes, if anyone knows a temporary fix that keeps functionality that would be fantastic. 

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 3/7/17 11:08 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
	at icbm.classic.content.explosive.blast.BlastEMP.doExplode(BlastEMP.java:174)
	at icbm.classic.content.explosive.blast.Blast.explode(Blast.java:146)
	at icbm.classic.content.explosive.ex.ExEMP.doCreateExplosion(ExEMP.java:29)
	at icbm.classic.content.explosive.Explosive.createExplosion(Explosive.java:207)
	at icbm.classic.content.entity.EntityMissile.explode(EntityMissile.java:468)
	at icbm.classic.content.entity.EntityMissile.onImpactTile(EntityMissile.java:279)
	at com.builtbroken.mc.prefab.entity.EntityProjectile.handleBlockCollision(EntityProjectile.java:292)
	at com.builtbroken.mc.prefab.entity.EntityProjectile.func_70071_h_(EntityProjectile.java:260)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at icbm.classic.content.explosive.blast.BlastEMP.doExplode(BlastEMP.java:174)
	at icbm.classic.content.explosive.blast.Blast.explode(Blast.java:146)
	at icbm.classic.content.explosive.ex.ExEMP.doCreateExplosion(ExEMP.java:29)
	at icbm.classic.content.explosive.Explosive.createExplosion(Explosive.java:207)
	at icbm.classic.content.entity.EntityMissile.explode(EntityMissile.java:468)
	at icbm.classic.content.entity.EntityMissile.onImpactTile(EntityMissile.java:279)
	at com.builtbroken.mc.prefab.entity.EntityProjectile.handleBlockCollision(EntityProjectile.java:292)
	at com.builtbroken.mc.prefab.entity.EntityProjectile.func_70071_h_(EntityProjectile.java:260)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Entity being ticked --
Details:
	Entity Type: icbmclassic.ICBMMissile (icbm.classic.content.entity.EntityMissile)
	Entity ID: 127555
	Entity Name: entity.icbmclassic.ICBMMissile.name
	Entity's Exact location: 162.67, 48.43, 93.76
	Entity's Block location: World: (162,48,93), Chunk: (at 2,3,13 in 10,5; contains blocks 160,0,80 to 175,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.24, -1.38, 0.15
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [GCEntityPlayerMP['nextjr'/1756, l='world', x=190.75, y=64.88, z=78.38]]
	Chunk stats: ServerChunkCache: 819 Drop: 0
	Level seed: -92270588370115038
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (1,138,27), Chunk: (at 1,8,11 in 0,1; contains blocks 0,0,16 to 15,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 60004151 game time, 5239194 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 6099 (now: false), thunder time: 58363 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4653276184 bytes (4437 MB) / 5360320512 bytes (5112 MB) up to 6681526272 bytes (6372 MB)
	JVM Flags: 2 total; -Xmx7168M -Xms4096M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 103
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 108 mods loaded, 108 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (mcforge.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (mcforge.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.1.11} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.5.1.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	3DManeuverGear{1.7.10-@MAJOR@.@MINOR@.@REVIS@} [3D Maneuver Gear] (3DManeuverGear-1.7.10-0.6.jar) 
	UCHIJAAAA	bspkrsCore{6.16.sincommand} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.sincommand.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	abyssalcraft{1.9.1.3} [AbyssalCraft] (AbyssalCraft-1.7.10-1.9.1.3-FINAL.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.19} [BuildCraft] (buildcraft-7.1.19.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.19} [BC Silicon] (buildcraft-7.1.19.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.19} [BC Transport] (buildcraft-7.1.19.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.19} [BC Factory] (buildcraft-7.1.19.jar) 
	UCHIJAAAA	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.5.jar) 
	UCHIJAAAA	lightsabers{1.1} [Advanced Lightsabers Mod] (AdvancedLightsabers-1.7.10-1.1.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJAAAA	betterrecords{1.7.10-1.2.1} [Better Records] (betterrecords-1.7.10-1.2.1.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.19} [BC Energy] (buildcraft-7.1.19.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.19} [BC Builders] (buildcraft-7.1.19.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.19} [BC Robotics] (buildcraft-7.1.19.jar) 
	UCHIJAAAA	candycraftmod{Beta 1.3} [CandyCraft] (CandyCraft-1.3.jar) 
	UCHIJAAAA	catwalks{2.0.4} [Catwalks Mod] (catwalks-2.0.4.jar) 
	UCHIJAAAA	catwalkmod{x.x.x} [Legacy Catwalk Compat] (catwalks-2.0.4.jar) 
	UCHIJAAAA	chancecubes{1.7.10-2.3.2.126} [Chance Cubes] (ChanceCubes-1.7.10-2.3.2.126.jar) 
	UCHIJAAAA	ChestTransporter{2.0.6} [Chest Transporter] (ChestTransporter-1.7.10-2.0.6.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	claysoldiers{2.0.0-beta.2} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0-beta.2.jar) 
	UCHIJAAAA	LookingGlass{0.2.0.01} [Looking Glass] (LookingGlass-1.7.10-0.2.0.01.jar) 
	UCHIJAAAA	OpenComputers{1.6.1.11} [OpenComputers] (OpenComputers-MC1.7.10-1.6.1.11-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	CompactMachines{1.7.10-1.21} [Compact Machines] (compactmachines-1.7.10-1.21.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) 
	UCHIJAAAA	DeathCounter{4.0.0} [DeathCounter] (DeathCounter-4.0.0.jar) 
	UCHIJAAAA	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
	UCHIJAAAA	ElecCore{1.4.294} [ElecCore] (ElecCore-1.7.10-1.4.294.jar) 
	UCHIJAAAA	Emotes{1.0} [Emotes] (Emotes 1.0.1.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.464.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.464.jar) 
	UCHIJAAAA	ExtraPlanets{1.0-3.8} [ExtraPlanets] (ExtraPlanets-1.0-Pre 3.8.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJAAAA	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCHIJAAAA	VoltzEngine{0.28.5.367} [Voltz Engine] (VoltzEngine-1.7.10-0.28.5b367-dev-universal.jar) 
	UCHIJAAAA	icbmclassic{2.15.1.77} [ICBM-Classic] (ICBM-classic-1.7.10-2.15.1b77-universal.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	journeymap{5.1.4} [JourneyMap] (journeymap-1.7.10-5.1.4-unlimited.jar) 
	UCHIJAAAA	mcheli{1.0.3} [MC Helicopter] (mcheli) 
	UCHIJAAAA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	mffs{0.50} [Modular Forcefield System] (Mffs-1.7.10-0.0.51b39-universal.jar) 
	UCHIJAAAA	numina{0.4.1.104} [Numina] (Numina-0.4.1.104.jar) 
	UCHIJAAAA	powersuits{@VERSION@} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.1.109.jar) 
	UCHIJAAAA	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCHIJAAAA	NotEnoughWands{1.2.3} [Not Enough Wands] (notenoughwands-1.2.3.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJAAAA	openmodularturrets{2.2.10-233} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.10-233.jar) 
	UCHIJAAAA	ParticleMan{v1.0} [Particle Man] (ParticleMan-1.4.1.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.10.1} [ProjectE] (ProjectE-1.7.10-PE1.10.1.jar) 
	UCHIJAAAA	quiverchevsky{b101c} [QuiverBow] (QuiverBow_1.7.10_b101d.zip) 
	UCHIJAAAA	ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.7.10.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.406.jar) 
	UCHIJAAAA	SpawnCommands{2.2.2} [SpawnCommands] (SpawnCommands-2.2.2-mc1.7.10-forge.jar) 
	UCHIJAAAA	Sync{4.0.1} [Sync] (Sync-4.0.1.jar) 
	UCHIJAAAA	tc{4.3.0_002} [Traincraft] (TrainCraft-4.3.0_002.jar) 
	UCHIJAAAA	vending{1.2.3} [vending] (vending-v1.2.3.jar) 
	UCHIJAAAA	waystones{1.0.4} [Waystones] (Waystones-mc1.7.10-1.0.4.jar) 
	UCHIJAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCHIJAAAA	ZAMod{v1.10} [Zombie Awareness] (zombieawareness-1.7.10-1.10.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@681a1efa) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@7e0736dd) returned non-null result: 0
	CoFHCore: -[1.7.10]3.1.3-327
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	ThermalFoundation: -[1.7.10]1.2.5-115
	ThermalExpansion: -[1.7.10]4.1.4-247
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from compactmachines-1.7.10-1.21.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:ON, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [GCEntityPlayerMP['nextjr'/1756, l='world', x=190.75, y=64.88, z=78.38]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by DarkGuardsman** [comment]
Looks like some client code is rendering server side. I should have it fixed soon.

**Comment by nextjr** [comment]
So where can I download the fix after you update it? Through curse still? Or is there a better place to grab it?

**Comment by dmodoomsirius** [comment]
Every build is auto uploaded to curse as a alpha. Just need to wait for curse mods to approve it.

**Comment by nextjr** [comment]
Oh cool thanks

**Comment by dmodoomsirius** [comment]
They are on our maven but at times it's hard to navigate. I do hope to get a page per mod on the main site at least for downloads if not at least for while we wait for curse to approve people can still test said mod. I'll try to get that going over the next couple of weeks.

**Comment by DarkGuardsman** [comment]
The issue is fixed. The bug was in (VE)VoltzEngine and not ICBM-Classic itself so you will need to update VE.
