### ISSUE TITLE
[1.12] v6 - Missing recipes

### ISSUE THREAD

**Issue by xJon** [BuiltBrokenModding/ICBM-Classic#443]
All Bomblets apart from Conventional don't seem to have a recipe in-game.
Also the Cluster Missile with 50x Payload Parachutes, and the Smoke Marking Explosives don't seem to have recipes.
Not sure if intentional or not

**Comment by DarkGuardsman** [comment]
Bomblets might be intentional if I remember right, as I haven't tested scale of a large cluster for each. As volume defaults need to be set to avoid overpacking clusters with blasts that can't handle scale well. Such as 50 antimatters.

Can you send me a screenshot of the others, not sure I'm understanding.

**Comment by xJon** [comment]
![image](https://github.com/BuiltBrokenModding/ICBM-Classic/assets/8945347/dcbbde65-0b8f-441d-88e3-7f1457a384f5)
![image](https://github.com/BuiltBrokenModding/ICBM-Classic/assets/8945347/c3e903c3-0a6e-4fad-a99b-a657aa064f2f)

**Comment by xJon** [comment]
~~There are also two recipes for Spikes:
![image](https://github.com/BuiltBrokenModding/ICBM-Classic/assets/8945347/5907925f-64c7-46ba-a7cb-a73388055397)~~

**Comment by DarkGuardsman** [comment]
> There are also two recipes for Spike

Checking into this, I'm only seeing a single recipe in the file system. So not sure why this would be generating more than one. Given I can't test with JEI i'm unable to replicate currently.

**Comment by xJon** [comment]
@DarkGuardsman Updated the issue 👍

**Comment by DarkGuardsman** [comment]
Not seeing these issues unless JEI support is disabled.

**Comment by xJon** [comment]
I did have JEI support enabled. Do you mean after https://github.com/BuiltBrokenModding/ICBM-Classic/commit/8588675cfce55f92f722e8f6b12904215871d854?
