### ISSUE TITLE
How To Counter Tracker

### ISSUE THREAD

**Issue by LogicalMaximus** [BuiltBrokenModding/ICBM-Classic#445]
I have been playing on a server with the tracker enabled and I was wondering if there was a way to counter the tracker being on you

**Comment by DarkGuardsman** [comment]
if the version has a jammer it should work. That said we haven't had a functional tracker in the mod since 1.6.4 (9 years ago), 1.7.10 (7 years ago) had a partially working one for some versions... its fully gone in the 1.12 version with no plans to restore it.
