### ISSUE TITLE
[1.12] v6 - Config max values

### ISSUE THREAD

**Issue by xJon** [BuiltBrokenModding/ICBM-Classic#446]
![image](https://github.com/user-attachments/assets/67bd326b-d9b8-442f-844f-e87a7c624479)
Is 2.147483647E9 supposed to be something like 10000000000000000000?

**Comment by bl4ckscor3** [comment]
2.147483647E9 represents 2.147483647×10^9 and equals 2147483647 which is the maximum number that an Integer (whole number) can be in Java and [is the maximum these config values are set to](https://github.com/BuiltBrokenModding/ICBM-Classic/blob/2046a8e78cd71ee00a0c3ef4542216a3d12c6e86/src/main/java/icbm/classic/config/blast/types/ConfigNuclear.java#L13). This notation is just how it's displayed in the config.

**Comment by DarkGuardsman** [comment]
Discord is likely better for questions, but ya forge configs represent large numbers oddly. Beyond that realistically max size is like 200~ish. As those blasts are not very performance but eh... someone has a super computer they can try.
