### ISSUE TITLE
T3 frame launched missile frame issue

### ISSUE THREAD

**Issue by nextjr** [BuiltBrokenModding/ICBM-Classic#45]
When any missile is fired from a t3 launcher frame this happens and the rocket stays even after the structure is broken.
![2017-03-08_10 53 19](https://cloud.githubusercontent.com/assets/12243052/23714066/91252be4-03ed-11e7-98be-c010298813c0.png)

![2017-03-08_10 40 39](https://cloud.githubusercontent.com/assets/12243052/23713548/ea5c4280-03eb-11e7-8804-7e509f53e2f9.png)

![2017-03-08_10 44 01](https://cloud.githubusercontent.com/assets/12243052/23713708/5c10d92c-03ec-11e7-8738-a3ac4a2f7697.png)
![2017-03-08_10 44 25](https://cloud.githubusercontent.com/assets/12243052/23713715/5ea1ab4e-03ec-11e7-8ee7-ae0d55c39605.png)
![2017-03-08_10 44 25_2](https://cloud.githubusercontent.com/assets/12243052/23713716/60288b90-03ec-11e7-9ee5-1bd0312eaa63.png)
![2017-03-08_10 44 27](https://cloud.githubusercontent.com/assets/12243052/23713720/62611e86-03ec-11e7-8d1b-9d642fcaa58f.png)
![2017-03-08_10 44 52](https://cloud.githubusercontent.com/assets/12243052/23713732/6d3e6930-03ec-11e7-8ef4-965658cf01bd.png)

**Comment by DarkGuardsman** [comment]
Do the missiles go away after reloading the world?

**Comment by DarkGuardsman** [comment]
Through testing, I think this might be a client side issue. Will see if I can fix it shortly.
