### ISSUE TITLE
Hypersonic missile is tiny on all launchers

### ISSUE THREAD

**Issue by nextjr** [BuiltBrokenModding/ICBM-Classic#46]
when placed in any launcher frame the hypersonic missile is absolutely tiny and adorable. but the visual bug still happens with the floating missile. but the missile operates and still blows things up very well.

![2017-03-08_10 47 21](https://cloud.githubusercontent.com/assets/12243052/23713888/032bca00-03ed-11e7-9664-12f9b2f8dba4.png)
![2017-03-08_10 49 50](https://cloud.githubusercontent.com/assets/12243052/23713891/04e5dd18-03ed-11e7-9e48-2bef55ea5e19.png)
![2017-03-08_10 47 13](https://cloud.githubusercontent.com/assets/12243052/23713894/071f9bb4-03ed-11e7-98f1-6bd8a311d5aa.png)
![2017-03-08_10 47 16](https://cloud.githubusercontent.com/assets/12243052/23713896/08002882-03ed-11e7-878c-a1e0b9b72c76.png)
![2017-03-08_10 47 18](https://cloud.githubusercontent.com/assets/12243052/23713897/08ddf55e-03ed-11e7-9104-5bd0f6a879c3.png)
![2017-03-08_10 47 21](https://cloud.githubusercontent.com/assets/12243052/23713900/0bedb19e-03ed-11e7-8abb-3521882b5818.png)

**Comment by DarkGuardsman** [comment]
Known issue will fix here shortly... Was originally going to wait on an updated model but it can be corrected in code.
