### ISSUE TITLE
Chunk loading?

### ISSUE THREAD

**Issue by nextjr** [BuiltBrokenModding/ICBM-Classic#47]
I've been testing on my server and in single player and it doesn't seem tat missiles will fly through unloaded chunks will this be fixed in the future?

**Comment by dmodoomsirius** [comment]
That is how it was originally written. I am not sure if Darkcow will fix it.

**Comment by DarkGuardsman** [comment]
Not going to fix, the old chunk loading system had a lot of issues. Here later I will update it to the ICBM rewrite's way of handling things.

**Comment by nextjr** [comment]
Any approximation on when you'll add it? Only reason why I'm wondering is I would loooove to be able to use this on my server, but if you have to walk under or dig with the missile it kinda ruins the sneakyness of an airstrike.

**Comment by spacebuilder2020** [comment]
You used to ride the missles

**Comment by DarkGuardsman** [comment]
Not sure when I will have time to add it.

Also @spacebuilder2020 missiles riding will be re-added soon. It was removed by mistake when I recoded the missiles for the update.
