### ISSUE TITLE
Server crashes trying to resolve EntityFX

### ISSUE THREAD

**Issue by spacebuilder2020** [BuiltBrokenModding/ICBM-Classic#48]
I am getting a server crash when getting near an active antimatter explosion.  The error seems to be due to trying to resolve a client side class.  Based on the crash report, it is happening here.

https://github.com/BuiltBrokenModding/ICBM-Classic/blob/development/src/main/java/icbm/classic/content/explosive/blast/BlastRedmatter.java#L132

At first, I thought it was #44 but after applying that fix it still crashes.

Below is the full crash report running on ICBM-Classic version 2.15.1b77

http://pastebin.com/mdyxu5aW

**Comment by DarkGuardsman** [comment]
It's most likely actually crashing the in the block entity class itself. If I recall right I render dig particles inside of the class. I should have it fixed shortly, it just needs to be updated to my new effect system.
