### ISSUE TITLE
Radar item

### ISSUE THREAD

**Issue by mesl** [BuiltBrokenModding/ICBM-Classic#50]
Hi i installed icbm classic and all the dependencies
but it looks like the radar block doesn't work

Kind regards, Merlyn

**Comment by DarkGuardsman** [comment]
Now is it the entire tile or just the GUI?

**Comment by mesl** [comment]
the entire tile

**Comment by DarkGuardsman** [comment]
Ok, I'll look into it the first chance I get. Which could be a while as I'm short on time due to working on the 1.8 update for ICBM at the moment.

I suspect that the issue most likely is the tile is not updating correctly, or classic missiles are not adding to the radar grid.

**Comment by DarkGuardsman** [comment]
Finally got a chance to work on the radar, the code was working correctly to detect missiles. However, redstone support was missing and packet handling was not finished. This meant the tile was not usable in its current state but works now :)
