### ISSUE TITLE
[1.7.10] Anti-gravitational missing effects?

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#53]
As of ICBM-classic-1.7.10-2.15.1b153 / VoltzEngine-1.7.10-1.3.0b82, anti-gravitational explosive is having inconsistent effect:
1- there's no audio
2- when placed on top of 10x10x10 cube of obsidian, stone is seen flying while effectively no obsidian is damaged

In general, there's "fuse" audio on explosives, so it might be related.
In the logs, I've seen no 'missing resources' related to audio.

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.
