### ISSUE TITLE
[1.7.10] Exothermic could use more effects with snow, sand and obsidian

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#54]
As of ICBM-classic-1.7.10-2.15.1b153 / VoltzEngine-1.7.10-1.3.0b82, exothermic explosive are a bit inconsistent:
- on Obsidian, no lava, fire nor netherrack appears to be placed. I would expect at least fire.
- on Sand, only fire is placed. It feels weird. I would expect some nethetrack and a bit of lava.
- on Snow, nothing is done. I would expect is vaporised or flowing water?

I understand obsidian shouldn't get replaced with netherrack, but fire could still be added on top of it.

In comparison:
- Dirt gets fire, a bit of lava and netherrack.
- Stone gets a lot of netherrack and some lava.
- Sandstone is largely replaced with lava.
- Ice and water are mostly removed.
- Wood is largely replaced with fire.
- Clay is largely replaced with wire and a bit of lava.

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.
