### ISSUE TITLE
[1.7.10] Flying fluids rendered as thin slices or items

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#55]
As of  ICBM-classic-1.7.10-2.15.1b153 / VoltzEngine-1.7.10-1.3.0b82, anti-gravitational and endo/exothermic explosive are creating flying water blocks.
Those fluid blocks are rendered as their item forms (some thin slices) instead of full fledged blocks.

![image](https://cloud.githubusercontent.com/assets/4776032/26321527/5debb1f6-3f27-11e7-9243-f992f8c84384.png)

**Comment by LemADEC** [comment]
This also applies to lava.

**Comment by GHXX** [comment]
Closing all 1.7.10 issues since we are no longer supporting it officially and its unlikely that it receives any patches.
