### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by SupremeMortal** [BuiltBrokenModding/ICBM-Classic#60]
Commit https://github.com/BuiltBrokenModding/ICBM-Classic/commit/79afa74f8f1f7cedd665b7251dc4af393076cf6b seems to be giving me compile errors:
https://hastebin.com/suquzofaja.pas

**Comment by DarkGuardsman** [comment]
I just finished pushing everything a few mins ago. You will need to update your copy of VE API.
