### ISSUE TITLE
Right-clicking with missile in hand on the launcher platform sides results in game crash

### ISSUE THREAD

**Issue by luetzj** [BuiltBrokenModding/ICBM-Classic#65]
[crash-2017-06-05_14.43.28-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/1053002/crash-2017-06-05_14.43.28-client.txt)

Seems to occur with any missile on any launch platform.

**Comment by DarkGuardsman** [comment]
Update to the latest VE and ICBM-Classic. Most likely the version of ICBM-Classic you are using does not have the updated Multi-block code required by VE.
