### ISSUE TITLE
Fix tooltips

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM-Classic#7]
- [x] Defuser - missing info and needs shift info translation
- [x] Radar Gun - missing translation
- [x] Rocket Launcher - missing shift translation
- [x] Signal Disrupter - shift info translation
- [x] Tracker - shift info translation, info is after shift
- [x] Remote Detonator - using ICBM-New translation
- [x] Laser Designator - using ICBM-New translation

**Comment by LemADEC** [comment]
+ Typo in various tooltips: these -> there's, strait, titian, etc. as of 1.7.10-2.15.1b33

**Comment by DarkGuardsman** [comment]
I've fixed a few of the typos but if you could list the exacts that would be great.

**Comment by LemADEC** [comment]
Here's a pass on ICBM-classic-1.7.10-2.15.1b37-universal:
Contagious: sounds incorrect to me =>"Have you ever heard the plague?" or "Never heard of the plague? now you will know..."
Rejuvenation: missing uppercase on first word + "to find" sounds incorrect to me => "You can't be blamed for damage if there's none to be found..."?
Thermobaric: country name with capital letters + maybe be more elusive to avoid the political statement
Redmatter: I'm miss the "you guys the bomb..." part? 
EMP tower: probably too long for a single line + missing the damage on incoming missiles
Launcher platforms: replace store with hold?

Some other tweaks proposals:
Sonic: "Who needs to be a ninja to sneak in after that much noise?"
Breaching: "Hole in the wall!"
Nuclear: "Hi! I'm a nuclearholic..."

**Comment by DarkGuardsman** [comment]
A lot of the Redmatter translations are jabs and pokes at Yogscast for messing up beautifully with the redmatter. I might change a few of them to fit better and be less yogscast based.... was having a bit too much fun. I might also take time to code most of these to only show up for servers that have yogscast staff on for extra fun.

Other than that I will apply those changes as they do sound better, Thank you again for the help :) 

Also, I would like to note I wrote all of these at too tired o'clock in the morning.
