### ISSUE TITLE
Anti-Ballistic missile doesn't work

### ISSUE THREAD

**Issue by TheLastSpectre** [BuiltBrokenModding/ICBM-Classic#71]
The anti-ballistic missile doesn't destroy any incoming missiles. It simply follows the missile down to the ground, and explodes, allowing the other missile to explode to it's fullest effect.

**Comment by DarkGuardsman** [comment]
I might increase the speed but generally, the missile should be fired ahead of the target.

**Comment by TheLastSpectre** [comment]
That isn't what I meant, but thanks for the reply. I fired the missiles directly at each other, using the radar to launch the anti-ballistic missile. However, the anti-ballistic missile doesn't explode, or destroy the missile. It just meets up with it and does nothing.

EDIT: I tested the missile again with no other mods installed (except Thermal Expansion for power), and it worked perfectly fine. Sorry to bother, this is my problem, not yours. Keep up the great work!
