### ISSUE TITLE
Incompatibility with Other mods Due to RF API

### ISSUE THREAD

**Issue by HowLife** [BuiltBrokenModding/ICBM-Classic#75]
[crash-2017-10-05_14.43.06-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/1359082/crash-2017-10-05_14.43.06-client.txt)

This Issue has been appearing repeatedly. Any mod that doesn't have the RF API version 1.7.10R1.0.12 is not working with ICBM. As soon as you disable it works flawlessly. I have verified that It is ICBM that has the problem. It is an issue that I find that I cannot fix as I don't know how to swap the RF API.

**Comment by DarkGuardsman** [comment]
Didn't know they were still updating the 1.7 API. We have been packaging the API in VoltzEngine as a shortcut to implement RF support. I will go ahead and rework it so its no longer a problem. A quick solution is to open up the VoltzEngine.jar and remove the cofh folder. This should solve the problem as the code only lightly depends on the API.

Also, that crash has nothing to do with RF, so I assume you uploaded the wrong one.
