### ISSUE TITLE
Crash without any logs, errors and crash reports

### ISSUE THREAD

**Issue by Tommeh3** [BuiltBrokenModding/ICBM-Classic#77]
My modpack crashes without logging anything whatsoever regardless of which version of this mod that i use, even if i throw all the other mods out(it runs fine on the server though(togeather with all mods)), if you wanna use the modpack to find the issue, use this private link in the techniclauncher http://api.technicpack.net/modpack/craftalot-reloaded-test
And defensetech causes issues with way too many plugins which makes it unusable

**Comment by Tommeh3** [comment]
Fixed, it turned out to be caused by the newest forge version for 1.7.10

**Comment by dmodoomsirius** [comment]
Very weird as we compile against that version for 1.7.10. I am not finding any newer forge version since 12/09/15 11:08 PM on http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html
