### ISSUE TITLE
Can't place explosive blocks, causes crash

### ISSUE THREAD

**Issue by mikeonator** [BuiltBrokenModding/ICBM-Classic#78]
[2017-11-19-4.log](https://github.com/BuiltBrokenModding/ICBM-Classic/files/1485925/2017-11-19-4.log)

when i place an explosive, it crashes the game, none of the other blocks in the modpack do this, only the explosive blocks themselves. I've been trying to make a modpack, and the classic icbm is way better, but I cant get it to work

[Edit]

Also, when i try to use a rocket launcher, the same thing happens

**Comment by DarkGuardsman** [comment]
Unable to replicate the issue with VoltzEngine and ICBM-Classic. Though you are one version behind as well  Resonant Engine is no longer a supported mod. It's very likely this last part is the issue as VoltzEngine includes some parts of the old API. Which have yet to be fully removed from the current version. So using an older mod like ResonantEngine will cause issues. 

UCHIJAAAA	ResonantEngine{3.0.0} [Resonant Engine] (resonant-engine-3.0.0.214-core.jar)

**Comment by mikeonator** [comment]
Yo thanks man, that totally fixed the problem!
