### ISSUE TITLE
Feature: Missile decor blocks

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM-Classic#81]
Simple decoration versions of all missiles

**Comment by GHXX** [comment]
What might work is making missiles placeable, so we don't have deco variants of every missile since i personally find that confusing.

**Comment by DarkGuardsman** [comment]
https://builtbroken.codecks.io/decks/14-icbm-backlog/card/1fc-missile-deco-blocks
