### ISSUE TITLE
Crash on server 1.12.2

### ISSUE THREAD

**Issue by Kowantify** [BuiltBrokenModding/ICBM-Classic#86]
ICBM Classic Version: 2.16.3b8
Voltz Version: 1.7.3b14

Just crashed the server and client (not sure if client crashed because of the same thing or the server crashing) when placing a launcher screen in-front of the actual launcher, Thanks!
https://pastebin.com/CkCX1UuJ

**Comment by dmodoomsirius** [comment]
ICBM-Classic is in alpha for 1.12.2. We know things are broken. We know they need work.

**Comment by DarkGuardsman** [comment]
@dmodoomsirius Stop telling that to everyone, you sound like a bot lol

@DarkMatterXCIX Fixed in next VE release, took me a while to hunt down the issue.

**Comment by Kowantify** [comment]
Lol I know things are broken I'm not complaining you he's hard at work, I'm just putting any crash reports I find here as it may be of some sort of help :D

**Comment by DarkGuardsman** [comment]
:D I know you're not complaining and in this case I would not have caught the bug. As I rarely do server testing these days.

**Comment by Kowantify** [comment]
Awesome! I can be server test Guinnea Pig!
