### ISSUE TITLE
1.12 rewrite to make ICBM-Classic standalone

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM-Classic#89]
In order to better support updating ICBM-Classic I've decided to gut VE and make the mod standalone. In order to do this there is a range of tasks needed:

- [x] Create a lightweight VE - delete anything not used by ICBM-Classic
- [x] Merge lightweight VE into ICBM-Classic
- [x] Change any package names to not conflict with VE if updated to 1.12 again
- [x] Cleanup any junk code - if not used or useful, delete
- [ ] Rewrite radar system - VE version is too heavy for a standalone, can be trimmed to fit the mod
- [ ] Rewrite radio system - ditto above
- [ ] Rewrite thread system - the current system used by the old 1.6 code is not efficient at all
- [x] Rewrite usage of Pos system - this will remove dep on Coding Lib
- [ ] Rewrite effects - currently not updated and depended on VE's effect system
- [ ] Rewrite audio - ditto above
- [ ] Rewrite API - we have no solid events or compatibility
- [ ] Rewrite MultiBlock - we only have 3 blocks for such a complex solution
- [ ] Design resources - VE contained all resources both ores and items. We need to see if ICBM needs said items
- [ ] Design tools - ditto above, need to check if ICBM needs any tools or could features be changed to avoid the need. An example is replacing the sneak-wrench on radar to active redstone with a GUI button.
- [x] Design energy - see if we should just stick with Forge Energy only or include the Universal Energy system in VE. The latter would be useful for the EMP.

**Comment by danielpearceofficial** [comment]
This will be very interesting can't wait to see it finished!
