### ISSUE TITLE
Placing panel/frame/launcher on block

### ISSUE THREAD

**Issue by MaciejJedlinski** [BuiltBrokenModding/ICBM-Classic#92]
I know you guys are aware that this version is obviously broken but because I don't know of what EXACTLY you are aware I'm posting this here.

I was able to reproduce this with only Launcher Control Panels, Lanucher Support Frames and Launcher Platforms of all tiers. 

So for example I have Launcher Platform Tier 1 and Launcher Platform Tier 2. When I place the first one, then break it and place the second one in the same place everything is fine. But something strange happens when I try to place any of the panels in the same exact spot. Lets say it's tier 3 one. It will not place tier 3 panel but instead its corresponding launcher platform. Same in the opposite direction: I place tier 2 panel, break it, place tier 1 launcher but tier 1 panel appears on the ground. Breaking it on Survival gives you the item you were placing not the one which actually appeared.

Useful info:
Minecraft version: 1.12.2
Forge version: 1.12.2-14.23.1.2607
Volt Engine: 1.12.2-1.7.3b21
ICBM Classic: 1.12.2-3.0.0b14

Other mods installed:
Hwyla-1.8.23-B38_1.12
InventoryTweaks-1.63
jei_1.12.2-4.8.5.147
minetogether-1.10.2-1.8.7
MouseTweaks-2.8-mc1.12.1

**Comment by DarkGuardsman** [comment]
Almost sounds like a rendering bug or block state issue. I'll check into it here soon.

**Comment by DarkGuardsman** [comment]
Forgot to close this when I fixed it, but it should be fixed
