### ISSUE TITLE
Chemical Grenade and Explosive Not Generating Effect

### ISSUE THREAD

**Issue by ToffeeMax** [BuiltBrokenModding/ICBM-Classic#93]
Minecraft Version: 1.12.2
ICBM Classic Version:  ICBM - Classic 1.12.2-3.0.0b15-UNSTABLE-deobf build 15 for 1.12.2
Desc: The Chemical Explosive does not produce the previous effect from the 1.7.10 version.
Previous Effect:
![2018-02-25_10 27 39](https://user-images.githubusercontent.com/11787561/36640482-7f77b2cc-1a17-11e8-83cf-14c65fd38f3d.png)
Current Behaviour:
![2018-02-24_23 43 10](https://user-images.githubusercontent.com/11787561/36640495-c134a9e0-1a17-11e8-9c90-d5b29ae99da9.png)

**Comment by DarkGuardsman** [comment]
Known issue, effects have not be updated for any explosive in the 1.12 version

**Comment by ToffeeMax** [comment]
Closing this as I have realised this in in a previous post (#89)- and makes mention of re-writing effect system.
