### ISSUE TITLE
Change gas explosives to work in air range

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM-Classic#95]
Currently, any gas based explosive will damage any entity in range. Doesn't matter were that entity is (say behind a wall or in a bunker) the effect will be applied.

To fix this the explosives should be changed to map the area of effect. This can be done with a simple pathfinder that locates all reachable air blocks. 

Implementing this change should improve quality of life for players. As sealed blocks and walls will have an effect on how these explosive types are balanced.

**Comment by GHXX** [comment]
Fixed in blast-rewrite: 309fbec66d74be3aa21d4d619d232f8e78370ab0
