### ISSUE TITLE
Change gas explosives effect area to scale with time

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/ICBM-Classic#96]
At the moment gas based explosives move to max area size even though the graphics scale over time. This is poorly designed as user feedback from the visual gives the false impression of safety. This should be fixed but not just because of the visuals. The other reason is to improve gameplay by having a delay for max range. In which a player can run away before the effect is applied.

**Comment by GHXX** [comment]
Fixed in blast-rewrite: 309fbec66d74be3aa21d4d619d232f8e78370ab0
